### ISSUE TITLE
implementing multiple association joins

### ISSUE THREAD

**Issue by Exanimous** [jbox-web/ajax-datatables-rails#100]
I have been able to get a single has_many association working, like below:

```
Organisation.joins(:members).all
```

I am unsure how to include several separate associations together in the get_raw_records method.

Obviously, doing:

```
Organisation.joins(:members, :subjects).all
```

does not work, and I can't seem to find any specific examples of how to do this.
I am not entirely sure about what syntax I should be using.

**Comment by antillas21** [comment]
@Exanimous take a look at the following code so you can adapt to your specific case:

``` ruby
# models
class Agent < ActiveRecord::Base
  has_many :orders
end

class Client < ActiveRecord::Base
  has_many :orders
end

class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :agent
end

# schema.rb
ActiveRecord::Schema.define(version: 20150421214741) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "agents", force: true do |t|
    t.string   "name"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "clients", force: true do |t|
    t.string   "name"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "orders", force: true do |t|
    t.integer  "client_id"
    t.string   "order_number"
    t.string   "data"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "po_number"
    t.float    "total"
    t.integer  "agent_id"
  end

  add_index "orders", ["agent_id"], name: "index_orders_on_agent_id", using: :btree
end


# orders_controller.rb
class OrdersController < ApplicationController
 # GET /orders
  # GET /orders.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: OrdersDatatable.new(view_context) }
    end
  end
end

# orders_datatable.rb
class OrdersDatatable < AjaxDatatablesRails::Base

  def_delegator :@view, :number_to_currency

  # a note here: I am using this gem's v-0-4-0 branch,
  # if you are using the gem's 0.3.0 version,
  # just replace this method with the usual `sortable_columns`
  # and `searchable_columns` methods
  def view_columns
    @view_columns ||= [
      'Order.id', 'Client.name', 'Client.email',
      'Agent.name', 'Order.total'
    ]
  end

  def data
    records.map do |record|
      [
        record.id,
        record.client.name,
        record.client.email,
        record.agent.name,
        number_to_currency(record.total.to_f)
      ]
    end
  end

  private

  def get_raw_records
    Order.joins(:client, :agent)
    # sometimes more efficient:
    # Order.includes(:client, :agent).references(:client, :agent)
  end

  # ==== Insert 'presenter'-like methods below if necessary
end
```

And finally my view

``` html
<h1>Listing orders</h1>

<%= link_to 'New Order', new_order_path %>

<table class="enhanced" data-url="<%= orders_path(format: :json) %>">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Client Name</th>
      <th>Client Email</th>
      <th>Agent Name</th>
      <th>Order Total</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
      $('.enhanced').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('.enhanced').data('url'),
        "pagingType": "full_numbers",
      });
  });
</script>
```

And, to show it all works as expected, take a look at these screenshots
![dt-initial-load](https://cloud.githubusercontent.com/assets/333671/7263668/8aac69ee-e838-11e4-98f1-723030c16522.jpg)
![dt-searching](https://cloud.githubusercontent.com/assets/333671/7263669/8d3b5080-e838-11e4-8faf-975c153e9003.jpg)

**Comment by antillas21** [comment]
BTW @Exanimous ... please take this into consideration when writing your `get_raw_records` method:

_You need_ to return an `ActiveRecord::Relation` object as the result of this method.... please be aware that Rails 3, returns an `Array` when you call `.all` in an `ActiveRecord` query, example:

``` ruby
Organisation.joins(:members, :subjects).all
# this will return an Array if you're in Rails 3
```

but it will return an `ActiveRecord::Relation` object if you're using Rails 4+

``` ruby
Organisation.joins(:members, :subjects).all
# this will return an ActiveRecord::Relation object
```

Now, an `Array` **is not what we need** in order to continue chaining the gem's functionality, so you can filter, sort and paginate records... so, put special care to **always return** an `ActiveRecord::Relation` object.

Your original query, if under Rails 3, can be:

``` ruby
Organisation.joins(:members, :subjects)
# this will return an ActiveRecord::Relation object
# __this is what we need__, to make the gem work as expected
```

**Comment by Exanimous** [comment]
Thanks for the examples - I have made some progress on my tables that use has_many relationships.

Now I am having some issues with has_many :through associations.

For example, the following code:

```
Organisation.joins(:org_memberships).all
```

Only returns the first Organisation model and the related Organisation through the join table (these models use a self-referential association.  I would like to pull all the Organisation parent models (to populate the entire table)

**Comment by antillas21** [comment]
@Exanimous perhaps if you take a look at this issue: https://github.com/antillas21/ajax-datatables-rails/issues/82 you can extract a solution from it... there's a link to a gist file that presents a similar scenario (self-referential associations) and presents a possible solution for it.

This is one of the scenarios that inspired the recent work in branch `v-0-4-0` of this gem... so, you may as well check it out.

**Comment by Exanimous** [comment]
I was able to get this working by using the following syntax:

```
Organisation.includes(:members, :subjects).references(:members, :subjects)
```

And then mapping the association results like the following:

```
record.subjects.map(&:full_name).join(', '),
```

and

```
record.members.map(&:name).join(', '),
```
