### ISSUE TITLE
get_raw_records with polymorphic associations

### ISSUE THREAD

**Issue by Exanimous** [jbox-web/ajax-datatables-rails#103]
Currently I have hit a snag with implementing my has_many :through polymorphic models with the datatables.

I have been able to create two separate queries that work with the associations individually.
Subject and Organisation are polymorphic derivatives of each other, and belong to the Entry model.

```
def get_raw_records

Entry
    .joins( "INNER JOIN `subjects` ON `entries`.`entity_id` = `subjects`.`id`" )
    .where( entries: { entity_type: 'Subject' } )

Entry
    .joins( "INNER JOIN `organisations` ON `entries`.`entity_id` = `organisations`.`id`" )
    .where( entries: { entity_type: 'Organisation' } )
```

The issue I am having is I need to combine these two rails queries into a single query, and not having extensive experience with directly writing MySQL queries, I have hit a roadblock on this.

**Comment by Exanimous** [comment]
I have changed the query to:

```
Entry.joins("LEFT OUTER JOIN `subjects` ON `entries`.`entity_id` = `subjects`.`id` LEFT OUTER JOIN `organisations` ON `entries`.`entity_id` = `organisations`.`id`")
```

This enables full sorting/searching on the Subject model, but the Organization model is un-searchable/sortable.

**Comment by ajahongir** [comment]
@Exanimous I am not sure what exactly you want.
but I thing you have to use aliasing when joining table. something like this:

``` ruby
Entry.joins("
  LEFT OUTER JOIN `subjects` AS `s` ON `entries`.`entity_id` = `s`.`id`
  LEFT OUTER JOIN `organisations` AS `o`  ON `entries`.`entity_id` = `o`.`id`
").order('o.title DESC').order('s.title DESC')
```

?

**Comment by Exanimous** [comment]
I was able to solve this by the following:

```
Entry.includes(:subject, :organisation).references(:subject, :organisation).distinct
```

The trick was to modify my entry model association declaration as follows to ensure my Entry model can directly pick up on the subject/organisation polymorphic associations. (This syntax is rails 4 and above only)

```
belongs_to :subject, -> { where(entries: {entity_type: 'Subject'}) }, foreign_key: 'entity_id'
belongs_to :organisation, -> { where(entries: {entity_type: 'Organisation'}) }, foreign_key: 'entity_id'
```

**Comment by antillas21** [comment]
@Exanimous would you like to contribute this to the `README`?
