### ISSUE TITLE
Datatable custom column searching

### ISSUE THREAD

**Issue by ajahongir** [jbox-web/ajax-datatables-rails#104]
I seems this gem searches only for global searching. how about custom column searching like this: 
http://www.datatables.net/release-datatables/examples/api/regex.html

**Comment by antillas21** [comment]
@ajahongir this is a planned feature to be released sometime soon. And @mebezac developed this in our [v-0-4-0 branch](https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0), so if you need this feature, please use that branch :wink:

**Comment by ajahongir** [comment]
@antillas21 thank you.

**Comment by ajahongir** [comment]
@mebezac how about this way using view_columns option?
https://github.com/ajahongir/ajax-datatables-rails/pull/1

in this way you will able to define any columns you want not all of columns.

**Comment by mebezac** [comment]
@ajahongir thanks for your input! You would also need to change https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/base.rb#L42-L45. 

Personally I like using an array with all columns in the view, because if you add a new column to the middle of the table in the html, you just need to add that column in the correct place in the `view_columns` array. If it were a hash, you would have to add that column to the hash and then change all the keys for any columns to the right of the column you just added.

@antillas21 what do you think?

**Comment by ajahongir** [comment]
@mebezac

> if you add a new column to the middle of the table in the html, you just need to add that column in the correct place in the view_columns array. If it were a hash, you would have to add that column to the hash and then change all the keys for any 

in my case I have 10 columns on a table and want to filter or sort only on 2 columns, and I have no to define all of columns.

if you care that if your hash order will change after adding a new col. https://github.com/antillas21/ajax-datatables-rails/pull/87 is fine for this.

``` ruby
def view_columns
  @view_columns ||= {
    first_name: 'User.first_name',
    last_name: 'User.last_name', 
    bio: 'User.bio'
  }
end
```

**Comment by ajahongir** [comment]
> You would also need to change https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/base.rb#L42-L45.

thanks

**Comment by antillas21** [comment]
@mebezac and @ajahongir I have some questions...

``` ruby
# if you make this:
def view_columns
  @view_columns ||= {
    first_name: 'User.first_name',
    last_name: 'User.last_name', 
    bio: 'User.bio'
  }
end

# and you manage to edit this:

# def searchable_columns
#    searchable_indexes = params[:columns].map {|k, v| k.to_i if v[:searchable] == 'true' }.compact
#    @searchable_columns ||= view_columns.values_at(*searchable_indexes)
# end

# into something like:
def searchable_columns
  searchable_cols = params[:columns].map {|k, v| v[:name] if v[:searchable] == 'true' }.compact
  @searchable_columns ||= view_columns.values_at(*searchable_cols.map(&:to_sym))
end
```
- what changes do you need in your JS code?
- what other changes do you need in the `AjaxDatatablesRails::Base` class? I'm guessing none, but that's off the top of my head.

**Comment by ajahongir** [comment]
@antillas21 I was thinking about this: 

``` ruby
def view_columns
    # Declare strings in this format: ModelName.column_name
    # or in aliased_join_table.column_name format
    @view_columns ||= {
      "id" => "Flight.id",
      "departure_date" => "Flight.departure_date",
      "arrival_date" => "Flight.arrival_date",
      "code" => "Flight.code"
    }
end
```

``` ruby
def aggregate_query
  conditions = view_columns.map do |data_attr, column|
    searching_column = params[:columns].values.find { |col| col[:data] == data_attr }
    if searching_column
      value = searching_column[:search][:value]
      regex = searching_column[:search][:regex] == 'true'
    end
    search_condition(column, value, regex) unless value.blank?
  end
  conditions.compact.reduce(:and)
end
```

> what changes do you need in your JS code?

no changes

but it seams will some problems with current ordering field

**Comment by ajahongir** [comment]
https://github.com/ajahongir/ajax-datatables-rails/pull/1

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/pull/105

**Comment by antillas21** [comment]
Guys, I'm missing a point here... why don't we start by pointing out why is a good idea to have a hash with `keys` pointing to a `Model.column` if we're going to treat them as an `Array` later on...

**Comment by ajahongir** [comment]
@antillas21
In this way it is not matter order of columns on table. and you will not have problem when you add a new column to your table.

later, we can define other useful options in a hash. for example right now I am having a problem with typecasting(covering this issue - https://github.com/antillas21/ajax-datatables-rails/issues/75). thomething like this:
- like
- like_full
- eql_positive
- date_between
- date_by_day
- eql

``` ruby
@view_columns ||= {
  'id' => { field: 'User.id', type: :eql },
  'first_name' => { filed: 'User.first_name', type: :like_full }
  'bio' => 'User.bio'
}
```

what do you think guys about this idea?

**Comment by antillas21** [comment]
Mmh... somehow this sounds interesting... never thought about extending a column definition, so it could help later on with typecasting, but what if, to simplify things a little bit then:

``` ruby
def view_columns
  @view_columns ||= [
    { source: "User.id" },
    { source: "User.last_login_from", type: :ip },
    { source: "Property.complicated_field", type: :json }
  ]
end
```

This is:
- We define an `Array` of `Hashes`
- By default, all columns are typecasted to text-like behavior in its corresponding db (mysql, sqlite, postgresql)
- Developer can "override" typecasting if needed
- Leave door open to extend/override when more cases are brought to our attention

@ajahongir , @mebezac what do you think about this?

**Comment by ajahongir** [comment]
> Guys, I'm missing a point here... why don't we start by pointing out why is a good idea to have a hash with keys pointing to a Model.column if we're going to treat them as an Array later on...

## 

> We define an Array of Hashes

## 

@antillas21 I am really dont understant why you dont want to use columns definition as a hash?

my procs in this case is:
- you have to not describe every column if you dont want to use ordering all searching for all of your columns at client side
- you should not to change order of columns when you change order or add column at client side.
- ability to define more options for every column.

**Comment by antillas21** [comment]
@ajahongir I am not reluctant to adding such functionality... my comment was because I needed to understand what will be gained if we change the implementation to use a `Hash` map instead, as opposed to the current `Array` or an `Array of Hashes`.

**Comment by ajahongir** [comment]
@antillas21 
It seems it is possible to use `Array` of `Hashes`. in this case you have to desctibe column data field:

``` ruby
@view_columns ||= [
  { data: 'id', source: 'User.id', type: :integer, cond: :eq },
  { data: 'first_name', source: 'User.first_name', type: :json, cond: :like },
  { data: 'bio', source: 'User.bio' }
]
```

`data` attribute will connect to our `source` with datatable columns.

**Comment by antillas21** [comment]
I like where this is going... I'm not totally sure on the `cond` key, as the purpose of jQuery.dataTables is to filter records as you type along in a search box, so, a `like` filtering mechanism and not `eq` is what is needed, but to be able to map source and typecast is a nice thing to have.

What do you think @mebezac ?

**Comment by mebezac** [comment]
Sorry for taking so long to read through this. I really do the like the idea of an array of hashes, or hash of hashes and being able to add more functionality (e.g. different type-casting per column) down the road. I think hash of hashes would make the most sense, something like

```
def view_columns
  @view_columns ||= {
   0:  { source: "User.id" },
   1:  { source: "User.last_login_from", type: :ip },
   2:  { source: "Property.complicated_field", type: :json }
  }
end
```

**Comment by ajahongir** [comment]
guys can you please look at my changes - https://github.com/antillas21/ajax-datatables-rails/pull/105
may be it is possible to accept some of concepts from there?

**Comment by ajahongir** [comment]
I am not finished yet. It requires to refine search conditions, It should be simple do define/redefine custom search condition.

**Comment by antillas21** [comment]
@ajahongir I just recently had a chance to review what you've done in that PR.

I am now adding comments to that specific PR thread, so we can discuss it further... rest assured that I like what you've done so far, just have minor comments to make, and believe the PR comment thread would be the best place to discuss.

So, follow me there :)
