### ISSUE TITLE
Weird issue that only occurs when serverSide: true

### ISSUE THREAD

**Issue by Exanimous** [jbox-web/ajax-datatables-rails#106]
I have noticed I am having a strange issue that only occurs when server side processing is enabled.

I have a Person model, with the following associations:

```
has_many :posts, -> { order "start_date DESC" }, dependent: :destroy
has_many :organisations, through: :posts
has_many :secondary_orgs, through: :posts
```

I am storing two subject-organisation foreign keys on my post join model to represent rare case scenarios where a person needs to have two organisations stored (foreign keys are organisation_id and secondary_org_id)

The issue is:

```
Person.includes(:organisations, :secondary_orgs).references(:secondary_org).distinct
```

The second organisation (represented by :secondary_orgs) is not searchable when json is passed back from the server (perhaps because the organisation model is duplicated).

It works fine when serverSide: true is removed in the coffeescript files.

**Comment by antillas21** [comment]
@Exanimous this looks pretty like the scenario described here: https://github.com/antillas21/ajax-datatables-rails/issues/82

And we worked this out for the [v-0-4-0](https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0) branch (where we are working on feedback provided by other developers). You can give this branch a try in your project. Please be aware that this work-in-progress branch represents breaking changes from the current API, but they're already documented in the `README`.

**Comment by Exanimous** [comment]
I have been testing the v-0-4-0 branch, but despite changing the initialisers and implementing the view_columns method, the exact code that works with the standard branch breaks with the following error:

```
NoMethodError (undefined method `split' for nil:NilClass):
```

I will have to compare the queries and see what the exact issue is.  Note I am using mysql2.

**Comment by Exanimous** [comment]
A bit of an update on this, I think the reason that this fails is because datatables does not seem to like having two associations of the same model.  I have tried several workarounds (such as extracting the model into separate classes, but none of these seem to work, it's either one or the other).

It might be possible to manually override the default server side search functionality to search the tables separately depending on their foreign keys.

Note it works client-side because the browser is interacting directly through the active-record associations.

**Comment by antillas21** [comment]
Mhh... that is very weird, given we have tried this scenario before. The way to make it work was to be explicit as to how relationships are laid out in models, please refer to the [gist](https://gist.github.com/antillas21/4e22f87888ea9114025c) included in that issue to identify the applicable changes.

HInts:
- your relationships need to define an alias for each instance of the same model
- your `foreign_keys` must be named after this alias
- you may need to define `fake` active record models named after these aliases and explicitly use the same table of the original model

**Comment by Exanimous** [comment]
Interesting, I have implemented alias models but thinking about it I only have one foreign key name that matches the aliases, I will have a go at renaming the other one.  Thanks
