### ISSUE TITLE
Raw Data by different data ranges

### ISSUE THREAD

**Issue by maier-stefan** [jbox-web/ajax-datatables-rails#107]
**My raw data looks like this atm:**

```
def get_raw_records
    CampaignOfferPublisherReport.where('start_time >= ?', 7.day.ago.at_beginning_of_day).group(:campaign_offer_id, :publisher_id).select(:campaign_offer_id, :publisher_id, "sum(`campaign_offer_publisher_reports`.`clicks`) as clicks","sum(`campaign_offer_publisher_reports`.`cost`) as cost","sum(`campaign_offer_publisher_reports`.`revenue`) as revenue", "sum(`campaign_offer_publisher_reports`.`profit`) as profit", "sum(`campaign_offer_publisher_reports`.`conversions`) as conversions", "sum(`campaign_offer_publisher_reports`.`visits`) as visits" ,"MIN(`campaign_offer_publisher_reports`.`start_time`) as start_time", "MAX(`campaign_offer_publisher_reports`.`end_time`) as end_time").order('profit asc')
  end
```

*\* I want the user to choose between 1 day 3 days or 7 days ago... so where can i put the where statement?*\*

**Comment by antillas21** [comment]
@Stefflan00 here's what I would do

First, in the html view code, I would add a `<select>` tag with the options you need the user to choose (1 day, 3 days, 7 days ago).

Then I would ensure that changing the value on the select (and maybe clicking a "Search" button) results in a post/get request to the same rails route, where it appends the `start_time` param to the URL, something like: `http://localhost:3000/campaign-offer-publisher-report?start_time=3`.

Then in the controller I would pass in that param into the `format.json` handler, something like:

``` ruby
def index
  respond_to do |format|
    format.html {}
    format.json { render json: MyDatatableClass.new(view_context, { start_time: params[:start_time] }) }
  end
end
```

Then, as the documentation reads, I can use the hash passed in an `options` hash inside my datatable class.

``` ruby
def get_raw_records
  CampaingOfferPublisherReport.where(
    "start_time >= ?", options[:start_time]
  )
  .group(:campaign_offer_id, :publisher_id)
  .select(:campaign_offer_id, :publisher_id, "sum(`campaign_offer_publisher_reports`.`clicks`) as clicks","sum(`campaign_offer_publisher_reports`.`cost`) as cost","sum(`campaign_offer_publisher_reports`.`revenue`) as revenue", "sum(`campaign_offer_publisher_reports`.`profit`) as profit", "sum(`campaign_offer_publisher_reports`.`conversions`) as conversions", "sum(`campaign_offer_publisher_reports`.`visits`) as visits" ,"MIN(`campaign_offer_publisher_reports`.`start_time`) as start_time", "MAX(`campaign_offer_publisher_reports`.`end_time`) as end_time")
end
```

And also, will make sure to pass in (a default value for) that `start_time` param when drawing the html view (in the section where you build the `table` markup:

``` erb
<table class="table" id="report-table" data-source="<%= table_index_path(format: :json, start_time: 3) %>">
```

Please notice in the `get_raw_records` method, I omitted the `.order()` clause... as that should be left to dataTables to handle, both by providing an array of `sortable_columns` inside the datatable class, and maybe add a default sorting param in the JS code.
