### ISSUE TITLE
Is sorting and searching functionality working fine?

### ISSUE THREAD

**Issue by purezen** [jbox-web/ajax-datatables-rails#108]
Guys, I am using the gem in my project using Rails 4.1.8 and I have tried my best to set it up correctly.
But neither of searching, sorting and pagination functionality seems to be working right now.

It does show activity on the web page as well as fires SQL queries on doing any of the action, but shows the same data at the end.

**Comment by antillas21** [comment]
Can you share your implementation code?

**Comment by antillas21** [comment]
@purezen have you been able to solve your issue? if you need help, please let us know and don't forget to share your implementation code, so we can pinpoint where the problem is.

The gem is used currently in production in several apps (that I maintain) and everything is working without hitches.

**Comment by shpytalenko** [comment]
i have the same issue

**Comment by antillas21** [comment]
@shpytalenko could you share your implementation code along with rails and gem version, so I can help you debug it?

As I mentioned in my previous comment, I have it all working fine in several production apps, as well as other users.

**Comment by shpytalenko** [comment]
https://github.com/nguyentamvinhlong/ajax-rails-datatables-example

**Comment by shpytalenko** [comment]
```
class CompanyDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::Kaminari
  def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= ['Company.company_name', 'Company.date_added']
  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= ['Company.company_name']
  end

  private

  def data
    records.map do |record|
      [
        record.company_name,
        record.date_added,
        record.source,
        record.date_founded,
        record.linkedin_profile,
        record.funding_amount,
        record.funding_amount,
        #record.latest_founding,
        record.updated_at 
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
      ]
    end
  end


  def get_raw_records
    Company.all
  end


  # ==== Insert 'presenter'-like methods below if necessary
end


class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  has_scope :appannie,  :type => :boolean
  has_scope :by_source

def index
   respond_to do |format|
      format.html
      format.json { render json: CompanyDatatable.new(view_context) }
    end
end

$ ->
  $('#companies-table').dataTable
    processing: true
    serverSide: true
    ajaxSource: $('#companies-table').data('source')
    pagingType: 'full_numbers'

   <table class="" id="companies-table"  data-source="<%= companies_path(format: :json) %>">
  <thead>
    <tr>
      <th> id</th>
      <th style="width:20%;"><%= model_class.human_attribute_name(:company_name) %></th>
      <th> Date Added </th>
      <th> Founded </th>
      <th>Employees Linkedin</th>
      <th>Funding amount</th>
      <th>Latest funding</th>
      <th> Last Update </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  </table>  

```

gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'ajax-datatables-rails', git: 'git://github.com/antillas21/ajax-datatables-rails.git', branch: 'master'

here is my code

**Comment by antillas21** [comment]
@shpytalenko I can suggest the following:

Approach 1:
- update to the gem `0.3.0` version (your project is using version `0.1.2` as seen here: https://github.com/nguyentamvinhlong/ajax-rails-datatables-example/blob/master/Gemfile#L46)
- replace the `AjaxDatatablesRails::Extensions::Kaminari` extension in favor of the `AjaxDatatablesRails::Extensions::SimplePaginator` extension
- notice that as you're using `mysql` as your db engine (as seen here: https://github.com/nguyentamvinhlong/ajax-rails-datatables-example/blob/master/Gemfile#L7), you will need to add a configuration initializer as described here: https://github.com/antillas21/ajax-datatables-rails#configuration-initializer

Approach 2 (better):
- declare in your Gemfile that you want to use the `v-0-4-0` branch of this repo, like this:

``` ruby
gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'v-0-4-0'
```
- forget about using any paginator extensions (they're deprecated and no longer exist)
- notice that as you're using `mysql` as your db engine (as seen here: https://github.com/nguyentamvinhlong/ajax-rails-datatables-example/blob/master/Gemfile#L7), you will need to add a configuration initializer as described here: https://github.com/antillas21/ajax-datatables-rails#configuration-initializer
- follow the instructions of that branch `README` file, as the general API changed (https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0#customize-the-generated-datatables-class).

**Comment by antillas21** [comment]
Please let me know how it goes, and if I can help any further.

**Comment by shpytalenko** [comment]
i added to index.html.erb 

<script>
jQuery(document).ready(function() {
  $('#companies-table').dataTable({
    "processing": true,
    "serverSide": true,
    "ajax": $('#companies-table').data('source'),
    // optional, if you want full pagination controls.
    // Check dataTables documentation to learn more about
    // available options.
  });
});
</script>

 instead of coffee and got it working now
anyway thanks for help a lot, man! awesome tool!

**Comment by antillas21** [comment]
You're welcome. Glad it is sorted out now. I would like to encourage you to use the `v-0-4-0` branch, as we feel is a more polished API overall.

**Comment by shpytalenko** [comment]
I am using v-0-4-0 branch

**Comment by antillas21** [comment]
Excellent! :thumbsup:
