### ISSUE TITLE
How to displaying entries by using joins

### ISSUE THREAD

**Issue by maier-stefan** [jbox-web/ajax-datatables-rails#112]
How can i display number of entries by using joins within the datable model.

_Query:_

```
def get_raw_records
    start_time = "'#{Date.strptime(options[:start_time], "%m/%d/%Y")}'"
    end_time = "'#{Date.strptime(options[:end_time], "%m/%d/%Y")}'"
    CampaignOffer.joins("LEFT JOIN campaign_offer_reports ON campaign_offers.id = campaign_offer_reports.campaign_offer_id AND campaign_offer_reports.end_time <= #{end_time} AND campaign_offer_reports.start_time >= #{start_time}")
      .select( "campaign_offers.*","sum(campaign_offer_reports.profit) as profit","sum(campaign_offer_reports.revenue) as revenue","sum(campaign_offer_reports.cost) as cost", "sum(campaign_offer_reports.visits) as visits","sum(campaign_offer_reports.clicks) as clicks","sum(campaign_offer_reports.conversions) as conversions", "MIN(`campaign_offer_reports`.`start_time`) as start_time", "MAX(`campaign_offer_reports`.`end_time`) as end_time")
      .group(:campaign_offer_id)
  end
```

```
Showing 0 to 0 of 0 entries (filtered from NaN total entries)
```

**Comment by antillas21** [comment]
@Stefflan00 can you share sample classes and relationships, so we can try to reproduce this issue and help you drive this out?

**Comment by maier-stefan** [comment]
@antillas21 https://gist.github.com/Stefflan00/197e3b653e198f0c3bcb
That is my datatable class.

**Comment by mrpotts** [comment]
Same problem here. The returned values for iTotalRecords and iTotalDisplayRecords are hashes instead of integer. It seems the bug is triggered by the .group() option.

**Comment by maier-stefan** [comment]
@mrpotts did you find a solution yet?

**Comment by mrpotts** [comment]
Yes, I found it. The problem is the way [ActiveRecord counts records](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count); on grouped query, it returns an hash of counts. So, in those cases, you'd have to sum the values. I've solved it by redeclaring `as_json` as a public method in my _datatable.rb file (note the `.inject` after `get_raw_records.count()`):

``` ruby
def as_json(options = {})
  {
    :sEcho => params[:sEcho].to_i,
    # added .inject(0){|a,(_,b)|a+b} to sum the hash values
    :iTotalRecords => get_raw_records.count.inject(0){|a,(_,b)|a+b},
    :iTotalDisplayRecords => filter_records(get_raw_records).count.inject(0){|a,(_,b)|a+b},
    :aaData => data
  }
end
```

**Comment by antillas21** [comment]
@mrpotts interesting... perhaps we could add a check (in the gem code) to help with this issue, something like this, perhaps:

``` ruby
def as_json(options = {})
  {
    :sEcho => params[:sEcho].to_i,
    :iTotalRecords => get_raw_records.count.inject(0){|a,(_,b)|a+b},
    :iTotalDisplayRecords => filtered_records_count,
    :aaData => data
  }
end

def filtered_records_count
  records_count = filter_records(get_raw_records).count
  return records_count.inject(0){|a,(_,b)|a+b} if records_count.is_a?(Hash)
  records_count
end
```

**Comment by mrpotts** [comment]
@antillas21 Yes, this is the solution. Hower the check should be applied to `:iTotalRecords` as well, so here's what I'd do (untested):

``` ruby
def as_json(options = {})
  {
    :sEcho => params[:sEcho].to_i,
    :iTotalRecords => records_count( get_raw_records ),
    :iTotalDisplayRecords => records_count( filter_records(get_raw_records) )
    :aaData => data
  }
end

def records_count( records )
  records_count = records.count
  return records_count.inject(0){|a,(_,b)|a+b} if records_count.is_a?(Hash)
  records_count
end
```

**Comment by maier-stefan** [comment]
@antillas21 @mrpotts 

if i look in the base code: 

```
def as_json(options = {})
      {
        :draw => params[:draw].to_i,
        :recordsTotal =>  get_raw_records.count(:all),
        :recordsFiltered => filter_records(get_raw_records).count(:all),
        :data => data
      }
    end
```

Why can't we just get the length of that array? 

```
def as_json(options = {})
      {
        :draw => params[:draw].to_i,
        :recordsTotal =>  get_raw_records.length,
        :recordsFiltered => filter_records(get_raw_records).length,
        :data => data
      }
    end
```

**Comment by mrpotts** [comment]
@Stefflan00 Yep, that works!

**Comment by ikaul** [comment]
Firstly, @Stefflan00 thank you for the elegant solution.

Just wanted to add that rather than modifying the as_json function, I achieved the same from adding the below code to the my_datatable.rb
 ```
  def records_total_count
    get_raw_records.length
  end

  def records_filtered_count
    filter_records(get_raw_records).length
  end
```

**Comment by fate83** [comment]
Hi! We had a similar issue in our application when using outer joins in our _get_raw_records_ method.

We solved it by using **distinct** instead of **group**.

See: https://stackoverflow.com/questions/31879150/group-by-and-count-using-activerecord

Hope that helps :)

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails#associated-and-nested-models
