### ISSUE TITLE
Search and sorting functionality not working

### ISSUE THREAD

**Issue by Da1amar** [jbox-web/ajax-datatables-rails#114]
Guys,

I am integrating ajax-datatables-rails gem into my application, and can not get it to work with search and sort, and pagination.

I looked at source code, and it seems the code in AjaxDatatablesRails::Base tries to get wrong parameters. For example:
      records = sort_records(records) if params[:order].present?
      records = filter_records(records) if params[:search].present?
      records = paginate_records(records) unless params[:length].present? && params[:length] == '-1'

And my parameters are (from server log):
Parameters: {"sEcho"=>"8", "iColumns"=>"3", "sColumns"=>",,", "iDisplayStart"=>"10", "iDisplayLength"=>"10", "mDataProp_0"=>"0", "sSearch_0"=>"", "bRegex_0"=>"false", "bSearchable_0"=>"true", "bSortable_0"=>"true", "mDataProp_1"=>"1", "sSearch_1"=>"", "bRegex_1"=>"false", "bSearchable_1"=>"true", "bSortable_1"=>"true", "mDataProp_2"=>"2", "sSearch_2"=>"", "bRegex_2"=>"false", "bSearchable_2"=>"true", "bSortable_2"=>"true", "sSearch"=>"", "bRegex"=>"false", "iSortCol_0"=>"0", "sSortDir_0"=>"asc", "iSortingCols"=>"1", "_"=>"1439462087660"}

So instead of params[:length] it should be params[:iDisplayLength], instead of params[:search] should be params[:sSearch].

It looks like I use some wrong version of datatable. But I just use the latest.
GemFile:
gem 'will_paginate'
gem 'jquery-datatables-rails'
gem 'ajax-datatables-rails'

Bundler log:
Using jquery-datatables-rails 3.3.0
Using ajax-datatables-rails 0.3.1

What am I doing wrong?

**Comment by antillas21** [comment]
you're not doing anything wrong... you have the _legacy_ version of the
jquery datatables plugin.

You can notice a message in our README file about versions.

The current version of this gem is to be used with jquey datatables version
1.10 and you have version 1.9 in your project.

**Comment by antillas21** [comment]
@Da1amar Take a look at the [README: Versions](https://github.com/antillas21/ajax-datatables-rails#versions) section.

From your Bundler log, it should be using `jQuery.dataTables` ver. 1.10, if it's not, maybe it's due to a config setting. AFAIK, dataTables 1.10 supports both params syntax, but our gem doesn't, and that's why you should be careful on what version you're using.

**Comment by Da1amar** [comment]
@antillas21 

Thank you for prompt answer.

Yeap, I changed to 'legacy' branch of ajax-datatables-rails gem, and everything works fine.
I just wonder why my jquery-datatables-rails (most recent) provides me legacy datatables.

BTW. I checked /assets/dataTables/jquery.dataTables.self-770bf6f5f52c93784a25c3c866719f24d091a3f864c36850a7d338b58bbed52c.js?body=1 (this is from generated HTML source code). And it starts with:
/*! DataTables 1.10.6
  ©2008-2014 SpryMedia Ltd - datatables.net/license

So it seems the DataTables are the most recent ones, but they for some reason use old parameter names when communicating to the server.
Maybe there is some config option? Or maybe initialization? I do it the following way:
jQuery ->
  $('#users').DataTable
    sPaginationType: "full_numbers"
    bJQueryUI: true
    bProcessing: true
    bServerSide: true
    sAjaxSource: $('#users').data('source')

**Comment by maartendra** [comment]
@Da1amar You should use the new DataTables syntax (camelCase notation instead of Hungarian). So in your case:

``` coffee
jQuery ->
  $('#users').DataTable # This was okay already
    pagingType: "full_numbers"
    jQueryUI: true
    processing: true
    serverSide: true
    ajax: $('#users').data('source')
```

If you do so DataTables will provide you with the new parameters when querying. For all other parameters you can take a look here: http://www.datatables.net/upgrade/1.10-convert.

**Comment by antillas21** [comment]
:+1: on @maartendraijer comments... it appears that using the new `dataTables` syntax in your JS, is the way to go. Using the legacy syntax (hungarian notation) will trigger legacy behavior.

**Comment by rtplvaibhav** [comment]
Hello Antialla,

I need to have a increment number in the first column of datatable and using the following code. I need first column nor to be searchable neither sortable. How can i achieve this? Below is my code 

class UserDatatable < AjaxDatatablesRails::Base
include AjaxDatatablesRails::Extensions::Kaminari

```
def sortable_columns
  @sortable_columns ||= ['User.first_name', 'User.last_name', 'User.email']
end

def searchable_columns
  @searchable_columns ||= ['User.first_name', 'User.last_name', 'User.email']
end

private
def data
    outer = []
    records.each_with_index do |record, idx|
        outer << [
                     idx + 1,
                     record.first_name,
                     record.last_name,
                     record.email
                ]
    end
    outer
end

def get_raw_records
    User.all
end

# ==== Insert 'presenter'-like methods below if necessary
```

end

**Comment by aldrienht** [comment]
Hi there!

**Please help!**

why i'm getting this error when I tried to set more than 9 columns in table (i got it setting 10 columns)
    <H1>Request-URI Too Large</H1>
    WEBrick::HTTPStatus::RequestURITooLarge

<H1>Also, sorting and searching is not working too (no error logs in console). </H1>

**I saw the parameters in query logs, but it's not updating the table records.**

**Gemfile:** (I tried different version)
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git', branch: 'master'
*gem 'ajax-datatables-rails', git: 'git://github.com/antillas21/ajax-datatables-rails.git', branch: 'legacy'
*gem 'ajax-datatables-rails'
*gem 'ajax-datatables-rails', '0.1.2'
gem "kaminari"

**Controller:**
I used cancan gem
load_and_authorize_resource

def index
    respond_to do |format|
      applicants = filter_not_to_be_deleted(@applicants).includes(:country, :religion)
      format.html
      format.json { render json: ApplicantsDatatable.new(view_context, records: applicants) }
    end
  end

**applicants_datatable.rb:**
`class ApplicantsDatatable < AjaxDatatablesRails::Base  
  include AjaxDatatablesRails::Extensions::Kaminari

  def sortable_columns
    @sortable_columns ||= [
      'applicants.name', 
      'applicants.project_id', 
      'applicants.gender',
      'applicants.birth_date',
      'applicants.country.en_name',
      'applicants.marital_status',
      'applicants.last_academic'
    ]
  end

  def searchable_columns
    @searchable_columns ||= [
      'applicants.name', 
      'applicants.project_id', 
      'applicants.gender',
      'applicants.birth_date',
      'applicants.country.en_name',
      'applicants.marital_status',
      'applicants.last_academic'
    ]  
  end

  private

  def data
    records.map do |applicant|
      [ 
        "<image src='#{applicant.profile.url(:thumb)}' class='listing_image' />",
        applicant.name,
        applicant.project.title,
        applicant.gender,
        applicant.birth_date,
        applicant.age,
        applicant.country.en_name,
        applicant.marital_status,
        applicant.last_academic
      ]
    end
  end

  def get_raw_records
    options[:records]
  end
end`

**applicants/index.html.erb:**

<#table id="applicants-table" class="table table-striped table-bordered table-hover" data-source="<%= applicants_path(format: :json) %>">
........

**Comment by ajahongir** [comment]
try to use gem 'thin' instread of 'webreak' as application server

**Comment by jmaggesi** [comment]
@aldrienht The problem arise because the web server can't handle request URI bigger than the maximum size defined in the configuration.

A possible solution could be to use a POST request in the definition of the DataTables. Something like this:

```
$(document).ready(function() {
    $('#example').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "URL_TO_SERVER",
            "type": "POST"
        },
        "columns": [
            { "data": "first_name" },
            { "data": "last_name" },
            { "data": "position" },
            { "data": "office" },
            { "data": "start_date" },
            { "data": "salary" }
        ]
    } );
} );

```

As pointed out in the doc of the DataTables library. I don't know if this could be a problem for the gem.

**Comment by n-rodriguez** [comment]
> A possible solution could be to use a POST request in the definition of the DataTables

This is the **only** solution.
