### ISSUE TITLE
Add documentation/generator for creating indices.

### ISSUE THREAD

**Issue by panmari** [jbox-web/ajax-datatables-rails#115]
Has anyone else the problem that the `... ILIKE '%foo%' or ... ILIKE '%foo%' or .. ILIKE '%foo%'` queries are rather slow? It would be great to have some documentation or possibly even a generator for creating indices to speed up these. What I found so far for postgres is the [gin/gist index type](http://www.postgresql.org/docs/current/interactive/pgtrgm.html). For my application, I then wrote something along these lines as migration:

```
def change
    enable_extension :pg_trgm

    TEXT_SEARCH_ATTRIBUTES.each do |attr|
      reversible do |dir|
        dir.up do
          execute "CREATE INDEX runners_#{attr}_gin ON runners USING gin(#{attr} gin_trgm_ops)"
        end
        dir.down do
          remove_index :runners, name: "runners_#{attr}_gin"
        end
      end
    end
end
```

Inspired by a post from [dba.stackexchange](http://dba.stackexchange.com/questions/2195/how-is-like-implemented/10856#10856). This took down the time necessary for a search on 3 columns from 120 ms to 3 ms in my case.

**Comment by antillas21** [comment]
@panmari is this a suggestion on how to improve db schema? If so.... could you open a PR updating the `README`? or maybe creating a new page in the wiki?

**Comment by panmari** [comment]
Actually, it was intended as a question but then I found the answer myself along the way ;) What would you prefer? Wiki page, generator or just entry in README?

**Comment by antillas21** [comment]
I would prefer a wiki page, given that:
- database performance tips are outside the scope of the datatables plugin and helper implementation in ruby (as this gem).
- database performance tips should be presented as such, a tip.

**Comment by panmari** [comment]
Added a part 3 to wiki - speeding up search by creating indices.

**Comment by antillas21** [comment]
:+1: Thanks! Just went in and edited the code highlight section to be easily readable.

Thanks for this contribution!

**Comment by panmari** [comment]
Great, thanks!
