### ISSUE TITLE
In javascript console: Uncaught TypeError: Cannot set property 'data' of null

### ISSUE THREAD

**Issue by panmari** [jbox-web/ajax-datatables-rails#117]
For every ajax request I get the following exception in the javascript console:

```
Uncaught TypeError: Cannot set property 'data' of null_fnBuildAjax @ jquery.dataTables.self-a9908e5a65de4eeb0522babd326c527638c2ff12f0b4c3f61deb76b1dc27e25d.js?
body=1:2527_fnAjaxUpdate @ jquery.dataTables.self-a9908e5a65de4eeb0522babd326c527638c2ff12f0b4c3f61deb76b1dc27e25d.js?
body=1:2544_fnDraw @ jquery.dataTables.self-a9908e5a65de4eeb0522babd326c527638c2ff12f0b4c3f61deb76b1dc27e25d.js?
body=1:2008searchFn @ jquery.dataTables.self-a9908e5a65de4eeb0522babd326c527638c2ff12f0b4c3f61deb76b1dc27e25d.js?
body=1:2786(anonymous function) @ jquery.dataTables.self-a9908e5a65de4eeb0522babd326c527638c2ff12f0b4c3f61deb76b1dc27e25d.js?
body=1:4307jQuery.event.dispatch @ jquery.self-d03a5518f45df77341bdbe6201ba3bfa547ebba8ed64f0ea56bfa5f96ea7c074.js?
body=1:4666jQuery.event.add.elemData.handle @ jquery.self-d03a5518f45df77341bdbe6201ba3bfa547ebba8ed64f0ea56bfa5f96ea7c074.js?body=1:4334
```

thrown in the line `ajax.data = ajaxData;`. I'm using DataTables 1.10.7. The datatable is updating as excpected nonetheless. Anyone else with this issue?

**Comment by antillas21** [comment]
No, I haven't seen this error.

From what it looks like it may be related to your `JS` implementation. Have you tried the jQuery dataTables plugin forum?

**Comment by panmari** [comment]
Got it, was a mistake on my side. I set the `ajax` attribute wrong (null), which somehow still worked but made this error appear.

**Comment by chevinbrown** [comment]
I am having this same problem, but having trouble diagnosing. Table works fine, but I get the error mentioned above.

**Comment by arielcxl** [comment]
In my case I was having the same issue, then I noticed I was trying to reload another data table I haven't created yet as part of an event the first one triggered. So it looks related to the first data table.

**Comment by ajahongir** [comment]
@arielcxl 
can you shor your js code, your ajax request and response, please?

**Comment by arielcxl** [comment]
That’s the point, a request is never made because the options (which includes the ajax url) are never passed to the data-table. Most likely I was calling ajax reload (and implicitly creating the data-table), so no ajax url to call.

**Comment by bwilsonkey** [comment]
In my case, this was caused by a very simple typo. 

Define your data like this:

` "ajax:" {url: "{{ route('datatables') }}",`

and the table will render but you will get the error.

Define your data like this: 

`"ajax": {url: "{{ route('datatables') }}",`

and the table will render and you will not get the error.
