### ISSUE TITLE
Column search doesn't work with multiple models/tables.

### ISSUE THREAD

**Issue by mrudult** [jbox-web/ajax-datatables-rails#120]
While searching in columns from multiple tables, the SQL generated doesn't join/include the required model.
The SQL generated is something like this:

```
 Unknown column 'addresses.city in 'where clause': SELECT COUNT(*) FROM `users` WHERE (((CAST(`addresses`.`city` AS CHAR) LIKE '%nyc%' OR CAST(`users`.`name` AS CHAR) LIKE '%nyc%') OR CAST(`users`.`email` AS CHAR) LIKE '%nyc%'))):
```

I'm having `user has_many addresses` defined in model

**Comment by antillas21** [comment]
@mrudult what is the code inside your `get_raw_records` method?

I would do something like:

``` ruby
def get_raw_records
  User.joins(:addresses)
end
```

to get all `users` and have that missing join, given that:

``` ruby
def get_raw_records
  User.all
end
```

won't work as it's missing the entry point into the `has_many :addresses` relationship.

**Comment by mrudult** [comment]
Okay. I had `includes` in my AR query but I wasn't using `joins`. I thought `includes` and `joins` together is bad idea. Anyways, thanks for the fix! :smiley:

**Comment by antillas21** [comment]
@mrudult it's not a _good idea, bad idea_ issue... it's merely a decision on how to expose database tables to be accessed for querying. Example:

``` ruby
User.includes(:addresses).references(:addresses)
# lazy-loads :addresses relationship while allowing the query to perform `WHERE` statements

User.joins(:addresses)
# loads selected properties of addresses and allows the query to perform `WHERE` statements
```

even when both cases will allow you to search columns in the related `:addresses` table, one will always perform more efficiently at the db level. Which of them does, is just a matter of checking the logs :wink:

**Comment by ajahongir** [comment]
@mrudult you have to use something like this syntax:

``` ruby
def data
  records.map do |user|
    id: user.id,
    ...
    ...
    city: user.adress_city
  end
end
```

``` ruby
def get_raw_records
  User.select('users.*, adresses.city AS address_city').joins(:addresses)
end
```
