### ISSUE TITLE
How can I export my datatable to .csv?

### ISSUE THREAD

**Issue by abhinavmsra** [jbox-web/ajax-datatables-rails#121]
Does the gem support `export to csv` feature?  

I have complex filtering in my datatable and I need to export the filtered data to csv. I was looking at the `TableTools` as well. But could not get it to work?

Anyways what would be the better approach, use the datatable extensions or send a .csv request to server and responding accordingly?

**Comment by antillas21** [comment]
Hi @abhinavmsra , no, this gem does not support export to csv, as that is handled by the `jQuery.dataTables` plugin through the `TableTools` extension.

I don't have a suggestion to what the best approach could be. AFAIK if you are able to filter and display records, using the `TableTools` extension should just work when it comes to exporting the resulting data set into `csv, pdf, xls`.

I'm really sorry, if nothing of this helps you.

**Comment by kingp0dd** [comment]
@antillas21 I know your gem works with jquery-datatables-rails gem. If jquery-datatables-rails supports TableTools, it should also work with ajax-datatables-rails, right?
Thank you!

**Comment by fionajvoss** [comment]
Can anybody elaborate on the meaning of "this gem does not support export to csv"? Can I still use the TableTools extension if I'm using this gem, or does it break the extension? @antillas21, are you still involved with maintaining this gem?
