### ISSUE TITLE
Broken Tests

### ISSUE THREAD

**Issue by sallustfire** [jbox-web/ajax-datatables-rails#124]
Hi, I forked the repo to look at adding some functionality around filtering and sorting column that are rails enums.  However, it appears that someone made some changes in e502fda (which is quite old) that completely circumvents two of the tests.

In aab56a9 on lines 232 and 246, someone added `records.where`.  The only expectation in these tests are `expect(records).to receive(:where)`, which is now trivially true since `records.where` is explicitly called.  Both of those tests fail when the offending `records.where` are removed.

Figured that someone might want to be aware of this.

**Comment by antillas21** [comment]
Hi @sallustfire , thanks for reporting this... and also, an apology for getting back to you this late.

You are more than welcome to improve specs, if you'd be interested in doing so :smile:

**Comment by sallustfire** [comment]
@antillas21 No worries.  I'm adding some functionality in my fork.  I'll clean some of this up in the process and send it back your way for review in a week or two.

**Comment by n-rodriguez** [comment]
Seems to be fixed now :)
