### ISSUE TITLE
how to add an URL pointing to 'show' or 'edit' actions

### ISSUE THREAD

**Issue by miguelfg** [jbox-web/ajax-datatables-rails#125]
Hi, I'm trying to add as a record column the url pointing to the show or edit page of the record/object in the table row, and I don't find the way to do it.

I've tried with 'link_to' and 'view_context.link_to' methods in def data method at xxx_datatable.rb, but those methods are not accessible in that file.

What would be the way to do it?

Great gem BTW

**Comment by ajahongir** [comment]
@miguelfg 
try something like this: `view.admin_airlines_path`

**Comment by RodMachado** [comment]
@miguelfg 

Add `def_delegators :@view, :link_to, :your_resource_path` to your datatables class. That way you can call `link_to`. You need to add your resource path as well since the class doesn't have access to Rails url helpers.

My data method looks like this

```
   def_delegators :@view, :link_to, :finance_bank_account_path

    def data
      records.map do |record|
        [
          link_to(record.id, finance_bank_account_path(record)),
          link_to(record.name, finance_bank_account_path(record))
        ]
      end
    end
```

Cheers!

**Comment by miguelfg** [comment]
@ajahongir i don't get really where your code should go
@RodMachado AWESOME, worked smoothly, thanks!

**Comment by antillas21** [comment]
Late to the party, but yes, @RodMachado is right, that is the way to go, as is documented in the [Using view helpers](https://github.com/antillas21/ajax-datatables-rails#using-view-helpers) section of the gem's README

**Comment by an-nasir** [comment]
Hi, how can we add multiple links under one <td> say 
I have last column named as **Actions** and I want all three (Show, Edit, Delete and Some Other ) links to be placed under **Actions** TD.

Below is my `def data` mapping method

`DT_RowId:   record.id,`
`id:         record.id,`
 `mr_number: record.mr_number,`
  `number:  record.number,`
` name:      record.name,`
`cnic:        record.cnic,`
 `actions: link_to("Visits", user_visits_url(record), class: "btn teal btn-reg")`

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails#using-view-helpers
