### ISSUE TITLE
AR Enum Support

### ISSUE THREAD

**Issue by sallustfire** [jbox-web/ajax-datatables-rails#126]
The enum columns introduced by active record 4.1 don't work.  The labels are only in the rails application and not in the database, hence filtering and sorting on these columns does not work as expected.  The proposed solution is to handle enum columns separately and perform the mapping between labels and the ints prior to generating the SQL queries.

**Comment by thalesmiguel** [comment]
Hello.
Have we made progress in this?
I'm having the same problem as @sallustfire.
How can I use an ENUM field for search?

Thanks in advance.
