### ISSUE TITLE
Sorting functionality not working for colReorder

### ISSUE THREAD

**Issue by gillisd** [jbox-web/ajax-datatables-rails#129]
I have colReorder set to true in my datatable. However, when I try to sort a column after reordering, the server pulls data using the original column order. Has anyone found a way to get around this?

**Comment by ajahongir** [comment]
@gillisd I am not sure but I thing latest version should work. on v.0.3 sording columns defines as just an Array. on v.0.4 you define as hash. 
sample project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to
