### ISSUE TITLE
How to populate two datatables from the same controller

### ISSUE THREAD

**Issue by slead** [jbox-web/ajax-datatables-rails#130]
I've got a model which has a Status attribute, and I'd like to have two datatables, one showing "Published" and the other showing "Draft" entries.

Is it possible to pass a parameter through to the controller's index method, so I can render the json to the appropriate DataTable?

eg:

```
if params["published"]
  format.json { render json: PublishedVideoDatatable.new(view_context) }
else
  format.json { render json: DraftVideoDatatable.new(view_context) }
end

I can't see how to pass through the parameter on the HTML page: `#tblVideos{:data => {:source => videos_path(format: :json)}}`

Thanks,
Steve

```

**Comment by slead** [comment]
Nevermind, I resolved this using:

```
#tblVideos{:data => {:source => videos_path(format: :json, status: "published")}}

if params[:status] == "published"
  format.json { render json: VideoDatatable.new(view_context) }
elsif params[:status] == "draft"
  format.json { render json: DraftVideoDatatable.new(view_context) }
end
```

**Comment by antillas21** [comment]
Hi @slead ,

While what you've done works, you can simplify it with:

``` ruby
format.json { render json: VideoDatatable.new(view_context, status: params[:status] }
```

then, inside your `VideoDatatable` class, you can have access to the `status` in the `options` hash, example:

``` ruby
def get_raw_data
   Video.where(status: options[:status])
end
```

You can reference [this section in the README](https://github.com/antillas21/ajax-datatables-rails#options) to learn more about the options hash.

**Comment by ajahongir** [comment]
or juts using `params`

``` ruby
format.json { render json: VideoDatatable.new(view_context) }
```

``` ruby
def get_raw_data
   Video.where(status: params[:status])
end
```
