### ISSUE TITLE
Search/sort associations for dummies?

### ISSUE THREAD

**Issue by llermaly** [jbox-web/ajax-datatables-rails#133]
Hello, first of all , thank you very much @antillas21 and contributors for this fantastic gem, I started with some basic datatables but then I added relations to my tables and all started to fail. 

I read over and over again issues related and documentation, but I cant make my association models search/sort work properly, so I hope you can give me a hand here.

I will try to be short and precise, I have an Order model that holds a School and OrderStatuses.

My code look like this

```
class OrderDatatable < AjaxDatatablesRails::Base

  def_delegators :@view, :link_to, :h, :order_path, :edit_order_path, :order_proccesses_path

  def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= %w(Order.number School.nombre Commune.name Region.id Order.year Order.paymethod Order.contract StatusType.nombre)
  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= %w(Order.number School.nombre Commune.name Region.id Order.year Order.paymethod Order.contract StatusType.nombre)
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
        record.try(:number), 
        record.school.try(:nombre),
        record.school.commune.try(:name),
        record.school.commune.try(:region).try(:roman),
        record.try(:year),
        record.try(:paymethod), 
        record.try(:contract),
        record.order_statuses.last.status_type.try(:nombre),
        edit_and_delete_buttons(record)
        ]
    end
  end

  def get_raw_records
    # insert query here
    Order.includes({:school => {:commune => :region}},{:order_statuses => :status_type}).distinct
  end
```

Sort works OK with all columns except this 

```
record.order_statuses.last.status_type.try(:nombre),
```

It seems like sorts inside all statuses of each order instead of only the lasts.

Search is not working (ofcourse, because if any of the columns fails searchs doesnt work).

I'm using yadcf with datatables and filters only works with columns directly related to Order, so most probably get_raw_records line is bad. This is very frustrating and I feel shame about asking you with all the documentation about , but I just cant solve this.

THANKS AGAIN

**Comment by antillas21** [comment]
Hi @llermaly ... you can try two things here:

``` ruby
# if using .includes
def get_raw_records
  Order.includes(
    :school => { :commune => :region }, :order_statuses => :status_type
  )
  .references(
    :school => { :commune => :region }, :order_statuses => :status_type
  ).distinct
end

# alternatively, you can use .joins
def get_raw_records
  Order.joins(
    :school => { :commune => :region }, :order_statuses => :status_type
  ).distinct
end
```

the trick is... if using `.includes`, you need to add the `.references` snippet to tell `ActiveRecord` how to add model relationships to perform any action different from retrieving data, like sorting or filtering :wink:  ... but if you use `.joins`, then you don't need to add anything else as the join keeps the reference to perform these other actions.

There's some documentation in the `README` about this, here: https://github.com/antillas21/ajax-datatables-rails#associated-and-nested-models (look at comment 3 in the _Some comments for the above code_ section).

Hope this helps :smile:

**Comment by llermaly** [comment]
Thanks!! ,  worked with includes, the only thing is that the weird behavior of         record.order_statuses.last.status_type.try(:nombre),column persists , when I press the column head to sort,  looks like ignores the ".last" statement and shows another statuses instead. What can I do to not change the row text when I sort?

I read the link you sent me but I couldn't apply your example to my case successfully (too complex for me :( )

BTW:  just noticed you are from Mexico (maybe just living there?) saludos desde Chile!!, mi hermano anda por allá. Prefiero mantener el inglés aunque me cueste escribirlo, así practico y queda entendible para los demás.

Regards

**Comment by antillas21** [comment]
Maybe the weird behavior is because you're retrieving and trying to sort on a single record?
`record.order_statuses.last.status_type.try(:nombre)` ... I think that call to `.last` along with `.try` may
be the root of your problems.

As a rule of thumb, I follow Yoda's advice on:

> Do, or do not... there is no try

Hope any of this makes any sense.

P.S. Gracias por los saludos. Sí, Mexicanito de nacimiento :)

**Comment by llermaly** [comment]
Haha thanks,  im very confused .. I tried creating a method in my model to extract only the name of the last status and keeps looking inside all the statuses 

#model 
  def last_status
    self.order_statuses.last.status_type.nombre
  end

#datatable 
 record.last_status,

Probably theres something I dont know but in my mind that method extract a string and its not possible to get to the other statuses :/ 

maybe do I need to set a limit in the get_raw_record ? Tried but throws error of method in a symbol
