### ISSUE TITLE
Need Customization Help

### ISSUE THREAD

**Issue by rtplvaibhav** [jbox-web/ajax-datatables-rails#134]
Hi, 

This is a great extension but I need few help over this.

1) Need to define custom table for datatable class like shown below, but I am not getting it working.

class UserListingDatatable < AjaxDatatablesRails::Base
    include AjaxDatatablesRails::Extensions::Kaminari
    self.table_name = "users";
end

2) Can i use Users.find_by_sql(sql) to get my records because i am finding hard time to implement joins using the syntax mentioned in readme plus i need a concat of first_name and last_name as full name also. My sql for this is 
SELECT concat(u.first_name, ' ', u.last_name) as full_name, u.email, s.name FROM users AS u JOIN zips AS z ON z.id = u.zip_id JOIN neighbour AS n ON n.id = z.neighbour_id JOIN states as s ON n.state_id = s.id

3) Can i implement individual column search any how ?

4) I also need a incremental Serial Number starting from 1 in first column which is neither searchable nor sortable. How can i achieve this.

5) How can I decide the width of each column of table manually.

**Comment by ajahongir** [comment]
look at this sample project https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by rtplvaibhav** [comment]
Yes, I have seen this example but I am not able to get this working in my case. I did not understand the concept there

**Comment by ajahongir** [comment]
@rtplvaibhav  can you put your datafile here and what wersion of gem are you using right now?

**Comment by ajahongir** [comment]
> 2) Can i use Users.find_by_sql(sql) to get my records because i am finding hard time to implement joins using the syntax mentioned in readme plus i need a concat of first_name and last_name as full name also. My sql for this is 
> SELECT concat(u.first_name, ' ', u.last_name) as full_name, u.email, s.name FROM users AS u JOIN zips AS z ON z.id = u.zip_id JOIN neighbour AS n ON n.id = z.neighbour_id JOIN states as s ON n.state_id = s.id

you can join your table as:
`User.joins({ zips: { neighbour: :states} })`

**Comment by rtplvaibhav** [comment]
class UserListingDatatable < AjaxDatatablesRails::Base
  # uncomment the appropriate paginator module,
  # depending on gems available in your project.
    include AjaxDatatablesRails::Extensions::Kaminari
  # include AjaxDatatablesRails::Extensions::WillPaginate
  # include AjaxDatatablesRails::Extensions::SimplePaginator

  self.table_name = "users";

  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= [
            'users.full_name',
            'users.email',
            'users.state'
        ]
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns ||= [
            'users.full_name',
            'users.email',
            'users.state'
        ]
  end

  private

  def data
    records.map do |user_info|
      [
        user_info.full_name,
        user_info.email,
        user_info.state
      ]
    end
  end

  def get_raw_records
        User.find_by_sql("SELECT concat(u.first_name, ' ', u.last_name) as full_name, u.email, s.name FROM users AS u JOIN zips AS z ON z.id = u.zip_id JOIN neighbour AS n ON n.id = z.neighbour_id JOIN states as s ON n.state_id = s.id");
  end

  # ==== Insert 'presenter'-like methods below if necessary
end

**Comment by rtplvaibhav** [comment]
This is the error right now, which i think is not related to sql but something else

ActiveRecord::RecordNotFound at /users/user_listing.json
Couldn't find User with 'id'=user_listing [WHERE "users"."deleted_at" IS NULL]

**Comment by ajahongir** [comment]
> ActiveRecord::RecordNotFound at /users/user_listing.json
> Couldn't find User with 'id'=user_listing [WHERE "users"."deleted_at" IS NULL]

I gues you have not define controller method in route.rb file

you shoud to have something like this:

``` ruby
resources :users do
  get :user_listing, on: :collection
end
```

**Comment by rtplvaibhav** [comment]
Yes i got that resolved but what about,

Incremental serial number in first column of table that is nor searchable nor sortable
First name and last name as full name from query only

**Comment by ajahongir** [comment]
I advice you to user latest version v4. and build your datafile as like this:

``` ruby
class UserListingDatatable < AjaxDatatablesRails::Base

  def view_columns
    @view_columns ||= {
      first_name: { source: "User.first_name" },
      last_name: { source: "User.last_name" },
      email: { source: "User.email" },
      name: { source: "Source.name" }
    }
  end

  private
  def data
    index = 0
    records.map do |user|
      index += 1
      {
        index: index,
        firt_name: user.firt_name,
        last_name: user.last_name,
        email: user.email,
        name: user.name,
      }
    end
  end

  def get_raw_records
    User.joins({ zips: { neighbour: :states} })
  end

end
```

**Comment by rtplvaibhav** [comment]
I am getting this error now "undefined method `name' for #<User:0x8e4dac8>", there is no direct name field in database, I need to get it by concating first_name and last_name 

class UserListingDatatable < AjaxDatatablesRails::Base
    #include AjaxDatatablesRails::Extensions::Kaminari
	
	def view_columns
		@view_columns ||= 
		{
		  first_name: { source: "User.first_name" },
		  last_name: { source: "User.last_name" },
		  email: { source: "User.email" },
		  name: { source: "Source.name" }
		}
	end

	private
		def data
			index = 0
			records.map do |user|
			index += 1
			{
				index: index,
				first_name: user.first_name,
				last_name: user.last_name,
				email: user.email,
				name: user.name,
			}
		end
	end

	def get_raw_records
		User.joins({ zip: { neighborhood: :state} })
	end

end

**Comment by rtplvaibhav** [comment]
This is my updated code and it works fine for initial page load but does not works on searching and sorting

class UserListingDatatable < AjaxDatatablesRails::Base
    #include AjaxDatatablesRails::Extensions::Kaminari

```
def view_columns
    @view_columns ||= 
    {
        first_name: { source: "User.first_name", cond: :like },
        last_name: { source: "User.last_name", cond: :like },
        email: { source: "User.email", cond: :like },
        state: { source: "State.name", cond: :like },
        neighborhood: { source: "Neighborhood.name", cond: :like },
        zip: { source: "User.zip_id", cond: :like },
    }
end

private
    def data
        serial_no = 0
        records.map do |user|
        serial_no += 1
        {
            serial_no: serial_no,
            first_name: user.first_name,
            last_name: user.last_name,
            email: user.email,
            state: user.state.name,
            city: user.neighborhood.name,
            zip: user.zip_id,
        }
    end
end

def get_raw_records
    #User.joins({ zip: { neighborhood: :state} })
    abort(User.joins({ zip: { neighborhood: :state} }).to_sql.to_s);
end
```

end
