### ISSUE TITLE
Search generates AND condition

### ISSUE THREAD

**Issue by rtplvaibhav** [jbox-web/ajax-datatables-rails#135]
I have installed the datatable and it is working fine but it generates unwanted AND condition while searching which almost always passes a null result. Below is the query generated

SELECT  "users".\* FROM "users" 
INNER JOIN "zips" ON "zips"."id" = "users"."zip_id" 
INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "zips"."neighborhood_id" 
INNER JOIN "states" ON "states"."id" = "neighborhoods"."state_id" 
WHERE "users"."deleted_at" IS NULL AND (((((CAST("users"."first_name" AS VARCHAR) ILIKE '%dev%' OR 
CAST("users"."last_name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("users"."email" AS VARCHAR) ILIKE '%dev%') OR 
CAST("states"."name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("users"."zip_id" AS VARCHAR) ILIKE '%dev%') 

AND 
(CAST("users"."first_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."last_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."email" AS VARCHAR) ILIKE '%dev%' AND 
CAST("states"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."zip_id" AS VARCHAR) ILIKE '%dev%') 

LIMIT 10 OFFSET 0

And here is my coding files

class UserListingDatatable < AjaxDatatablesRails::Base
    #include AjaxDatatablesRails::Extensions::Kaminari

```
def view_columns
    @view_columns ||= 
    {
        first_name: { source: "User.first_name", cond: :like },
        last_name: { source: "User.last_name", cond: :like },
        email: { source: "User.email", cond: :like },
        state: { source: "State.name", cond: :like },
        city: { source: "Neighborhood.name", cond: :like },
        zip: { source: "User.zip_id", cond: :like },
    }
end

private
    def data
        serial_no = 0
        records.map do |user|
        serial_no += 1
        {
            serial_no: serial_no,
            first_name: user.first_name,
            last_name: user.last_name,
            email: user.email,
            state: user.state.name,
            city: user.neighborhood.name,
            zip: user.zip_id,
        }
    end
end

def get_raw_records
    User.joins({ zip: { neighborhood: :state} })
    #abort(User.joins({ zip: { neighborhood: :state} }).to_sql.to_s);
end
```

end

And below is the coffee js file

$ ->
  $('#users-table').dataTable
    processing: true
    serverSide: true
    ajax: $('#users-table').data('source')
    pagingType: 'full_numbers'
    columns: [
        {data: 'serial_no', searchable: false, sortable: false },
        {data: 'first_name', searchable: true, sortable: true },
        {data: 'last_name', searchable: true, sortable: true },
        {data: 'email', searchable: true, sortable: true },
        {data: 'state', searchable: true, sortable: true},
        {data: 'city', searchable: true, sortable: true},
        {data: 'zip', searchable: true, sortable: true},
    ]

**Comment by ajahongir** [comment]
maybe you are using some default_scope in User model?

**Comment by rtplvaibhav** [comment]
This is my user model

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  enum provider: [:provider_facebook, :provider_linkedin]
  validates :first_name, :last_name, :email, presence: true
  validates_format_of :email, :with => Devise::email_regexp

  validates :terms_and_conditions, :acceptance => true
  has_attached_file :image, :styles => { :large => "350x350", :medium => "100x100", :thumb => "60x60" }, :default_url => "missing_:style.png", :convert_options => { :large => '-background white -gravity center -extent 350x350', :medium => '-background white -gravity center -extent 100x100' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  attr_accessor :terms_and_conditions, :current_password, :state_id, :neighborhood_id

  validates :zip_id, :primary_service_consumed, presence: true

  validates :current_password, presence: true, if: "current_password && current_password.empty? && (password.present? || password_confirmation.present?)"
  validates :password, presence: true, confirmation: true, length: { minimum: 6, maximum: 10 }, if: "new_record? || current_password.present? || password_confirmation.present?"

  belongs_to :zip
  #belongs_to :primary_service_consumed, class_name: "Service"
  has_one :neighborhood, through: :zip
  has_one :state, through: :neighborhood
  has_many :profiles_viewed, class_name: 'ProfessionalProfileView', foreign_key: 'user_id'
  has_many :reviews
  has_many :jobs

  acts_as_paranoid

  def self.from_omniauth(auth)

```
#logger.debug "Model variable: #{auth.inspect}";
where(provider_id: auth.uid, provider: User.providers["provider_#{auth.provider}".to_sym]).first
```

  end

  def full_name
    "#{last_name}, #{first_name}"
  end

  def email_name
    self.first_name
  end

  def to_s
    full_name
  end

  def profile_image_url
    ActionController::Base.helpers.asset_path image.url(:medium)
  end

  def user_type
    :user
  end

  def conversations
    Conversation.where('(member1_id = :id and member1_type = :type) OR (member2_id = :id and member2_type = :type)', {id: self.id, type: self.class.name})
  end

  def unread_messages
    conversations.with_messages.inject(0){ |sum, conversation| sum + conversation.messages.where.not("writer_id = :id AND writer_type = :type",{id: self.id, type: self.class.name}).unread.count }
  end

  def conversation_with(member)
    Conversation.where('(member1_id = :id and member1_type = :type and member2_id = :member_id and member2_type = :member_type) OR (member1_id = :member_id and member1_type = :member_type and member2_id = :id and member2_type = :type)', {id: self.id, type: self.class.name, member_type: member.class.name, member_id: member.id}).first
  end

  def review_for(professional)
    reviews.where(professional: professional)
  end
end

**Comment by ajahongir** [comment]
It seams you are using https://github.com/ActsAsParanoid/acts_as_paranoid and it uses deleted_at columns to be sure that record not removed yet

**Comment by rtplvaibhav** [comment]
Yes, but what does it has to do with the AND condition generated in the SQL

**Comment by ajahongir** [comment]
> Yes, but what does it has to do with the AND condition generated in the SQL

look at gem readme - https://github.com/ActsAsParanoid/acts_as_paranoid

try to use something like this in your datatable:

``` ruby
def get_raw_records
  User.with_deleted.joins({ zip: { neighborhood: :state } })
end
```

**Comment by rtplvaibhav** [comment]
Nope :( still the same result

SELECT  "admins".\* FROM "admins" WHERE "admins"."id" = $1  ORDER BY "admins"."id" ASC LIMIT 1[0m  [["id", 1]]
  [1m[35m (3.0ms)[0m  SELECT COUNT(_) FROM "users" INNER JOIN "zips" ON "zips"."id" = "users"."zip_id" INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "zips"."neighborhood_id" INNER JOIN "states" ON "states"."id" = "neighborhoods"."state_id"
  [1m[36m (3.0ms)[0m  [1mSELECT COUNT(_) FROM "users" INNER JOIN "zips" ON "zips"."id" = "users"."zip_id" INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "zips"."neighborhood_id" INNER JOIN "states" ON "states"."id" = "neighborhoods"."state_id" WHERE (((CAST("users"."email" AS VARCHAR) ILIKE '%d%' OR CAST("states"."name" AS VARCHAR) ILIKE '%d%') OR CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%d%') OR CAST("users"."zip_id" AS VARCHAR) ILIKE '%d%') AND (CAST("users"."email" AS VARCHAR) ILIKE '%d%' AND CAST("states"."name" AS VARCHAR) ILIKE '%d%' AND CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%d%' AND CAST("users"."zip_id" AS VARCHAR) ILIKE '%d%')

**Comment by ajahongir** [comment]
> WHERE "users"."deleted_at" IS NULL AND

I dont see this condition on request. seems problem solved?

**Comment by ajahongir** [comment]
if you want to search/order for only fields: first_name, last_name, email. state
you have to define datatable:

``` coffeescript
columns: [
{data: 'serial_no', searchable: false, sortable: false },
{data: 'first_name', searchable: true, sortable: true },
{data: 'last_name', searchable: true, sortable: true },
{data: 'email', searchable: true, sortable: true },
{data: 'state', searchable: true, sortable: true},
{data: 'city', searchable: false, sortable: false},
{data: 'zip', searchable: false, sortable: false},
]
```

**Comment by rtplvaibhav** [comment]
Thanks for helping me so deep but the problem is not solved. I think u didnt understand my problem

This is my whole sql generated while searching, just look at it

SELECT "users".\* FROM "users" 
INNER JOIN "zips" ON "zips"."id" = "users"."zip_id" 
INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "zips"."neighborhood_id" 
INNER JOIN "states" ON "states"."id" = "neighborhoods"."state_id" 
WHERE "users"."deleted_at" IS NULL AND (((((CAST("users"."first_name" AS VARCHAR) ILIKE '%dev%' OR 
CAST("users"."last_name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("users"."email" AS VARCHAR) ILIKE '%dev%') OR 
CAST("states"."name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%dev%') OR 
CAST("users"."zip_id" AS VARCHAR) ILIKE '%dev%')

AND 
(CAST("users"."first_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."last_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."email" AS VARCHAR) ILIKE '%dev%' AND 
CAST("states"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."zip_id" AS VARCHAR) ILIKE '%dev%')

LIMIT 10 OFFSET 0

Now in this query the watch out the last section as explained below

AND 
(CAST("users"."first_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."last_name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."email" AS VARCHAR) ILIKE '%dev%' AND 
CAST("states"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("neighborhoods"."name" AS VARCHAR) ILIKE '%dev%' AND 
CAST("users"."zip_id" AS VARCHAR) ILIKE '%dev%')

This whole bunch is in AND. Ideally, this should not be generated. If i remove this section from query and run in database than results are what we expect, but this AND bunch exists here, dont know wny

**Comment by ajahongir** [comment]
I see..
can you show me a request which coming from client?

**Comment by rtplvaibhav** [comment]
http://localhost:3000/users/user_listing.json?draw=8&columns%5B0%5D%5Bdata%5D=serial_no&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=email&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=state&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=city&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=zip&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=action&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=false&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=dev&search%5Bregex%5D=false&_=1451151536768

1451151536768
columns[0][data]  
serial_no
columns[0][name]  
columns[0][orderable]  
false
columns[0][search][regex]  
false
columns[0][search][value]  
columns[0][searchable]  
false
columns[1][data]  
name
columns[1][name]  
columns[1][orderable]  
true
columns[1][search][regex]  
false
columns[1][search][value]  
columns[1][searchable]  
true
columns[2][data]  
email
columns[2][name]  
columns[2][orderable]  
true
columns[2][search][regex]  
false
columns[2][search][value]  
columns[2][searchable]  
true
columns[3][data]  
state
columns[3][name]  
columns[3][orderable]  
true
columns[3][search][regex]  
false
columns[3][search][value]  
columns[3][searchable]  
true
columns[4][data]  
city
columns[4][name]  
columns[4][orderable]  
true
columns[4][search][regex]  
false
columns[4][search][value]  
columns[4][searchable]  
true
columns[5][data]  
zip
columns[5][name]  
columns[5][orderable]  
true
columns[5][search][regex]  
false
columns[5][search][value]  
columns[5][searchable]  
true
columns[6][data]  
action
columns[6][name]  
columns[6][orderable]  
false
columns[6][search][regex]  
false
columns[6][search][value]  
columns[6][searchable]  
false
draw  
8
length  
10
order[0][column]  
0
order[0][dir]  
asc
search[regex]  
false
search[value]  
dev
start  
0

**Comment by ajahongir** [comment]
sorry, It was really bug at line https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/orm/active_record.rb#L9

now its fixed(https://github.com/ajahongir/ajax-datatables-rails/blob/filtering-improvements/lib/ajax-datatables-rails/orm/active_record.rb#L9) on my branch and not yet merged on main branch(v4)

so make sure that you are using this branch:
gem 'ajax-datatables-rails', git: "git@github.com:ajahongir/ajax-datatables-rails.git', branch: 'filtering-improvements'

**Comment by rtplvaibhav** [comment]
Hi Ajahongir,

It seems that there is still an error with this version https://github.com/ajahongir/ajax-datatables-rails/tree/filtering-improvements. I switched to this version and my table didnt even rendered and gave me the error "undefined method `[]' for nil:NilClass" and when i switched back to the previous version of table v4 then it started working again

**Comment by ajahongir** [comment]
any other error informations?

**Comment by rtplvaibhav** [comment]
No, i could not track anything more. There was nothing more in the log. BTW I managed to get the V4 version working by changing the phrase as you mentioned in active_record.rb.

Thanks for the help

**Comment by ajahongir** [comment]
currently this branch is under development so its important to get your issues and feedbacks. it helps to improve this gem. 
btw sample todo project is working properly.
