### ISSUE TITLE
Custom search for column

### ISSUE THREAD

**Issue by rtplvaibhav** [jbox-web/ajax-datatables-rails#137]
Hi Antillas,

I need to make a different search for a column.  For example i have a column Test which is a combination of 4 columns(test1, test2, test3, test4) seperated with spaces and on which i would like to search a combination of same. How can i achieve this? Below is my code

def view_columns
        @view_columns ||= 
        {
            test: { source: "User.test1 + User.test2 + User.test3 + User.test4", cond: :like },
        }
    end

**Comment by n-rodriguez** [comment]
Hi! Actually you **can't** do this. And I don't know if there is a way to do this with ajax-datatables-rails.

**Comment by n-rodriguez** [comment]
You can do it with https://github.com/activerecord-hackery/ransack and https://github.com/Casecommons/pg_search. It's tricky but it works. (and only with Postgres)
