### ISSUE TITLE
How to sort on polymorphic association

### ISSUE THREAD

**Issue by rbudiharso** [jbox-web/ajax-datatables-rails#138]
Let say I have this model

``` ruby
class Banner < ActiveRecord::Base
  # Banner has name attribute
  belongs_to :featurable, polymorphic: true
end

class Promotion < ActiveRecord::Base
  # Promotion has title attribute
  has_many :banners as: :featurable
end

# in datatables
  def sortable_columns
    @sortable_columns ||= [
      'Banner.name',
      'featurable.title'
    ]
  end


  def searchable_columns
    @searchable_columns ||= [
      'Banner.name'
    ]
  end
```

How can I get it to work with sorting on `featurable.title`, I've tried using `includes` but I got `Cannot eagerly load the polymorphic association :featurable` error. Thank you.

**Comment by etcook** [comment]
Also interested in what the best solution is for this

**Comment by ajahongir** [comment]
@rbudiharso try this one

``` ruby
  def sortable_columns
    @sortable_columns ||= [
      'Banner.name',
      'Featurable.title'
    ]
  end
```

and 

``` ruby
  def get_raw_records
    Banner.includes(:featurable)
  end
```

**Comment by godinezb** [comment]
@ajahongir solution didn't work for me. I'm using includes and the proper sortable column name.
Models:
```
class Pawn < ApplicationRecord
   has_many :items, as: :acquisition
 end

class Item < ApplicationRecord
  belongs_to :acquisition, polymorphic: true
 end
```
Datatables file:
```
def sortable_columns
     @sortable_columns ||= ['Item.folio', 'Acquisition.status']
  end

def get_raw_records
    Item.includes(:acquisition)
  end
```

Any ideas on how can we achieve this?, thanks.

**Comment by ajahongir** [comment]
here works - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb

**Comment by toomanyjoes** [comment]
@ajahongir your working example isn't using polymorphic relationships. That's the problem here. I'm not sure it's possible myself...

**Comment by ajahongir** [comment]
@rbudiharso  put your problem, try to help

**Comment by toomanyjoes** [comment]
@ajahongir this particular post is old, but here's a more recent question that is asking the same thing. I also am having this issue. https://github.com/jbox-web/ajax-datatables-rails/issues/347

**Comment by rbudiharso** [comment]
Sorry, I don't use ajax-datatables-ajax anymore (and Ruby on Rails for that
matter), besides this issue is from 2016, I don't think it's still
relevant. Thank you all for your help.

**Comment by toomanyjoes** [comment]
It's still a problem.
