### ISSUE TITLE
Remember current page?

### ISSUE THREAD

**Issue by abrambailey** [jbox-web/ajax-datatables-rails#141]
I have a list of like 20k users and when I go to edit one it always brings me back to the first page of my datatable. Is there some way to store the page in a session variable in the controller?

**Comment by ajahongir** [comment]
https://datatables.net/examples/basic_init/state_save.html - may be it will useful

**Comment by antillas21** [comment]
:+1: that is the param you need to set in your JS code

**Comment by abrambailey** [comment]
Ah thanks so much @ajahongir
