### ISSUE TITLE
get_raw_records being called three times?

### ISSUE THREAD

**Issue by LucasCioffi** [jbox-web/ajax-datatables-rails#145]
Why might `get_raw_records` be called three times when a table is loading?

**Comment by ajahongir** [comment]
It might be one time to totalCount and couple time to filtering

**Comment by LucasCioffi** [comment]
@ajahongir Thank you.  Is `totalCount` in the gem?

I didn't see it: https://github.com/antillas21/ajax-datatables-rails/search?utf8=%E2%9C%93&q=totalCount

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L45 - here

**Comment by ajahongir** [comment]
what version are you using?

**Comment by LucasCioffi** [comment]
@ajahongir Thanks.  I was searching for `totalCount` instead of `recordsTotal`.
