### ISSUE TITLE
Table row and cell definitions

### ISSUE THREAD

**Issue by Svashtar** [jbox-web/ajax-datatables-rails#148]
Hi,

i am sure someone else already had this problem or needed solution to, but i can't find any good resources on it.

I am trying to migrate my current HTML+DataTables tables to ajax-datatables-rails as records count is increasing and table rendering is getting slower and slower.

First, I was doubtful i could make it even work, because my table data has some nice styles etc, which i didn't want to lose. For example counter_counts are always a badge... On my big surprise, docorators work perfectly, so a basic migration was quite easy.

Now, I have pretty much successfully migrated to ajax-datatables-rails, but I still have two quite important problems:
- first column has to be sortable (i've read this in other tickets and i hope this will be improved, i think it is a must and is too limiting currently). If there are any workaround on this i would really like to know them
- second, and this is why i opened a ticket, is possibility to pass some additional information to TR and TD of generated table. For example, some data inside the cell should be center aligned. I know i can wrap my data into div and center that, but that is just redundant if i can align cell itself. I am also using some TD classes for javascripts etc. Then, the same goes for the TR classes. Sometimes i need a TR to be red/yellow - let's say it is kind of status indicator.

Is there any way i could achieve this? Add classes to generated TR/TD? Also data attributes?
This would be a life saver!

Thx!

**Comment by ajahongir** [comment]
> Is there any way i could achieve this? Add classes to generated TR/TD? Also data attributes?
> This would be a life saver!

I have 2 ways:
1. adding class at `rowCallback`
2. defining col options as `className`

``` coffeescript
$('#dataTable').dataTable
  rowCallback: (row, data) ->
    switch data.action_state
    when 'created' then $(row).addClass('success')
    when 'dropped' then $(row).addClass('warning')
    when 'updated' then $(row).addClass('info')
  columnDefs: [
    targets: -1
    orderable: false
    width: 80
    className: "text-center"
 ]
```

**Comment by ajahongir** [comment]
> first column has to be sortable (i've read this in other tickets and i hope this will be improved, i think it is a must and is too limiting currently). If there are any workaround on this i would really like to know them

https://datatables.net/examples/basic_init/table_sorting.html

**Comment by Svashtar** [comment]
Uh, thanks for such a quick reply :).
I am not sure what did you mean with the link?
I can set that, no problem, but i doesn't work, no effect whatsoever.

**Comment by ajahongir** [comment]
> I am not sure what did you mean with the link?

I thought you are going to define default sort column

**Comment by Svashtar** [comment]
No, unfortunately not.
I can live with sorting, but i desperately need a way to add TR and TD attributes. It would make life so much easier.

**Comment by ajahongir** [comment]
you can do it at `rowCallback` event
