### ISSUE TITLE
Custom Links

### ISSUE THREAD

**Issue by nwoow** [jbox-web/ajax-datatables-rails#149]
Hey I am trying to add two links inside one column like I have thead called action and I want to add edit link and delete link there . I am unable to find a custom method can you help me with this .

**Comment by ajahongir** [comment]
look at this callback https://datatables.net/reference/option/columns.render below I have example:

``` javascript
$('#example').dataTable( {
  "columnDefs": [ {
    "targets": -1,
    "data": "download_link",
    "render": function ( data, type, full, meta ) {
      return '<a href="#">edit</a><a href="#">remove</a>';
    }
  } ]
} );
```

in this example last column will have 2 links - edit, remove

**Comment by antillas21** [comment]
If you want to keep it in ruby, you may need to use the `concat` helper for this... roughly, you will need to do something like this:

``` ruby
class MyDatatables < AjaxDatatablesRails::Base
  def_delegators :@view, :h, :link_to, :edit_path, :destroy_path, :concat, :content_tag

  def data
    records.map do |record|
      [
        record.attribute,
        content_tag(:div) do
          concat(link_to("Edit", edit_path(record)))
          concat(link_to("Delete", destroy_path(record)))
        end
      ]
    end
  end
end
```

**Comment by Svashtar** [comment]
You can also use decorator ([Draper](https://github.com/drapergem/draper)) and it will be even more structured and nice (at least inside AjaxDatatablesRails class). You won't even need delegators. I am using this and works perfectly.

On the other hand, you can also use something like:

`def_delegators :@view, :render` and `render('actions.html.erb')`

Hope it helps...
