### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ricardodovalle** [jbox-web/ajax-datatables-rails#15]
Hi @JoelQ, 

I would like to become a maintainer to the gem ajax-datatables-rails.
Why did you leave de project?

Thanks.

**Comment by antillas21** [comment]
Hi @ricardodovalle,

I just became the maintainer to this gem (ajax-datatables-rails) and would like to share with you
some of the plans I have in mind for its development.

If you would be interested in contributing, I'd be more than happy to add you as a collaborator to this repo.

**Comment by ricardodovalle** [comment]
Hi @antillas21, thank you very much. 
I have used ajax-datatables-rails at production and your contribution to the project it is and will be great and I want to be a collaborator and help you.

At the moment, I am the principal collaborator at jquery-datatables-rails, I am working inside a updated dev branch.

Thanks.

**Comment by antillas21** [comment]
Hey @ricardodovalle,

Thanks for your support. It's great to know someone who has used this gem in production :)

BTW, we have released a [new version](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb) just hours ago. Please check it and let me know what do you think. A word of caution... it may break things, as namespaces and pagination modules have been extracted.

A comprehensive list of changes [is here](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md).

I will now add you as a collaborator. Welcome aboard :smile:

I already identified you as the main collaborator to `jquery-datatables-rails`... as [I opened this PR](https://github.com/rweng/jquery-datatables-rails/pull/95) some weeks ago there. I'd like to comment that if there's anything I can help you with on that front, please let me know. As you already read in our README, your gem is listed as a dependency in this project, to speed the setup process.
