### ISSUE TITLE
Timestamp search

### ISSUE THREAD

**Issue by Svashtar** [jbox-web/ajax-datatables-rails#150]
I am trying to do a search by timestamp. Something like "15:03" - but i get weird results or none at all.
Is it even possible to search created_at, updated_at attributes?

**Comment by ajahongir** [comment]
wich version are you using?

**Comment by Svashtar** [comment]
0.3.1.

**Comment by ajahongir** [comment]
try to override this method - https://github.com/antillas21/ajax-datatables-rails/blob/v0.3.1/lib/ajax-datatables-rails/base.rb#L125

or use latest version - 0-4-0 here is sample project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by Svashtar** [comment]
Will try...thx!
