### ISSUE TITLE
What to  do when you have large number of query in one url

### ISSUE THREAD

**Issue by nwoow** [jbox-web/ajax-datatables-rails#152]
Hey I am getting this "Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)" Is there any way how to fix this

**Comment by ajahongir** [comment]
try to use 'thin' gem in development mode as a web server

**Comment by nwoow** [comment]
What about puma

**Comment by ajahongir** [comment]
I have puma on production and no problem. what version of datatables are you usung?

**Comment by ajahongir** [comment]
https://github.com/rweng/jquery-datatables-rails/issues/112

**Comment by n-rodriguez** [comment]
In short : use POST.
