### ISSUE TITLE
How to override Generator 

### ISSUE THREAD

**Issue by nwoow** [jbox-web/ajax-datatables-rails#154]
Hey I need to add few things in rails generate datatable can you please tell me how can I override the generators I have few repeated tasks .

**Comment by antillas21** [comment]
@nwoow well... I don't know if this could work, but in your rails project, you could:
1. Override the generator class for AjaxDatatablesRails (see default class at: https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/generators/rails/datatable_generator.rb)
2. I think the most important thing to override is the `source_root` method in that class (https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/generators/rails/datatable_generator.rb#L7)

**Comment by nwoow** [comment]
I am trying to create a generator override inside project lib file but I am unable to do so can you check if you can share an example for that . Means I need to override your generator what do I need to do in my application I tried creating folders like lib/generators/rails/datatable_generator.rb but it is not working where do I need to write that .

**Comment by antillas21** [comment]
@nwoow here's what you need to do, override generator and place file here:

```
lib/templates/rails/datatable/datatable.rb
```

**Comment by antillas21** [comment]
Well, that's the path for the template file, which is the final file produced by the generator.

**Comment by nwoow** [comment]
Hey where do you overwrite datatable_generator.rb this
