### ISSUE TITLE
Scope Issue - Support

### ISSUE THREAD

**Issue by nsoparaw** [jbox-web/ajax-datatables-rails#156]
Hi @antillas21, I am new to rails and trying to implement datatables since the dataset being displayed will be ~100k. 

Models: Administrator < User , Participant < User, Member < ActiveRecord::Base 

Now to give different access rights, I have the members_controller in the admin folder and participant folder. I created the member_datatable:
class MemberDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::Kaminari

  search
  sort
  private
  data

 def get_raw_records
    Member.all
  end

and my measure_controller in the admin folder has this:

class Administrator::MembersController < ApplicationController
  before_action :verify_administrator
  def index
    @members = Member.all
    respond_to do |format|
      format.html
      format.json { render json: MemberDatatable.new(view_context) }

```
end
```

  end

now my path is, administrator_members_path and on loading it I get this error:
NameError (uninitialized constant Administrator::MembersController::MemberDatatable):

I think that this is a scope issue.. and I'm not sure how to get MemberDatatable to connect with the controller within admin scope.

**Comment by nsoparaw** [comment]
When I move MemberDatatable.rb from datatables folder to models, it starts working but does not recognize searchable columns:

NoMethodError (undefined method `id' for #Class:0x007f830ba70d10):

This is my searchable:
  def searchable_columns
    @searchable_columns ||= [Member.id]
  end

I had to turn off sorting as well because of the same error

**Comment by saiqulhaq** [comment]
You have to write `searchable_columns` in string format:

``` ruby
@searchable_columns ||= ['Member.id']
```

see the instruction properly in README.md file

**Comment by nsoparaw** [comment]
Yes you are right.. I don't know how did I miss the quotes!
