### ISSUE TITLE
Any reason why branch 'filtering-improvements' was deleted?

### ISSUE THREAD

**Issue by nextpulse** [jbox-web/ajax-datatables-rails#157]
The branch 'filtering-improvements' was deleted.
any reason why? (there was no merge etc)

It fixed some bugs that I was seeing in the main branch.

**Comment by ajahongir** [comment]
@nextpulse it was not deleted. It waits for accept PR - https://github.com/antillas21/ajax-datatables-rails/pull/123

**Comment by nextpulse** [comment]
@ajahongir thanks for the quick reply.

btw: since the branch was gone, existing projects broke (as some doc recommends):

gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'filtering-improvements'

I took a fork for now to keep it working. all good :)

**Comment by ajahongir** [comment]
here is branch - https://github.com/ajahongir/ajax-datatables-rails/tree/filtering-improvements
Its actively developing if you have any ideas or feedback - it will be good

**Comment by antillas21** [comment]
The `filtering-improvements` PR #123 has already been merged to the corresponding `v-0-4-0` branch of this gem.
