### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by Svashtar** [jbox-web/ajax-datatables-rails#158]
Hi,

I have many DTs in my app, but one of them is like no other :) - it is giving me major headaches.
When the data is loaded, and when i move from page to page, on every page there are different counts of rows.

For example I have a page size set to 10 records.
Data loads, the information says 100 records total
There are only 9 rows on the first page. I move to next page and it can be anything from 4-10 rows.
And so on.

Did someone else had similar problems?
What are possible reasons?

I am also noticing that sometimes the query generated is wrong and it wants to select a field it doesn't exist. If the field for association is object_id - the query fails on object_id_id

Any clues?

**Comment by ajahongir** [comment]
- what is your version of gem? latest one is 0.4
- can you show your items and count request queries?
