### ISSUE TITLE
Problem with columns definition

### ISSUE THREAD

**Issue by nevedimko** [jbox-web/ajax-datatables-rails#159]
I want to use named columns. Like 

``` javascript
$(function() {
  return $('#table_id').dataTable({
    processing: true,
    serverSide: true,
    ajax: 'ajax_url',
    columns: [
      {data: 'id' },
      {data: 'name' },
      {data: 'phone' }
    ]
  });
});
```

I set the following in my_datatable.rb

``` ruby
def data
  records.map do |record|
    {
      'id' => record.id,
      'name' => record.name,
      'phone' => record.phone
    }
  end
end
```

And after that I get an error:
`no implicit conversion from nil to integer`

**Comment by antillas21** [comment]
I think this functionality is part of what @ajahongir implemented on the `v-0-4-0` branch.

**Comment by ajahongir** [comment]
@nevedimko  can you show your my_datatable.rb?

**Comment by nevedimko** [comment]
@ajahongir Yes, sure. It looked like this:

``` ruby
class SubjectDatatable < AjaxDatatablesRails::Base

  def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= [
      'Subject.id',
      'Subject.name',
      'Subject.suggest'
    ]
  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= [
      'Subject.id',
      'Subject.name',
    ]
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
        'id' => record.id,
        'name' => record.name,
        'suggest' => record.suggest
      ]
    end
  end

  def get_raw_records
    Subject.all
  end

  # ==== Insert 'presenter'-like methods below if necessary
end
```

I'm trying to make friends [angular-datatables](http://l-lin.github.io/angular-datatables/#/serverSideProcessing) with ajax-datatables-rails

Also I have a problem with using `.group(:id)` in `get_raw_records` function. After that count of all results and count of filtered results break down and looks like `NaN`

Also when I'm using a custom select like `.select("COUNT(related_model.id) as count")` in `get_raw_records` function, then I can't use it to search for.

**Comment by ajahongir** [comment]
well, I recomend you use latest version(0.4) of the gem and you will have search & sort out of the box. try to define like this:

``` ruby
class SubjectDatatable < AjaxDatatablesRails::Base

  def view_columns
    @view_columns ||= {
      id: { source: "Subject.id", cond: :eq },
      name: { source: "Subject.name" },
      suggest: { source: "Subject.suggest" }
    }
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
        'id' => record.id,
        'name' => record.name,
        'suggest' => record.suggest
      ]
    end
  end

  def get_raw_records
    Subject.all
  end

  # ==== Insert 'presenter'-like methods below if necessary
end
```

also look at this sample project https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by ajahongir** [comment]
also you can see here custom column sample too - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb

**Comment by nevedimko** [comment]
@ajahongir Thanks for your response. I tried to work with version 0.4 and this is my_datatable.rb

``` ruby
class SubjectDatatable < AjaxDatatablesRails::Base

  def view_columns
    @view_columns ||= {
      id: { source: "Subject.id", cond: :eq },
      name: { source: "Subject.name" },
      suggest: { source: "Subject.suggest" },
      usage_count: { source: "usage_count" }
    }
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
        'id' => record.id,
        'name' => record.name,
        'suggest' => record.suggest,
        'usage_count' => record[:usage_count]
      ]
    end
  end

  def get_raw_records
    Subject.select('subjects.*, COUNT(users.id) AS usage_count')
      .joins('LEFT JOIN users ON subjects.name = users.major')
      .group('subjects.id')
  end

  # ==== Insert 'presenter'-like methods below if necessary
end

```

If I set `order[0][column]=0` in query params, then I see `no implicit conversion from nil to integer`

If `order[0][column]=id`, then `Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC LIMIT 10 OFFSET 0' at line 1: SELECT subjects.*, COUNT(users.id) AS usage_count FROM subjects LEFT JOIN users ON subjects.name = users.major GROUP BY subjects.id ORDER BY ASC LIMIT 10 OFFSET 0`

**Comment by ajahongir** [comment]
@nevedimko make sure that using right version of the gem. try to include like this:
`gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'v-0-4-0'`

**Comment by nevedimko** [comment]
Great. Thanks.
I used this gem:
`gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0'`

Now there's just one issue:
`Showing 1 to 10 of 866 entries (filtered from NaN total entries)`

Total count works incorrect with my `get_raw_records` function.

**Comment by ajahongir** [comment]
@nevedimko  try to override as_json method as

``` ruby
    def as_json(options = {})
      {
        recordsTotal: get_raw_records.count(:all).count,
        recordsFiltered: get_raw_records.model.from("(#{filter_records(get_raw_records).except(:limit, :offset, :order).to_sql}) AS foo").count,
        data: data
      }
    end
```

**Comment by nevedimko** [comment]
I already did so. 
@ajahongir Thank you. You helped me a lot

**Comment by ajahongir** [comment]
круто

**Comment by n-rodriguez** [comment]
Fixed in master branch.
