### ISSUE TITLE
undefined method `each_value' for nil:NilClass rails 4

### ISSUE THREAD

**Issue by boydenhartog** [jbox-web/ajax-datatables-rails#160]
Hi guys,

I'm running into an issue with my datatable. I can't seem to figure out where the problem is coming from.  This error keeps popping up when I load my datatable:

NoMethodError (undefined method 'each_value' for "/orders.json":String):
  app/datatables/order_datatable.rb:19:in 'data'
  app/controllers/orders_controller.rb:12:in 'block (2 levels) in index'
  app/controllers/orders_controller.rb:10:in 'index'

I've stripped down my datatable to the bare minimum, but am still getting this error. Here is my setup:

Table:

```

<table id="orders-table" class="table table-striped table-bordered table-hover" data-source="<%= orders_path(format: :json) %>">
  <thead>
    <tr>
      <th>Ship to name</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
```

Controller action:

```
  def index
    respond_to do |format|
      format.html
      format.json { render json: OrderDatatable.new(view_context, { store_id: params[:store_id] }) }
    end
  end
```

Datatable.rb:

```
class OrderDatatable < AjaxDatatablesRails::Base
  def_delegators :@view, :params, :link_to, :orders_path, :stores_path

  def sortable_columns
    # Declare strings in this format: ModelName.column_name
    #@sortable_columns ||= ['Order.id', 'Store.name', 'Order.ship_to_name', 'Order.ship_to_email', 'Order.status', 'Order.created_at' ]
    @sortable_columns ||= ['Order.ship_to_name']
  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    #@searchable_columns ||= ['Order.id', 'Store.name', 'Order.ship_to_name', 'Order.ship_to_email']
    @searchable_columns ||= ['Order.ship_to_name']
  end

  private

  def data
    records.map do |record|
      [
        record.ship_to_name
      ]
    end
  end

  def get_raw_records
    # insert query here
    Order.all
  end
end
```

And my coffeescript: 

```
$ ->
  $('#orders-table').DataTable
    processing: true
    serverSide: true
    retrieve: true
    lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]]
    dom: 'lfBrtip'
    buttons: ['csv', 'excel', 'pdf']
    ajax: data: (d) ->
      d.order = $('#orders-table').data('source')
      d.store_id = $('#store-id').val();
      return
```

What's going wrong here? I have an other datatable that uses exactly the same code that is working fine..

**Comment by antillas21** [comment]
By any chance are you using the rails 5 beta or RC? `each_value` has been
deprecated there.

**Comment by ajahongir** [comment]
can you show your params sending to a server?

if you really work with rails 5 or ruby higer 2.2 - user 0.4 version of this gem.

**Comment by ajahongir** [comment]
@antillas21  could we release 0.4 version?

**Comment by boydenhartog** [comment]
Hi guys,

I'm not using rails 5. Using:

gem 'rails', '4.2.3'
gem 'jquery-datatables-rails'
gem 'ajax-datatables-rails'

The parameters sent to the server:
Parameters: {"draw"=>"1", "columns"=>{"0"=>{"data"=>"0", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>"/orders.json", "start"=>"0", "length"=>"10", "search"=>{"value"=>"", "regex"=>"false"}, "_"=>"1467263159400"}

It's weird because I have another datatable using exactly the same setup and that one is working fine. There is no difference between the two code wise, so I don't know what the problem is. When I test my get_raw_data method I get orders as result, so the data should not be empty.

**Comment by ajahongir** [comment]
I see that you are passing wrong options. 
`order` options should not look like this. you have to looking for mistakes in defining datatable in Js(frontend)

**Comment by boydenhartog** [comment]
But the weird thing is, the parameter in my other datatable is the same (different path, "/vendor_skus.json", but this table works. I reckon there must be a different problem

**Comment by ajahongir** [comment]
> "order"=>"/orders.json"

but it not right option for datatable

**Comment by ajahongir** [comment]
it shold be and Hash or Array

**Comment by boydenhartog** [comment]
```
ajax: data: (d) ->
  d.order = $('#orders-table').data('source')
  d.store_id = $('#store-id').val();
  return
```

What would be the problem here? I fail to understand..

**Comment by ajahongir** [comment]
> d.order = $('#orders-table').data('source')

try to remove this line

**Comment by boydenhartog** [comment]
This worked. Thanks a bunch mate!!

**Comment by pawlarius** [comment]
@ajahongir im using rails 5..
