### ISSUE TITLE
Getting - TypeError (no implicit conversion of nil into String):

### ISSUE THREAD

**Issue by steamboy** [jbox-web/ajax-datatables-rails#161]
Hi @antillas21 

I'm getting the Rails error below. Not sure what's happening

`TypeError (no implicit conversion of nil into String):`

Parameters

`Parameters: {"id"=>"312", "job_id"=>"9627", "criteria_no"=>"2", "draw"=>"3", "columns"=>{"0"=>{"data"=>"0", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"1", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"2", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"3", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"4", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"desc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"t", "regex"=>"false"}, "_"=>"1467941516425"}`

```
def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= [
      'Model1.first_name',
      'Model1.last_name',
      'Model2.answer'
    ]
end
```

Initialisation

```
var dt_columns = [];
  dt_columns = [{ sortable: true, searchable: true }];
  - data_record.size.times do
    dt_columns.push({ sortable: false, searchable: true });
  dt_columns.push({ sortable: false, searchable: true });
  dt_columns.push({ sortable: false, searchable: true });

$('.validate-view-results-table').dataTable({ 
  processing: true,
  serverSide: true,
  ajax: $(".name-table").data("source") + "&criteria_no=#{data_record.size}",
  columns: dt_columns,  
});

```

**Comment by ajahongir** [comment]
@steamboy I recomend to use latest version 0.4 and you will have searching & sorting out of box.

**Comment by steamboy** [comment]
@ajahongir, using it now. didn't notice this branch. 

but how do i use kaminari now? 

noticed that this branch doesnt support extensions anymore

**Comment by ajahongir** [comment]
> using it now. didn't notice this branch.

well, rename your method `searchable_columns` to `view_columns` and some override it

``` ruby
def view_columns
    @view_columns ||= {
      first_name: { source: 'Model1.first_name' },
      last_name: { source: 'Model1.last_name' },
      answer: { source: 'Model2.answer', cond: :eq }
    }
end
```

here you can find sample project  - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to
here is README for 0.4 version - https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0

**Comment by ajahongir** [comment]
> but how do i use kaminari now?

you can use kaminari. you have to override this method: `paginate_records`

https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/orm/active_record.rb#L21

**Comment by antillas21** [comment]
I've flirted with the idea of dropping kaminari or pagination extensions
support from that branch onward, as they're really just a decorator to
basic active record offset and limit methods.

**Comment by antillas21** [comment]
point is, if you have kaminari in your project, the gem won't clash with
it, and will not get in the way.
