### ISSUE TITLE
.id? Display each items id?

### ISSUE THREAD

**Issue by oscar6654** [jbox-web/ajax-datatables-rails#162]
in my
  def get_raw_records
    # insert query here
    Invoice.all
  end

the Invoice should have auto generated id number for each row of entry.
I have 

def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= ['invoices.id']
end
def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= ['invoices.id']
end

then 
def data
    records.map do |record|
      [
        link_to(record.id,record)
      ]
    end
end

but its giving error. also how do I add checkboxes? I tried def_delegator @view, :check_box_tag and replaced link_to as check_box_tag doesnt work. Im trying to pass the selected ids into checkbox so I can edit multiple rows.

**Comment by oscar6654** [comment]
basically I wanted to add this functionality inside: http://railscasts.com/episodes/165-edit-multiple?view=asciicast

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/issues/149

**Comment by oscar6654** [comment]
problem I have is that I am getting ajax errors because id is not showing in the table..

**Comment by ajahongir** [comment]
I recomend to use 0.4 version of this gem.

**Comment by oscar6654** [comment]
how? gem 'ajax-datatables-rails', '0.4' doesnt exist

**Comment by antillas21** [comment]
version 0.4 is unreleased and is a test bed, BTW.

If you would like to use it, you need to declare it in your gemfile like
this:

`gem "ajax-datatables-rails", github: "antillas21/ajax-datatables-rails",
branch: "v-0-4-0"`

[image: --]

José Antonio Antillón
[image: http://]about.me/aantillon
http://about.me/aantillon?promo=email_sig

**Comment by oscar6654** [comment]
im still getting ajax errors when I added invoices.id. Im using postgresql, I can display the id if im not using the ajaxx and just on table directly. i kept searching on google and so far no one has done edit multiple with server processing using datatables

**Comment by ajahongir** [comment]
@oscar6654 can you show your latest changes?

> here you can find sample project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to
> here is README for 0.4 version - https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0

**Comment by n-rodriguez** [comment]
Use the new hash format : https://github.com/jbox-web/ajax-datatables-rails#map-data
