### ISSUE TITLE
Concat fields in searchable_columns

### ISSUE THREAD

**Issue by inyerade** [jbox-web/ajax-datatables-rails#165]
hi
exist the posibility to put a concatenation of 2 fields in one "column" of searchable_columns and orsortable_columns like this

```
# User model

def full_name
    "#{self.first_name} #{self.last_name}"
end

# datatable User
def searchable_columns
    @searchable_columns ||= [
        'User.id',
        'User.full_name', # User have method full_name
    ]
end
```

**Comment by ajahongir** [comment]
https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by rodrigoapereira** [comment]
hi @ajahongir.
I'm having similar problem here. But i'm using PostgreSQL function for concat two columns.

``` rb
def sortable_columns
  @sortable_columns ||= [
    'users.id', # for this column it's easy to correct, only use User.id for fix
    'concat_ws(\' \', users.first_name, users.last_name)'
  ]
end
```

**It's only for example.**

I receive this deprecation message:
[DEPRECATED] Using table_name.column_name notation is deprecated. Please ...

**Comment by inyerade** [comment]
Hi @ajahongir 
Yesterday I went back to this, I already implement v-0.4.0 but  I do not understand how to query the concatenation of fields of other table 

I have models `Agenda` and `Person` with his tables, in `Agenda` I have the `Person` key `Agenda.person_id` and a Person have first_name (`Person.last_name`) and last_name (`Person.last_name`)

In def view_columns what I have to put?

```
...
person: { source: "full_name", cond: filter_full_name_condition },
...
```

and in filter condition?

```
def filter_full_name_condition
   ????????????????????'
end
```

**Comment by ajahongir** [comment]
@inyerade well, what is your msql query for that:

``` sql
SELECT agendas.*, CONCAT(persons.first_name, ' ', persons.last_name) AS full_name FROM persons LEFT JOIN agendas on agendas.person_id = parsons.id
```

right?
if so, we can do it as:

``` ruby
def filter_full_name_condition
   ->(column) { column.table[column.field].eq(column.search.value) } # this returns condition: 'full_name=#value'
end
```

**Comment by inyerade** [comment]
thx @ajahongir 
but this give me `wrong constant name full_name`
 in line 
`->(column) { column.table[column.field].eq(column.search.value) } # this returns condition: 'full_name=#value'`

I put the query in the console and call `output.first.full_name` and is fine, give me the values

And I see the console and the error is in the COUNT query

```
SELECT COUNT(*) FROM "agendas" INNER JOIN "patients" ON "patients"."id" = "agendas"."patient_id" WHERE (agendas.deleted IS NOT false)

Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.9ms)

NameError (wrong constant name full_name):
...
```

What I missing?

**Comment by ajahongir** [comment]
> I put the query in the console and call output.first.full_name and is fine, give me the values

I guess right way to call custom field is:
`output.first['full_name']`

can you put your datatable here again?

**Comment by inyerade** [comment]
Hi @ajahongir 
`output.first['full_name']` and `output.first.full_name` works fine.

Here is my datatable

```
class AgendaDatatable < AjaxDatatablesRails::Base

    def view_columns
        @view_columns ||= {
            id: { source: "Agenda.id", cond: :eq },
            hour: { source: "Agenda.hour" },
            full_name: { source: "full_name", cond: filter_full_name_condition },
        }
    end

    private

    def_delegators :@view, :link_to, :h, :mailto, :edit_agenda_path, :agenda_path
    def data
       records.map do |agenda|
           {
               id: link_to( agenda.id , agenda_path( agenda.id ) ),
               hour: (I18n.l( agenda.hour, :format => "%A %e de %B de %Y <b>%H:%M</b>", :locale => 'es')).capitalize,
               full_name: "#{agenda.patients.name} #{agenda.patients.last_name}",
           }
        end
    end


    def get_raw_records
      # insert query here
          Agenda.where( "agendas.deleted IS NOT false" ).select("agendas.*  , patients.* , CONCAT( patients.name, ' ', patients.last_name) AS full_name ").joins( :patients )
    end

    def filter_full_name_condition
        ->(column) { column.table[column.field].eq(column.search.value) } # this returns condition: 'full_name=#value'
    end
end

```

**Comment by ajahongir** [comment]
Iam not sure but try to change this line.

~~full_name: "#{agenda.patients.name} #{agenda.patients.last_name}",~~

``` ruby
  full_name: agenda['full_name']
```

**Comment by inyerade** [comment]
same :(

**Comment by inyerade** [comment]
Reading I found that in posgresql can not use an alias in WHERE clause. I looking for some option to what I want.
Is there  a way to put in the filter condition some like:

```
WHERE CONCAT( patients.name , patients.last_name) ILIKE '%#{ column.search.value }%';
```

???

**Comment by ajahongir** [comment]
try something like this

``` ruby
def filter_full_name_condition
  SEPARATOR = Arel::Nodes.build_quoted(' ')
  ->(column) do
    full_name = Arel::Nodes::NamedFunction.new(
      'concat',
      [column.table[:name], SEPARATOR, column.table[:last_name]]
    )
    full_name.match column.search.value
  end
end
```

**Comment by inyerade** [comment]
thx @ajahongir , works great

few changes on your last code

```
SEPARATOR = Arel::Nodes.build_quoted(' ') # inside def throw error
def filter_full_name_condition
    ->(column) do
        full_name = Arel::Nodes::NamedFunction.new(
            'concat',
            [column.table[:name], SEPARATOR, column.table[:last_name]]
        )
        full_name.matches "%#{column.search.value}%"           # match change to matches and add the % % flags
    end
end
```

**Comment by Subtletree** [comment]
Is there a new way of doing this now? 

In my case `column` is just the string being searched. Therefore `column.table` and `column.search` are undefined

**Comment by inyerade** [comment]
@Subtletree can you post your code? Are you using v0.4.0?

**Comment by Subtletree** [comment]
@inyerade Yip v0.4.0. Thanks for taking a look.

Here's the change as far as I can tell. `filter` used to pass the `column` to `cond` but now just `value` is passed:
https://github.com/jbox-web/ajax-datatables-rails/commit/92c2254208c78fe1bf60df552d62171aea3834b6#diff-a7f0f3ee893084549cc5255576b14fe3

```
  SEPARATOR = Arel::Nodes.build_quoted(' ') # inside def throw error
  def filter_full_name_condition
    ->(column) do
      full_name = Arel::Nodes::NamedFunction.new(
        'concat',
        [column.table[:first_name], SEPARATOR, column.table[:last_name]]
      )
      full_name.matches "%#{column.search.value}%" # match change to matches and add the % % flags
    end
  end
```
If i make a search of the table with the letter 'b' i get:
`NoMethodError (undefined method 'table' for "b":String`

**Comment by Subtletree** [comment]
Bit hacky but just setting the column manually is working for me
`column = self.datatable.columns[2]`

**Comment by ajahongir** [comment]
I am not sure that passing search value[string] instead of datatable#column. column is more flexable

**Comment by ajahongir** [comment]
>Is there a new way of doing this now?

>In my case column is just the string being searched. Therefore column.table and column.search are undefined

not its [fixed](https://github.com/jbox-web/ajax-datatables-rails/commit/07795fd26849ff1b3b567f4ce967f722907a45be)

**Comment by gs2589** [comment]
@inyerade , can you post the final code that worked. Im trying to implement and I get:

NameError (wrong constant name show_name)

**Comment by inyerade** [comment]
HI @gs2589 

Better show your code and We help you

(I do not find this code :) )

**Comment by n-rodriguez** [comment]
@gs2589 @inyerade 

I think it's :

```ruby
def filter_full_name_condition
  SEPARATOR = Arel::Nodes.build_quoted(' ')
  ->(column) do
    full_name = Arel::Nodes::NamedFunction.new(
      'concat',
      [column.table[:name], SEPARATOR, column.table[:last_name]]
    )
    full_name.match column.search.value
  end
end
```

**Comment by creativetags** [comment]
I'm trying to follow this thread to recreate the solution. I've got it working but it looks hacky:

```
class UserDatatable < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= {
      full_name: { source: "full_name", cond: filter_full_name_condition },
      email: { source: "User.email", cond: :like },
      created_at: { source: "User.created_at" }
    }
  end
  def data
    records.map do |record|
      {
        id: record.id,
        full_name: record['full_name'],
        email: record.email,
        created_at: record.created_at
      }
    end
  end
  def get_raw_records
    User.select("users.id, CONCAT(users.first_name, ' ', users.last_name) AS full_name, users.email, users.created_at")
  end
  def filter_full_name_condition
    separator = Arel::Nodes.build_quoted(' ')
    ->(column, formated_value) do
      full_name = Arel::Nodes::NamedFunction.new(
        'concat',
        [self.datatable.columns[2].table[:first_name], separator, self.datatable.columns[2].table[:last_name]]
      )
      full_name.matches formated_value
    end
  end
end
```

**Comment by yverbytskyi** [comment]
> `full_name.matches formated_value`
this one builds ILIKE 'formated_value' query, if you need  %LIKE% query, can try
```full_name.matches "%#{formated_value}%" ```
