### ISSUE TITLE
Unsortable / Unsearchable columns definition

### ISSUE THREAD

**Issue by ghost** [jbox-web/ajax-datatables-rails#167]
I feel this is quite trivial, but both in the master branch and 0.4.0 branch I cant seem to figure out how to exclude columns from being sortable and/or searchable.

Lets say I have 4 columns: 
City.name, City.status, City.latitude, City.longitude
(`status` is simply an image_tag with a color coded icon)

I want only the `name` column searchable
I want only the `name`, `latitude` and `longitude` columns sortable

How would I do this in both the master branch or 0.4.0 branch? Or is this simply unsupported  functionality?

Currently if I click on a column that is not represented in the `@sortable_columns` it will generate an empty `ORDER BY` clause resulting in a MySQL syntax error.

**Comment by ajahongir** [comment]
@cdekker check this sample project for your case https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by ajahongir** [comment]
let me know if you have any problems

**Comment by ghost** [comment]
I used that example as a basis, but it seems that all 5 columns in that example are sortable, with 2 having their custom filter conditions. Its not clear to me how I can make a column NOT sortable.

I guess making a column NOT searchable is done by simply omitting the `cond:` key?

**Comment by ajahongir** [comment]
1. you can controll ordering via 'order' option in datatablejs option as here - https://datatables.net/examples/basic_init/table_sorting.html
2. if you want to turn of searching - just dont searching params to a server.

**Comment by ajahongir** [comment]
if you dont define 'cond' option datatable.rb - by default it searchs with 'like' query

**Comment by ghost** [comment]
I don't want to turn off searching, I want to search only on specific columns! Same with ordering. 

Given the example in the OP with City and the 4 columns,  whenever a user enters something in the search field I want only to search the field of the first column (name). 

Similar with ordering. If I want to disable ordering on a specific column, do I need to set that using the JavaScript you linked? Or is it possible  to do that through your gem?

**Comment by ajahongir** [comment]
well, you can do it both in js and rb
if you want to disable searching you can do like this^

``` ruby
  def view_columns
    @view_columns ||= {
      id: { source: "City.id", searchable: false, orderable: false },
      name: { source: "City.name" },
      ...
    }
  end
```

but you can do this also on client side:

``` coffescript
      $('#dataTable').dataTable
        ajax: cities_path()
        columns: [
            data: "id", bSortable: false
          ,
            data: "name"
         ...
        ]
```

**Comment by ghost** [comment]
`searchable` and `orderable` options in the Hash! This is great information, thanks! :)

If possible, add this to the Readme when you have time. All possible options in the `view_columns` method were unclear to me :)

**Comment by ajahongir** [comment]
> If possible, add this to the Readme when you have time. All possible options in the view_columns method were unclear to me :)

thats good idea, I will.

**Comment by ajahongir** [comment]
@cdekker 
you can close an issue if you have solved your problem
and let me know if you have any questions.

**Comment by ghost** [comment]
Thanks! Will do.

**Comment by ivanamihalek** [comment]
A related question - not sure if it merits (re)opening:  is the  columns field  in the  javascript  snippet above the same one that later appears in datatables.rb in options[:columns]? I am asking because I am  ending up with options[:columns] undefined, and could use some help figuring out how it happens.

**Comment by ajahongir** [comment]
guys you can look at this discussion for some details and concept here - https://github.com/antillas21/ajax-datatables-rails/pull/105

**Comment by ajahongir** [comment]
@ivanamihalek

> is the columns field in the javascript snippet above the same one that later appears in datatables.rb in options[:columns]?

yes Its, these options comes from client(js) and converts to Rb column object (https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/datatable/datatable.rb#L42)

**Comment by ivanamihalek** [comment]
Thank you very much for the reply.
 At this point (datatable.rb:42) my implementation already goes belly up because options[:columns] is undefined. (It might be helpful if columns method checked for the existence before using.) Where is the earliest place in Rb where options can be inspected/checked?

**Comment by ivanamihalek** [comment]
@ajahongir 
 It looks like the coffeescript part is not being executed at all. I was able to run your how-to example without much trouble (thanks). I must have missed something wen applying it to my own case.  Is there perhaps something in the  configuration I should be paying attention to?

**Comment by ajahongir** [comment]
@ivanamihalek in how-to I am using gems(js libs) like: `rails_script`, `coffee_routes` for mere ditails look at them.
if you still having problem - post your scripts, will look them

**Comment by ajahongir** [comment]
> options[:columns] is undefined. (It might be helpful if columns method checked for the existence before using.)

can you show your params(which coming from datatable.js)? I gues you have problem with defining Datatable.js. May be because in how-to I used coffeescript. btw you can compare your params and params in how-to.

**Comment by ivanamihalek** [comment]
I was able to trace down this particular problem to the json data sourcing in
`<table id="users-table" data-source="<%= users_path(format: :json) %>">`
leftover from the original ajax-datatables-rails README.md.

The whole error stack I was seeing can bee reproduced by visiting localhost:3000/cities.json in v0.4.0.-how-to example, in development mode.

Thank you for bearing with me!
