### ISSUE TITLE
Rails 5: undefined method `[]' on 'records'

### ISSUE THREAD

**Issue by ghost** [jbox-web/ajax-datatables-rails#168]
Seems like something is broken in Rails 5 by converting the `get_raw_records` to the `records` private method used in the `data` method, as it generates the following exception:

`NoMethodError (undefined method`[]' for nil:NilClass):`

From what I have gathered this happens on line 93 of base.rb:

`records = sort_records(records)     if datatable.orderable?`

**Comment by ajahongir** [comment]
@cdekker  is this issue still actual?

**Comment by ghost** [comment]
Yes!
From what I have seen it seems like the problem is in the Column class with some fields being not set or invalidly set. I haven't been able to determine why this happens in Rails 5 and not in your Rails 4.2 example project.

Take this example:

```
def view_columns
  @view_columns ||= {
      name: { source: 'Kid.name', cond: :like },
      gender: { source: 'Kid.gender', searchable: false, orderable: false },
      age: { source: 'Kid.dob', cond: :eq }
  }
end
```

Eventually reaches the code through `records` > `retrieve_records` > `sort_records(records)` > `sort_query` > `custom_field?` > `source`  where `@view_column[:source]` is called and `@view_column` is nil (not set) in column.rb.

From the looks of the initialization code this should be set by:
`@view_column = datatable.view_columns[options["data"].to_sym]`
However, I don't set this value explicitely, but in my example `options["data"]` is `"0"`. Is this supposed to be the column index? If so, it seems it is not updated to the new view_columns being a Hash instead of an Array?

**Comment by ajahongir** [comment]
`options["data"]` is column index or column name(in this case name you can pass via https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/assets/javascripts/cities.js.coffee#L10)

**Comment by ghost** [comment]
Does that mean that setting the column names in JavaScript is **required** in 0.4.0? 
Because if you don't, it will try to get `view_columns["0".to_sym]` which **always** returns nil on the Hash with column names defined in `def view_columns ... end`

It seems like arbitrary busy work having to define those columns. Wouldn't it be better to see if column names are defined in JS, and if not, simply use the index on the keys of the hash? So
`@view_column = datatable.view_columns[options["data"].to_sym]`
Becomes

```
if options["data"] ~= /\A\d+\Z/
    @view_column = datatable.view_columns[datatable.view_columns.keys[options["data"].to_i]]
else
    @view_column = datatable.view_columns[options["data"].to_sym]
end
```

That way, if its a number, the correct index is taken. If its not a number, the literal name of the column is looked up. Then no JS column definition is needed.

**Comment by ajahongir** [comment]
well, we have 2 ways of defining datatables:
1. in this way you have to define column name in JS as (https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/assets/javascripts/cities.js.coffee#L10)

``` coffeescript
      $('#dataTable').dataTable
        ajax: cities_path()
        columns: [
            data: "id"
          ,
            data: "name"
          ,
            data: "iata"
          ,
            data: "custom_column"
          ,
            data: "country_name"
        ]
```

``` ruby
  def view_columns
    @view_columns ||= {
      id: { source: "City.id", cond: :eq },
      name: { source: "City.name" },
      custom_column: { source: "custom_column", cond: filter_custom_column_condition },
      iata: { source: "City.iata" },
      country_name: { source: "City.country_id", cond: filter_country_condition },
    }
  end

  def data
    records.map do |city|
      {
        id: city.id,
        name: city.name,
        iata: city.iata,
        country_name: city.country.try(:name),
        custom_column: city[:custom_column]
      }
    end
  end
```

2 

``` ruby
  def data
    records.map do |city|
      [
        city.id,
        city.name,
        city.iata,
        city.country.try(:name),
        city[:custom_column]
      ]
    end
  end
```

in 1st way you bind column name in JS with column name in RB Its prefered way because you will have search and order out of box.

**Comment by ghost** [comment]
Thanks! I went with method 1 and defined the columns on the JS side as well as in `def view_columns ... end` on the server side.

Incidently, I noticed that `searchable:` and `sortable:` options in the `def view_columns ... end` method are always overridden by the options set in the JavaScript (by default all columns sortable and searchable) which is posted with every sort and search remote AJAX call. So I also had to set `bSortable` and `bSearchable` to false in a few columns using JavaScript.

Is this intended behaviour? If so, I think I can close this issue.

**Comment by ajahongir** [comment]
yes its
