### ISSUE TITLE
Order over multiple DB fields in a single column

### ISSUE THREAD

**Issue by ghost** [jbox-web/ajax-datatables-rails#170]
Consider the model `Event` with a `name`,  `start` and `end` date field. I am using the 0.4.0 branch with the new column definitions.

In Ruby I have defined the `view_columns` as such:

```
  def view_columns
    @view_columns ||= {
        name: { source: 'Event.name', cond: :like },
        period: { source: 'Event.start' }
    }
  end

  def data
    records.map do |event|
      {
          name: event_permission_link(event),
          period: event.start ? "#{l(event.start)} - #{l(event.end)}" : '-'
      }
    end
  end
```

Now, when I order on the Period column, containing both the start and end date, only a `ORDER BY events.start ASC` is added. How to I make sure this is changed into `ORDER BY events.start ASC, events.end ASC` so both fields are ordered correctly for that specific DataTables column? The period column is only sortable, not searchable.

**Comment by ajahongir** [comment]
I am not sure that is possible custom ordering. but I thing Its interesting feature.

**Comment by ghost** [comment]
Thanks! Yeah, feels like it would be a nice addition if we could customize the ordering similar to the search procs with 0.4.0.

Another example I have in my app is a `Date` field `date_of_birth` that I want to display as age: (`Time.zone.today - p.date_of_birth`). This means that the ordering for this field should be the exact opposite of what is selected.

**Comment by ajahongir** [comment]
I am not sure but you can try to set ordering DESC in JS by default for this column.

**Comment by ghost** [comment]
Well, I don't want to sort on that specific column by default ;) 

But when the user wants to _sort that column in ASC order_ I think it would be the responsibility of the server to make that translation. That way it is similar to how the `def data ... end` method makes the same translation the other way around from DB to View

**Comment by ajahongir** [comment]
in feature releases we should be able to custom order as a search for every field, now It not released yet.

**Comment by n-rodriguez** [comment]
In Datatable you can specify several columns for the default ordering :

```json
order:  [[ 1, "asc" ], [ 2, "asc" ]]
```
Note that you must specifiy the column ID and not the column name here.

**Comment by n-rodriguez** [comment]
If you press shfit when clicking to order column, you can order by several columns too.

**Comment by n-rodriguez** [comment]
But ordering over multiple DB fields in a single column seems tricky...
