### ISSUE TITLE
 404 (Not Found) in production - missing relative url

### ISSUE THREAD

**Issue by ivanamihalek** [jbox-web/ajax-datatables-rails#172]
Apologies if this was answered somewhere already:

I have a working development version of a datatable, which fails with  "Failed to load resource: the server responded with a status of 404 (Not Found)"  in production. Where should I look for the culprit?

Thanks for any possible help.

**Comment by ivanamihalek** [comment]
ok ... it is the relative url root which is missing in my case .. how do I set it up in coffeescript?

**Comment by ivanamihalek** [comment]
I hardcoded the root   in each   App.Base extension - please let me know if there is a better way.

**Comment by ajahongir** [comment]
@ivanamihalek am I right that you are having problem with `coffee_routes` gem?
if so, you can look at https://github.com/railsware/js-routes because `coffee_routes` is 

`NOTICE: CoffeeRoutes is now unmaintained, I recommend the excellent JsRoutes instead.`

**Comment by ivanamihalek** [comment]
Thanks @ajahongir. I was hoping to avoid it because  it would force me to 1) mix coffeescript and javascript, and 2) use a rather clunky solution of reading the root url from env variable in the assets precompilation step. Can it (the root url) be made available somewhere in the ajax-datatables-rails setup?

**Comment by ajahongir** [comment]
@ivanamihalek  sorry too late answer. I thing in this case its easy to updating gem from coffee_routes to JsRoutes.

I recently have updated how-to project. so I moved to rails 5 and js-routes.

**Comment by ivanamihalek** [comment]
Thank you, @ajahongir I migrated my project to js-routes following your how-to example and it works nicely. Thanks!

**Comment by ajahongir** [comment]
sounds good. you can close issue if its solved.
