### ISSUE TITLE
Child records count search filter 

### ISSUE THREAD

**Issue by vivek-nga** [jbox-web/ajax-datatables-rails#178]
Hi,
I have the model called Event and having child events with self-association I want to implement the advanced filter like show event having child event greater than 2 etc. 
I only displayed the parent record.
 def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= %w(PreStagingEvent.name PreStagingEvent.description PreStagingEvent.start_date )
  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= %w(PreStagingEvent.name PreStagingEvent.description PreStagingEvent.start_date )
  end

def get_raw_records
    PreStagingEvent.includes(:child_events).where("parent_id is NULL and start_date >= ?", Time.now)
  end

Please help how I can define searchable column
Thanks
Vivek

**Comment by ajahongir** [comment]
not sure is this possible on 0.3.x version @antillas21 

I recommend to use v-0-4-0 branch.
in this case you have to do:

``` ruby
def view_columns
  @view_columns ||= {
    id: { source: "PreStagingEvent.id", cond: :eq },
    name: { source: "PreStagingEvent.name", cond: :like },
    start_date: { source: "PreStagingEvent.start_date", cond: :gteq },
    description: { source: "PreStagingEvent.description", cond: :like },
    children_count: { source: "children_count", cond: children_count },
  }
end

def get_raw_records
    PreStagingEvent.select('pre_staging_events.*, (select count(*) from pre_staging_events AS pse where pse.parent.id = pre_staging_events.id) AS children_count').where("parent_id is NULL and start_date >= ?", Time.now)
  #or if you want to fixed filtering
  # you can add .where('children_count > 2') condition
end

def children_count
  ->(column) { column.table[column.field].eq(column.search.value) }
end
```

**Comment by vivek-nga** [comment]
Hi, 
Thanks for the help It looks like that I want.
Another problem I faced when I pull the branch 
gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'v-0-4-0'

I faced the following error

initializers/ajax_datatables_rails.rb:6:in `block in <top (required)>': undefined method`paginator=' for #AjaxDatatablesRails::Configuration:0x007fc3a0483210 (NoMethodError)

initializers/ajax_datatables_rails.rb
AjaxDatatablesRails.configure do |config|
  # available options for db_adapter are: :oracle, :pg, :mysql2, :sqlite3
  config.db_adapter = :pg

  # available options for paginator are: :simple_paginator, :kaminari, :will_paginate
  config.paginator = :kaminari
end

Thanks
Vivek

**Comment by ajahongir** [comment]
well, you shoulnot set a paginator in latest version, so remove config.paginator = :kaminari line

here is how-to project on rails 5 if you interest - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/tree/master/app

**Comment by vivek-nga** [comment]
Hi,
I got error after updating the above gem
pre_staging_event_datatable.rb file

```
class PreStagingEventDatatable < AjaxDatatablesRails::Base
def_delegator :@view, :link_to
  def_delegator :@view, :admin_pre_staging_event_path
  def_delegator :@view, :admin_pre_staging_event_child_events_path
  def_delegator :@view, :local_time

  def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= []

  end

  def searchable_columns
    # Declare strings in this format: ModelName.column_name
    @searchable_columns ||= []
  end

  def view_columns
    @view_columns ||= {
      id: { source: "PreStagingEvent.id", cond: :eq },
      name: { source: "PreStagingEvent.name", cond: :like },
      start_date: { source: "PreStagingEvent.start_date", cond: :gteq },
      description: { source: "PreStagingEvent.description", cond: :like },
      harmonize_venue_address: { source: "PreStagingEvent.harmonize_venue_address", cond: :like },
      children_count: { source: "children_count", cond: children_count },
    }
  end




  private

  def data
   records.map do |record|
    [
      record.name,
      record.description.try(:truncate_words, 22),
      local_time(record.start_date),
      record.harmonize_venue_address,
      record.child_events_source(record),
      record.children_count,
      action_links(record)

    ]
    end
  end

  def get_raw_records
    # PreStagingEvent.includes(:child_events, :external_links).where("parent_id is NULL and start_date >= ?", Time.now)
    PreStagingEvent.includes(:external_links, :child_events).select('pre_staging_events.*, (select count(*) from pre_staging_events AS pse where pse.parent_id = pre_staging_events.id) AS children_count').where("parent_id is NULL and start_date >= ?", Time.now)
  end


  def children_count
  ->(column) { column.table[column.field].eq(column.search.value) }
  end
```

I got the following error 
NoMethodError (undefined method `and' for nil:NilClass
pre_staging_events_controller.rb:9:in`index'

in my controller

```
respond_to do |format|
      format.html
      format.json { render json: PreStagingEventDatatable.new(view_context) }
    end
```

Now I got

NoMethodError (undefined method `[]' for nil:NilClass):

```
app/datatables/pre_staging_event_datatable.rb:36:in `data'
app/controllers/admin/pre_staging_events_controller.rb:11:in `block (2 levels) in index'
app/controllers/admin/pre_staging_events_controller.rb:9:in `index'
```

**Comment by vivek-nga** [comment]
Hi,
Its working now I took the mistakes in columns definition.

def view_columns
    @view_columns ||= {
      '1': { source: "PreStagingEvent.id", cond: :eq },
      '2': { source: "PreStagingEvent.name", cond: :like },
      '3': { source: "PreStagingEvent.start_date", cond: :gteq },
      '4': { source: "PreStagingEvent.description", cond: :like },
      '5': { source: "PreStagingEvent.harmonize_venue_address", cond: :like },
      '6': { source: "children_count", cond: children_count },
    }
  end
