### ISSUE TITLE
Add support for Mongo DB

### ISSUE THREAD

**Issue by D3xx73r** [jbox-web/ajax-datatables-rails#18]

**Comment by antillas21** [comment]
I'm pretty sure that [these are the methods](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L59-L105) that need to be overriden in an `AjaxDatatablesRails::Extensions::Mongoid` and `AjaxDatatablesRails::Extensions::MongoMapper`.

Please confirm.

**Comment by D3xx73r** [comment]
Indeed, those are the methods that we'll need to override for this implementation.

**Comment by exocode** [comment]
has someone tried to solve this?

**Comment by antillas21** [comment]
I remember that @ianrgz was set to work on this. Though I haven't received any comments from him.

I can set some time next week to work on solving this, or if you want to take a shot at it, you're more than welcome to do so :smile:

**Comment by exocode** [comment]
I am new on programming gems. Mostly forking them with tiny edits. If you can do this, I feel much better :-)

**Comment by D3xx73r** [comment]
Sorry for not getting back sooner, I'll address this over the weekend when I get some free time.

Cheers

**Comment by antillas21** [comment]
:thumbsup:

**Comment by rameshtyaga** [comment]
I thing this is really interesting feature.
@antillas21 is this completed ? @ianrgz if you need any assistance i am ready to work with you.

**Comment by antillas21** [comment]
@trkrameshkumar would you like to start working on this feature? All help is welcome :smile: 

If you are interested, and think you need any help to plan the feature, please let me know, so we can make this happen.

Thanks for your interest and contributions.

**Comment by rameshtyaga** [comment]
@antillas21 off-course i am interested,  let me analyse the gem first,  and i will come up with my requirement to build this feature.

**Comment by rameshtyaga** [comment]
@antillas21 i just started working on this, will give PR, on this week end.

**Comment by rameshtyaga** [comment]
Hi @antillas21 , unfortunately i was unable to complete this by this week end,but i am sure i can complete this by next week , so please bear with me.

**Comment by antillas21** [comment]
@trkrameshkumar don't worry... contributing to open source, is not precisely a "mandatory" job, development should be more relaxed :wink:

**Comment by rameshtyaga** [comment]
@antillas21 thanks for your understanding.

**Comment by matbox** [comment]
Any progress on getting support for Mongo? :-)

**Comment by antillas21** [comment]
No progress yet... we've been reworking the gem internals to allow to build this, but there hasn't been any work done on this front... would you be interested to contribute @matbox?

**Comment by n-rodriguez** [comment]
See https://github.com/jbox-web/ajax-datatables-rails/commit/7e92f7b3e635d30ad096772cdb25e1eb0b552fa5

**Comment by n-rodriguez** [comment]
Duplicate https://github.com/jbox-web/ajax-datatables-rails/issues/110
