### ISSUE TITLE
When using with mysql2 adapter , ajax data-tables wont show data without refreshing .

### ISSUE THREAD

**Issue by AyanSaha** [jbox-web/ajax-datatables-rails#180]
I have view page with ajax data table set up.When I redirect to the particular page,I see no data.But on refresh of the page everything works fine.

**Comment by antillas21** [comment]
db adapters and data display are not related issues... this looks like a
conflict with turbolinks, if you have turbolinks enabled this is something
that will happen if you haven't written your js calls with turbolinks page
loading events in mind... please refer to turbolinks documentation about
the available page events.

**Comment by ajahongir** [comment]
@AyanSaha any errors on page loading? is  request sending to server?
