### ISSUE TITLE
colspan por multiple actions on the same column

### ISSUE THREAD

**Issue by thalesmiguel** [jbox-web/ajax-datatables-rails#181]
Is it possible to apply a colspan="3" (for example), so that I can put my edit, show and delete actions on the same column?
As of today, I can set those actions on different <th> or pass a block as

```
[
  record.item,
  ...
   [
     link_to('edit', edit_path(record),
     link_to('delete', record, method: :delete)
   ]
]
```

Using this second approach, I almost get the result I want but my links are separated with a comma (,).

A fiddle to illustrate: [fiddle](https://jsfiddle.net/fmwemb00/)

**Comment by ajahongir** [comment]
@thalesmiguel You can add these action links on client side:
```coffeescript
$ ->
  $('#dataTable').dataTable
    ajax: Routes.cities_path()
    columns: [
        data: "id"
      ,
        data: "name"
      ,
        data: "iata"
      ,
        data: "custom_column"
      ,
        data: null
        render: (record)->
          "<a href='#{record.url}'>edit</a> <a href='#{record.url}'>remove</a>"
    ]
```

**Comment by thalesmiguel** [comment]
Thank you very much for your reply.
As I was struggling with this question, I've came up with another solution:

**EDIT: 
This does not work with pagination or search methods form DataTables. Please disregard.**

> _datatable.rb

```
[
  record.item,
  ...
   [
     <div class="actions">,
       link_to('edit', edit_path(record),
       link_to('delete', record, method: :delete),
     </div>
   ]
]
```

> .js

```
  $('#table').dataTable({
    "initComplete": function(settings, json) {
      $(".actions").html($(".actions").html().replace(/,/g, ' '));
    }
  });
```

I'm giving a Class for all my Actions and then, after rendering the Datatables, I'm using Javascrip to remove the commas.
Hope this issue helps someone else eventualy.

**Comment by ajahongir** [comment]
well, It will work but its not recomended way for ajax-datatable gem and datatables.net lib.
for datatables.net render event is convertion event to render custom content.

**Comment by thalesmiguel** [comment]
You are right.
Turn out, you can use strings to define Data inside de "_datatable.rb" file.
This is working fine for me (although it's kind of ugly code):

```
[
  record.item,
  ...
  "#{ link_to('edit', edit_path(record) }" "#{ link_to('delete', record, method: :delete) }"
]
```

This way, I don't neet to make any other changes and I can keep more ruby code.
