### ISSUE TITLE
scope with current user

### ISSUE THREAD

**Issue by luis77** [jbox-web/ajax-datatables-rails#184]
I am trying to use a scope that relates to the current user but for some reason it gives me error, it is not possible to use the current user in this method?  

This is the scope in the model
  scope :por_empresa, ->(user_id) { where(IdEmpresa: user_id) } # model

this is the method in cliente_datatable.rb
  def get_raw_records
    Cliente.activos.por_empresa(current_usuario.empresa_id)
  end

and I get this error:
```
NameError (undefined local variable or method `current_usuario' for #<ClienteDatatable:0xb386a7c8>):
  app/datatables/cliente_datatable.rb:39:in `get_raw_records'
  app/controllers/clientes_controller.rb:10:in `block (2 levels) in index'
  app/controllers/clientes_controller.rb:8:in `index'

```

**Comment by ajahongir** [comment]
you can pass current_user as option. you can find more info here - https://github.com/antillas21/ajax-datatables-rails#options
