### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by Manju244** [jbox-web/ajax-datatables-rails#186]
I have array of hashes which is stored in Redis. Now I want to access this data as below,

`def get_raw_records
  users = JSON.parse $redis.get("users")
end`

I have read the document and it's saying we need to return an ActiveRecord::Relation object. How we can achieve result using redis? or Is their any other way to achieve the result?

**Comment by ajahongir** [comment]
may its to late. Iam not sure than you can use this. because this gem for right now supports only ORM. databases.
I heard that someone working on mongo and other no sql databases supporting but It seems that it not ready yet.

**Comment by austinarchibald** [comment]
I also second Redis support! That will make this nice and speedy.
