### ISSUE TITLE
Enum columns and how to search them

### ISSUE THREAD

**Issue by thalesmiguel** [jbox-web/ajax-datatables-rails#191]
I can't seem to make the Enum columns to work.
The labels are only in the Rails application and not in the database... This way, filtering on these columns does not work as expected.
Is there a way to make this work?

Thanks in advance.

**Comment by ajahongir** [comment]
I gues you are passing labels to client side instead of sending enum number. you have to pass number value and on clients side do something like: 
```javascript
 if(user.status == 1) { 'active' } else { 'disabled' }
```

**Comment by thalesmiguel** [comment]
So I hava to send de INT value from my _datatable.rb and, via Javascript, I have to take that value and change de label?
By doing so, won't the INT value overlap my changed label after sorting or searching?

**Comment by ajahongir** [comment]
```
$('#example').dataTable( {
  "columnDefs": [ {
    "targets": 4,
    "data": "status",
    "render": function ( status ) {
      return if(status == 0) { 'active'} else { 'not active'}
    }
  } ]
} );
```

this should work

**Comment by thalesmiguel** [comment]
Nice!!!
Is there a way to set this inside my ruby class (AjaxDatatablesRails)?

**Comment by ajahongir** [comment]
sure, here is sample project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

use custom search and order - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb#L7

**Comment by thalesmiguel** [comment]
That is awesome! Thank you very much @ajahongir!
As you described, I just had to make a custom search.
As for my case:

```
def view_columns
  @view_columns ||= {
    type: { source: "User.type", cond: filter_user_type }
  }
end

###

def filter_user_type
  ->(column) { ::Arel::Nodes::SqlLiteral.new(column.field.to_s).matches("#{ User.types[column.search.value] }") }
end
```

**Comment by DavidMoritz** [comment]
Thank you guys so much! This was a terrific resolution! I just thought I'd add my small tweak as well.

For my purposes, I had a lot of enum values, and I wanted to be able to search for parts of the value as well. I ended up creating another method that did just that, then used `in` instead of `matches`:

```
def find_enum_list(search)
  foundArray = []
  Model.enums.each do |enum, i|
    if enum.downcase.include? search.downcase
      foundArray << i
    end
  end
  foundArray
end

def filter_enum_condition
  ->(search) { ::Arel::Nodes::SqlLiteral.new('enum_column_name').in(find_enum_list(search)) }
  # ->(dt, search) { ::Arel::Nodes::SqlLiteral.new('enum_column_name').in(find_enum_list(search)) }
  # Some searches pass in two values.
end
```
