### ISSUE TITLE
Getting a PG UndefinedColumn retrieving a table with lots of columns

### ISSUE THREAD

**Issue by afxjzs** [jbox-web/ajax-datatables-rails#196]
I've posted this to [StackOverflow here](http://stackoverflow.com/questions/42379478/postgresql-error-on-heroku-with-ajax-datatables-gem-works-100-on-local-pg-db) that has a much more complete description.

Whenever I try to use this gem on our `Events` table, i get this error:
```
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column events.["user", "venue", "client", "booking", "sales_person", "event_m does not exist 
LINE 1: ...nfo" AS t0_r99, "events"."shoot_type" AS t0_r100, "events"."... 
```

It looks like there's a limit to the length of the query or something. `event_m` is part of the string `event_manager`, where `Event` `belongs_to` an `:event_manager, class_name: "User", foreign_key: "event_manager_id"`

This seems to work fine on my localhost, but not on heroku. I've used this gem successfully on other tables, it's only this one that is causing issues. 

Any help is much appreciated. Thanks!

**Comment by n-rodriguez** [comment]
Hi there! Any news? It would be nice to have the full query if you can achieve to get it.

**Comment by n-rodriguez** [comment]
https://dba.stackexchange.com/questions/131399/is-there-a-maximum-length-constraint-for-a-postgres-query?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
