### ISSUE TITLE
Sorting and order field integer

### ISSUE THREAD

**Issue by alessiovaralta** [jbox-web/ajax-datatables-rails#197]
Hi, I use this gem in my project but when I have a table with integer fields and I try to oreder or serachable these field I have an error on the casting. There is a solution?

**Comment by hendranata** [comment]
yes i also face the same problem..
how do we do shorting in field integer/number?

they assume all are string even the content is number

**Comment by ajahongir** [comment]
you can always use custom search - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb#L35

**Comment by hendranata** [comment]
do u have another example there?
we cant use ->(column) {  xxxxxxxxxxxx }

**Comment by ajahongir** [comment]
well, column is  https://github.com/ajahongir/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/datatable/column.rb object so you can use it.
in block arel expression here is example https://github.com/ajahongir/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/datatable/column.rb#L88
for mere details look at docs https://github.com/rails/arel

**Comment by hendranata** [comment]
i have found solution..
using mysql.

def sortable_columns
    # Declare strings in this format: ModelName.column_name
    @sortable_columns ||= ['Location.name','Location.latitude', 'Location.longitude', 'ABS(locations.radius)', 'Location.description']
  end



ABS(locations.radius) will short in integer manner

**Comment by ajahongir** [comment]
it seams you are using old version 0.3.x
my example was for 0.4 branch

**Comment by alessiovaralta** [comment]
I use rails 3.2 I try to use the solution of  @hendranata this work for @sortable_columns (ps. many thanks), but I think is not a standard solution for the gem. For example in my application for 
@sortable_columns I use this format

Easw::People::Person.fname this work in @sortable_columns
but your solution for 'ABS(Easw::People::Person.ncode)' not working I have to change in 
'ABS(easw_people_people.ncode)'

So maybe is not standard.
The solution of @hendranata not working for @searchable_columns because there is an error wrong constant name ABS(locations.radius). @ajahongir your solution work for rails 3.2?

**Comment by alessiovaralta** [comment]
Any solution for searchable_columns integer in rails 3.2?
