### ISSUE TITLE
XSS posibility

### ISSUE THREAD

**Issue by johan-smits** [jbox-web/ajax-datatables-rails#199]
When returning the data trough the json it should be html escaped.
During a security audit we found that a string with:
```html
Name "><img src=x onerror=alert("XSS")>
```
Will show an alert image. We solved it now by escaping the result but it should be done my the library?

Our quick fix is:
```ruby
def data
    begin
      records.map do |record|
        [
            html_escape(record.name),
...
```

**Comment by dillonhafer** [comment]
This is what I am experiencing as well, it is opposite the rails convention of escaping by default in views.

**Comment by ajahongir** [comment]
>>We solved it now by escaping the result but it should be done my the library?

well, for every datatable you create, you have to define and handle each field by yourself. lib does not do that.
you have to override data method for every your datatable.

**Comment by dillonhafer** [comment]
I fixed mine with a monkey-patch:

```ruby
class AjaxDatatablesRails::Base
  def as_json(options = {})
    {
      :draw => params[:draw].to_i,
      :recordsTotal =>  get_raw_records.count(:all),
      :recordsFiltered => filter_records(get_raw_records).count(:all),
      :data => sanitize(data)
    }
  end

  private

  def sanitize(data)
    data.map do |record|
      record.map do |td|
        ERB::Util.html_escape(td)
      end
    end
  end
end
```

**Comment by n-rodriguez** [comment]
Fixed : https://github.com/jbox-web/ajax-datatables-rails/commit/888b281ee08de0be037583cd5ffde4d910964905
Thank you!

**Comment by ikaul** [comment]
How can I make sure that one of the columns data does not get escaped. 
I wanted to add a <td>row1<br/>row2<br/>row3<br/></td>. 
If I add the data as a array, it show the [].

**Comment by dillonhafer** [comment]
Mark the column as `#html_safe`

**Comment by zenzei** [comment]
Hi @n-rodriguez, this fix is breaking a use case I had, where i was setting the attribute 'DT_RowAttr' in the record with a Hash to style my datatable rows. Now is escaping the hash so the styling doesn't work.
I think at least the sanitize method should not be private so we know that maybe we will need to override it.
