### ISSUE TITLE
Is there a way to allow sort by relationship count?

### ISSUE THREAD

**Issue by makotogitdev** [jbox-web/ajax-datatables-rails#200]
Is there a way to allow sort by relationship count? Should I just make use of `counter_cache` feature in Rails?

Hers's a very simple example. I want to be able to to sort by the number of comments for Post. Obviously, I would get an error if I added `Post.comments.size` inside `sortable_columns` since that column doesn't exist in the db. Is there a workaround for this? I tried using left outer join and include a count column for `#get_raw_records`, but I am just not sure what/where I need to change.

```ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class Comments < ActiveRecord::Base
  belongs_to :post
end
```
```ruby
class PostListDataTable < AjaxDatatablesRails::Base
  def sortable_columns
    # TBD
  end

 private

  def data
    records.map do |record|
      [
        record.title,
        record.comments.size.
      ]
    end
  end

  def get_raw_records
    current_user.posts
  end
end
```

**Comment by ajahongir** [comment]
https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by whatch** [comment]
There's nothing in that how to app that approaches an answer to this question.

**Comment by arlenmendes** [comment]
I did it this way:

```
def get_raw_records
    PlayList.joins(:podcasts).select('play_lists.*, count(podcasts.id) as count_podcasts').group('play_lists.id')
  end
```

And added count_podcasts in sortable column. I hope its helps.
