### ISSUE TITLE
Ordering issues

### ISSUE THREAD

**Issue by Svashtar** [jbox-web/ajax-datatables-rails#202]
Hi,

i have these two models:

**User**
```
has_one  :teacher_department,     class_name: "Department", foreign_key: "class_teacher_id"
has_many :substitute_departments, class_name: "Department", foreign_key: "class_substitute_teacher_id"
```

**Department**
```
belongs_to :class_teacher, class_name: 'User', foreign_key: "class_teacher_id"
belongs_to :class_substitute_teacher, class_name: 'User', foreign_key: "class_substitute_teacher_id"
```

Then in departments_controller something like this:
`apply_scopes(Department).includes(:class_teacher).references(:user)`

The problem I am having is:

- when i don't define includes/references i can't sort/search by this two columns
- when i have includes/references, then i somehow can't access user attribute

My data definition is something like this:
```
records.map do |record|
  row = []
  row.push(
    ...
    record.class_teacher.try(:surname),
    record.class_substitute_teacher.try(:surname),
    ...
  )
end
```

By "access attribute" i mean it return empty, so there is no value returned, and again i can't do sorting (or maybe it does sort but i can't see values).

What am i doing wrong here?
Are models problematic or maybe controller or datatable?

Rails 5

**Comment by ajahongir** [comment]
hey, wich version are you using now and can I have full database.rb?

**Comment by Svashtar** [comment]
I am using 0.3.1.
database.rb? Do you mean datatable for department?

**Comment by Svashtar** [comment]
Anything new? Did you have a look at the file i've sent you? Thx
