### ISSUE TITLE
Datatables Server Side + YADCF only shows current page data on filter

### ISSUE THREAD

**Issue by thalesmiguel** [jbox-web/ajax-datatables-rails#203]
Hello.

I have this datatables with a lot of data and, when I try to filter it with a select filter, not all data is shown:
![1](https://cloud.githubusercontent.com/assets/1305223/23922300/959256dc-08e0-11e7-86f6-ac5f224c3dc3.png)

It only shows values that are currently being shown on the datatables:
![2](https://cloud.githubusercontent.com/assets/1305223/23922306/983dde6a-08e0-11e7-8d11-574148a60ad5.png)

As I'm using `serverSide: true`, I should provide yadcf with all the data from the start so it can make the filters.
Has anyone ever did that?
I don't know where I should do this.

Thanks in advance.

**Comment by ajahongir** [comment]
It seams you are using local data filtering

**Comment by thalesmiguel** [comment]
As for my code, I'm doing this:

Build an array with my fields
```
  let yadcf_campos = []
  $.each(campos, function( index, value ) {
    yadcf_campos.push({column_number: index, filter_reset_button_text: false, style_class: 'browser-default', filter_default_label: 'Filtrar'})
  });
```
Initialize the datatables (server side)
```
var tabela = $(table).DataTable({
  processing: true,
  serverSide: true,
  stateSave: true,
})
```
call yadcf
```
yadcf.init(tabela, yadcf_campos);
```

"It seams you are using local data filtering"
How do I change that?

**Comment by pawlarius** [comment]
got same problem :(
did you find the solution yet? @thalesmiguel

**Comment by ajahongir** [comment]
@thalesmiguel  how do you connect with server side? I dont see any urls

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails#additional-data

**Comment by n-rodriguez** [comment]
```ruby
def additional_data
  {
    yadcf_data_3:  select_options_for_boolean,
    yadcf_data_4:  select_options_for_users,
  }
end

def select_options_for_boolean
  [
    { value: 1, label: t('text.yes') },
    { value: 0, label: t('text.no') },
  ]
end

def select_options_for_users
  User.all.map { |object| { value: object.id, label: object.to_s } }
end
```
Yadcf use column id instead of column name to do the mapping between the select box and the column, so you must use : "yadcf_data_<column_id>" as key.
