### ISSUE TITLE
Only load 10 first records

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#204]
So i use monologue for rails, and want to show all posts from monologue by datatables ajax.
Datatable already run, default search and pagination showing correct number. Ajax files showing. but only load 10 first records, while i already specify to load all in method get_raw_records.

Pagination showing all same first 10 records, sorting and filtering doesnt work, only refreshing the data.. when click on another page in datatables,console already showing the correct parameters.. i think because somehow it only load 10 first records to datatables..

I use
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
gem 'ajax-datatables-rails'

datatables js coffee, "#blog_post" is my datatable id
![screen shot 2017-04-21 at 12 35 16 am](https://cloud.githubusercontent.com/assets/27823957/25244339/7adb87c0-262a-11e7-91c3-78707150a222.png)

post_datatables.rb :
![screen shot 2017-04-21 at 12 31 52 am](https://cloud.githubusercontent.com/assets/27823957/25244195/f2571c3e-2629-11e7-9eca-8679f34a66e9.png)
i must use "Monologue::Post" or it wont recognize the model, i tried change the sortable_columns and searchable_columns model name with something like this :
@sortable_columns ||= ['Monologue::Post.title'], but it still wont work

model Post column names :
![screen shot 2017-04-21 at 12 34 02 am](https://cloud.githubusercontent.com/assets/27823957/25244300/4fafe30c-262a-11e7-9a12-a2a3ce8bbdb9.png)

rails log when load the ajax datatable page :
![screen shot 2017-04-21 at 12 29 53 am](https://cloud.githubusercontent.com/assets/27823957/25244360/988b0c64-262a-11e7-9d9a-a3a8ef6dc0ef.png)

when click on number 2 page for ajax datatables (parameters changing but still showing the same first 10 records ) : 
![screen shot 2017-04-21 at 12 30 19 am](https://cloud.githubusercontent.com/assets/27823957/25244374/a58bd3da-262a-11e7-87c8-e633220a291c.png)

where did i go wrong :(

**Comment by ajahongir** [comment]
take a look here - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by pawlarius** [comment]
i already saw that but still cant find what is wrong ;(
what are u suggesting? @ajahongir

**Comment by ajahongir** [comment]
@Pawlarius  well, it seams you are using an old version, you have to use branch [0-4.](https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0) on latest version searching and ordering will work outofbox.

**Comment by pawlarius** [comment]
upgrading my gem to gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0', cause this error :") 

@ajahongir 
![screen shot 2017-04-21 at 12 16 09 pm](https://cloud.githubusercontent.com/assets/27823957/25263795/5b91749e-268c-11e7-828e-162410cbef3f.png)

**Comment by ajahongir** [comment]
at new version syntax has changed, please try to use as described here https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0 or 
https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb

**Comment by pawlarius** [comment]
oh my god, it works !
thankyou so much 👍

**Comment by Pawlarius** [comment]
oh my god, it works !
thankyou so much 👍
