### ISSUE TITLE
search return mysql error

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#205]
after upgrading gem to
gem 'jquery-datatables-rails'
gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0'

load the ajax file cause this error: 
![screen shot 2017-04-21 at 1 21 25 pm](https://cloud.githubusercontent.com/assets/27823957/25265105/726279c6-2695-11e7-99f6-c1a8add8477a.png)

this is my post_datatable.rb
![screen shot 2017-04-21 at 1 22 45 pm](https://cloud.githubusercontent.com/assets/27823957/25265140/a5e38542-2695-11e7-85e0-6f8e2c9c8b60.png)

my js.coffee to init
![screen shot 2017-04-21 at 1 23 41 pm](https://cloud.githubusercontent.com/assets/27823957/25265167/c7536e54-2695-11e7-9338-d2a3a20bfee7.png)

using gem gem 'ajax-datatables-rails' only ( ver 0.3)
can load the view but every time i input word to searchbox it return error alert,
![screen shot 2017-04-21 at 1 10 29 pm](https://cloud.githubusercontent.com/assets/27823957/25265201/083087cc-2696-11e7-9aa5-2600d9a38761.png)
![screen shot 2017-04-21 at 1 09 32 pm](https://cloud.githubusercontent.com/assets/27823957/25265202/093ff08a-2696-11e7-9b56-3e89a26f06f3.png)

pls help !

**Comment by ajahongir** [comment]
well, there are 2 way connecting client side fields with server side(db) fields.
1. by field order 0,1,2....
2. by name. 


1st you have to:
```ruby
@view_columns ||= [
      { source: "City.id", cond: :eq },
      { source: "City.name" },
      { source: "custom_column", cond: filter_custom_column_condition },
      { source: "City.iata" },
      .....
    ]
```

2. 
```ruby
@view_columns ||= {
      id: { source: "City.id", cond: :eq },
      name: { source: "City.name" },
      custom_column: { source: "custom_column", cond: filter_custom_column_condition },
      iata: { source: "City.iata" },
      country_name: { source: "City.country_id", cond: filter_country_condition },
    }
```
```coffeescript
      $('#dataTable').dataTable
        ajax: Routes.cities_path()
        columns: [
            data: "id"
          ,
            data: "name"
          ,
            data: "iata"
          ,
            data: "custom_column"
          ,
            data: "country_name"
        ]
```

1st way is not good - if you change an order of columnd on client side, your connection will broke.
2nd way is more stable and preffered because you connect by name

**Comment by ajahongir** [comment]
you can always look up to an example - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by pawlarius** [comment]
using 2nd way still return the same error :(
![screen shot 2017-04-21 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/27823957/25266496/8524e1c4-269b-11e7-820c-a8e0308485d2.png)

i already look up to that example..
![screen shot 2017-04-21 at 2 03 35 pm](https://cloud.githubusercontent.com/assets/27823957/25266497/862b6624-269b-11e7-9c6d-a3736ec0baa7.png)
![screen shot 2017-04-21 at 2 06 57 pm](https://cloud.githubusercontent.com/assets/27823957/25266603/ea5f74b4-269b-11e7-87e0-7e9adcdfbbf7.png)

**Comment by pawlarius** [comment]
okay , i managed to show ajax datatables with
gem 'jquery-datatables-rails'
gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0'

but still searching doesnt work,  while pagination and sorting works well..
![screen shot 2017-04-21 at 2 41 28 pm](https://cloud.githubusercontent.com/assets/27823957/25267859/b00e9ee8-26a0-11e7-9313-b4307f567378.png)
![screen shot 2017-04-21 at 2 41 54 pm](https://cloud.githubusercontent.com/assets/27823957/25267863/b4baf5d6-26a0-11e7-8e81-7fb3732e8fe1.png)

i follow ur suggestion like this..
![screen shot 2017-04-21 at 2 39 57 pm](https://cloud.githubusercontent.com/assets/27823957/25267874/c294602a-26a0-11e7-9462-b243477d3853.png)
![screen shot 2017-04-21 at 2 43 29 pm](https://cloud.githubusercontent.com/assets/27823957/25267920/edb706a4-26a0-11e7-995c-b5ad562986e9.png)

**Comment by ajahongir** [comment]
try to commentout line 8 in PostDatatable file.

**Comment by pawlarius** [comment]
tried that and still return the same error..
![screen shot 2017-04-22 at 12 52 04 am](https://cloud.githubusercontent.com/assets/27823957/25289938/f176a150-26f5-11e7-8b27-89b651c9b21c.png)

**Comment by ajahongir** [comment]
well you are having typecast error, for some reason published-at not converted to datetime

**Comment by ajahongir** [comment]
by default all fields as a string so it uses CAST function - https://github.com/antillas21/ajax-datatables-rails/blob/v-0-4-0/lib/ajax-datatables-rails/datatable/column.rb#L89

I think you have to override with custom searching as here https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb#L9

**Comment by ajahongir** [comment]
or you can turn of searching for these fields. by passing searchable: false, orderable: false on column connection

**Comment by pawlarius** [comment]
i tried add searchable: false, orderable: false on other fields, but still return same error..
also somehow i still can do sort on those fields..

![screen shot 2017-04-22 at 1 42 51 am](https://cloud.githubusercontent.com/assets/27823957/25291729/7936a200-26fd-11e7-8642-47816926839f.png)
![screen shot 2017-04-22 at 1 43 34 am](https://cloud.githubusercontent.com/assets/27823957/25291730/7a1abd8c-26fd-11e7-8378-094d617690a4.png)

**Comment by pawlarius** [comment]
btw i tried removing all fields except the title field and still got the same varchar error..
![screen shot 2017-04-24 at 1 53 32 pm](https://cloud.githubusercontent.com/assets/27823957/25325371/77be12d8-28f5-11e7-8e69-92c8eccdb54c.png)

here my current 
![screen shot 2017-04-24 at 1 54 12 pm](https://cloud.githubusercontent.com/assets/27823957/25325414/a6b4fbba-28f5-11e7-904e-76eab801e7b5.png)
![screen shot 2017-04-24 at 1 54 54 pm](https://cloud.githubusercontent.com/assets/27823957/25325415/a6b85b84-28f5-11e7-9d5f-ccbd8446c08c.png)

why am i getting these errors :(

**Comment by pawlarius** [comment]
okay i found out how to solve it..
read your documentation and other issues, found out i need to set the initializer generator to mysql2 so the varchar error when searching is solved !
thankyou for your work and time, sorry to bother so much :")
