### ISSUE TITLE
Pass param to controller

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#209]
How to pass parameter from form in datatable.rb?
![screen shot 2017-04-25 at 11 11 18 am](https://cloud.githubusercontent.com/assets/27823957/25368627/eefd531a-29a7-11e7-942e-383706babcbd.png)

I keep getting error : undefined method `[]' for nil:NilClass
I checked the params somehow always return to nil

Is there any specific way to pass params in this?
i tried https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65872592

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/tree/v-0-4-0#options

**Comment by pawlarius** [comment]
im sorry,could you be more exact ? kinda confused ..

i tried this in my post_datatable.rb
![screen shot 2017-04-25 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/27823957/25374069/426e3cda-29c6-11e7-918b-73004380d1a0.png)

and got this undefined method error..
![screen shot 2017-04-25 at 2 47 49 pm](https://cloud.githubusercontent.com/assets/27823957/25374086/534b8d1e-29c6-11e7-8efa-82cca3444477.png)

**Comment by pawlarius** [comment]
@ajahongir

**Comment by ajahongir** [comment]
well, you a tring to user view_context in datatable which is not possible becase the context is available on in controller.

**Comment by pawlarius** [comment]
@ajahongir 
i tried in controller but cause the same error 
![screen shot 2017-04-26 at 1 56 38 pm](https://cloud.githubusercontent.com/assets/27823957/25421693/334b66e8-2a88-11e7-8a32-1873b0cf706e.png)
am i doing it right..?

what im trying to do is, pass params with hidden field from method data in post_datatable.rb
![screen shot 2017-04-26 at 1 57 18 pm](https://cloud.githubusercontent.com/assets/27823957/25421716/4a1a22f6-2a88-11e7-888b-85d72cdcc1ed.png)

**Comment by hermesalexis** [comment]
You can try to do form from a helper method and add to datatable .rb file whit a delegator

**Comment by n-rodriguez** [comment]
What you want here is Rails `button_to` helper method : https://apidock.com/rails/ActionView/Helpers/UrlHelper/button_to. But anyway use it is a Draper decorator (https://github.com/drapergem/draper) so in the Datatable class you can do :

```ruby
def data
  records.map do |record|
    {
      foo: record.decorate.name
      bar: record.decorate.publish_button
    }
  end
end
```

**Comment by n-rodriguez** [comment]
BTW, remove `datatable = PostDatatable.new...` from `post_datatable.rb`.
This is how it works : https://github.com/jbox-web/ajax-datatables-rails#setup-the-controller-action

**Comment by n-rodriguez** [comment]
Also it won't work if you're using Rails in API mode : https://github.com/jbox-web/ajax-datatables-rails/issues/240
