### ISSUE TITLE
How to use rails url helpers inside data?

### ISSUE THREAD

**Issue by ricardodovalle** [jbox-web/ajax-datatables-rails#21]
There is a better and clean way to use link_to and edit inside a data than below?

```
def data
    records.map do |record|
    [
        @view.link_to(record.uid_human, @view.edit_polymorphic_path(record))
    ]
    end
end
```

Thanks

**Comment by antillas21** [comment]
Hey @ricardodovalle 

[Take a look here](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L7) to discover how we forward `:params` to the view.

You will basically will need to add something like this in your child class. Example:

``` ruby
def_delegator :@view, :link_to, :edit_polymorphic_path, :other_method_name
```

or, if you could test if the following code works... I'm pretty sure it should, as the class exists in the context of a Rails application.

``` ruby
delegate :link_to, :edit_polymorphic_path, :other_method_name, to: :@view
```

Doing this, will allow you to write the `data` method like this:

``` ruby
def data
  records.map do |record|
    [
      link_to(record.uid_human, edit_polymorphic_path(record))
    ]
  end
end
```

**Comment by antillas21** [comment]
@ricardodovalle 

I have tested my suggestions... and this is what actually worked:

``` ruby
# either delegate one-by-one
def_delegator :@view, :link_to
def_delegator :@view, :edit_polymorphic_path
def_delegator :@view, :other_method_name

# or delegate in one pass
def_delegators :@view, :link_to, :edit_user_path, :other_method_name
```

Notice the plural for delegators in the last example.

**Comment by ricardodovalle** [comment]
Hi @antillas21,

Thank you very much.
