### ISSUE TITLE
Search by translate attribute

### ISSUE THREAD

**Issue by alessiovaralta** [jbox-web/ajax-datatables-rails#210]
Hi, I have a rails 3.2 application and a table

Animals where i have a filed name..my field in database are in English but i want to search in base of the current language...I don't have the gem globalize

Is possible to make this operation without the gem globalize?

**Comment by n-rodriguez** [comment]
Hi! Sorry for the delay, I've been very busy... Well it seems very hard to do it without globalize and a decent version of Rails and of this gem, because this gem only support Rails > 4.
