### ISSUE TITLE
Filtering Error

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#211]
so i followed your example for simple filtering like this one :
![screen shot 2017-04-26 at 10 56 34 pm](https://cloud.githubusercontent.com/assets/27823957/25443939/a1c2cd0a-2ad3-11e7-8c0b-98ae7cb32c1f.png)

in my case, every option will return no matching records found,like this
![screen shot 2017-04-26 at 10 58 08 pm](https://cloud.githubusercontent.com/assets/27823957/25444107/3ade69cc-2ad4-11e7-94d0-5e19c1600310.png)
i felt like missing some step..what did i miss?

rails log:
![screen shot 2017-04-26 at 10 58 53 pm](https://cloud.githubusercontent.com/assets/27823957/25444101/36bd010a-2ad4-11e7-860a-a8082b2d8816.png)
![screen shot 2017-04-26 at 10 58 59 pm](https://cloud.githubusercontent.com/assets/27823957/25444115/40e0278e-2ad4-11e7-8790-9549217b6148.png)
![screen shot 2017-04-26 at 10 59 06 pm](https://cloud.githubusercontent.com/assets/27823957/25444124/42e8d40e-2ad4-11e7-98dc-e9bad81207ec.png)

here is my post_datatable.rb
![screen shot 2017-04-26 at 10 53 37 pm](https://cloud.githubusercontent.com/assets/27823957/25443966/b241bcea-2ad3-11e7-8acd-141138a22c0c.png)
![screen shot 2017-04-26 at 10 53 43 pm](https://cloud.githubusercontent.com/assets/27823957/25443967/b33b4594-2ad3-11e7-97de-44ee6fe9c79c.png)

my view
![screen shot 2017-04-26 at 10 53 26 pm](https://cloud.githubusercontent.com/assets/27823957/25443973/bc1018e8-2ad3-11e7-873e-67d71f6ae6b0.png)

my js.coffee
![screen shot 2017-04-26 at 10 53 12 pm](https://cloud.githubusercontent.com/assets/27823957/25443978/c3e5ecdc-2ad3-11e7-8ea0-cf4e489545b2.png)

**Comment by pawlarius** [comment]
i tried yadcf but it cause same issue like this https://github.com/antillas21/ajax-datatables-rails/issues/203

**Comment by ajahongir** [comment]
![b241bcea 2ad3 11e7 8acd 141138a22c0c png 518x617](https://cloud.githubusercontent.com/assets/625014/25445008/bdd184a0-2ab5-11e7-9be2-475b6c2476c6.png)

author: { source: '**Monologue::Post.author_id**', ....}

**Comment by pawlarius** [comment]
ah ! thankyou !
now if i do that, i will get "Mysql2::Error - Unknown column 'monologue_posts.author_id' in 'where clause':....."

**Comment by ajahongir** [comment]
user_id?

**Comment by pawlarius** [comment]
can u tell me what is happening? why user_id?
i tried that, return no error, but dont do any filtering..

**Comment by ajahongir** [comment]
> can u tell me what is happening? why user_id?

your are searching by user_id(author)

**Comment by pawlarius** [comment]
i inspect the dropdown and it is like this : post[user_id] 
should be working but wont..
current code :
![screen shot 2017-04-26 at 11 51 59 pm](https://cloud.githubusercontent.com/assets/27823957/25446328/6dfbf584-2adb-11e7-82a3-8441a4273d78.png)
![screen shot 2017-04-26 at 11 56 41 pm](https://cloud.githubusercontent.com/assets/27823957/25446530/098d511e-2adc-11e7-95bd-9a4f235f9a98.png)

found out some options can do filter correctly, some dont, some show wrong filter..
somehow it doesnt know which id is which..

**Comment by ajahongir** [comment]
well. show me you sql query on filtering

**Comment by pawlarius** [comment]
i found out why this is happening..
![screen shot 2017-04-27 at 12 08 48 am](https://cloud.githubusercontent.com/assets/27823957/25447028/b9077ed4-2add-11e7-8278-bed586acc1ba.png)

my code generate one default id, so +1 here is not needed..
after removing that, all filtering work well ! thankyou so much for your help !!

**Comment by ajahongir** [comment]
yep, it was just as an example.
