### ISSUE TITLE
Searching Value from All Column

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#212]
Hi again !
Just realised when doing searching, somehow it only search by first column (column "Title") and will return "not found" if search any value from any other column..

Here sql when search works fine for data in column "Title"
![screen shot 2017-05-02 at 12 30 47 am](https://cloud.githubusercontent.com/assets/27823957/25587631/0d3f7ac0-2ecf-11e7-956c-8646547e3604.png)

Here when searching value from other column ( when searching for value in column Author) :
![screen shot 2017-05-02 at 12 31 51 am](https://cloud.githubusercontent.com/assets/27823957/25587638/18b1403c-2ecf-11e7-92e1-f8a2494a2b09.png)

My post datatable :
![screen shot 2017-05-02 at 12 34 45 am](https://cloud.githubusercontent.com/assets/27823957/25587698/551abc06-2ecf-11e7-92bf-8e1d8e31ea14.png)
![screen shot 2017-05-02 at 12 34 52 am](https://cloud.githubusercontent.com/assets/27823957/25587699/55c299bc-2ecf-11e7-8fde-7f73a2e62a29.png)

searching for id and title still works though.. did i miss something?

**Comment by ajahongir** [comment]
well, datatables.net have 2 kind of searching and this gem also support these behaviors:
1. searching by all columns
in this way datatables sends query to a server:
`{"draw"=>"4", "columns"=>{"0"=>{"data"=>"id", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"iata", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"custom_column", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"country_name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"10", **"search"=>{"value"=>"glo", "regex"=>"false"},** "_"=>"1494228799024"}`

and on server side we handle with query like:

`SELECT  cities.*, timezone AS custom_column FROM "cities" WHERE (((("cities"."id" = 0 OR CAST("cities"."name" AS VARCHAR) LIKE '%glo%') OR custom_column LIKE 'glo%') OR CAST("cities"."iata" AS VARCHAR) LIKE '%glo%') OR "cities"."country_id" = 1) ORDER BY cities.id ASC LIMIT ? OFFSET ?  [["LIMIT", 10], ["OFFSET", 0]]
`
![v040howto ajax datatables rails 1](https://cloud.githubusercontent.com/assets/625014/25794750/fbdc3186-33da-11e7-8831-fc1f8f7d29e2.png)

2. searching by induvidual columns.

`{"draw"=>"6", "columns"=>{"0"=>{"data"=>"id", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, **"2"=>{"data"=>"iata", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"kul", "regex"=>"false"}}**, "3"=>{"data"=>"custom_column", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"country_name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"", "regex"=>"false"}, "_"=>"1494228799026"}`


`SELECT  cities.*, timezone AS custom_column FROM "cities" WHERE (CAST("cities"."iata" AS VARCHAR) LIKE '%kul%') ORDER BY cities.id ASC LIMIT`

![v040howto ajax datatables rails 2](https://cloud.githubusercontent.com/assets/625014/25794777/178149e4-33db-11e7-9cf3-a64a95e61d22.png)

**Comment by ajahongir** [comment]
@Pawlarius let me know if you have any questions

**Comment by pawlarius** [comment]
im wondering why it the search only works for some column while others not.. is there any settings need to do if i want to have searching by all columns?

**Comment by ajahongir** [comment]
you have to connect every columns in def view_columns method

**Comment by pawlarius** [comment]
![screen shot 2017-05-15 at 9 35 54 am](https://cloud.githubusercontent.com/assets/27823957/26040733/f55ad264-3951-11e7-9335-fbab1c1f0099.png)
i already connect it with this.. but still cant search other value except id and title.. @ajahongir

**Comment by jennifermaas** [comment]
So @ajahongir, is there a way to do a global search like you describe above as (1) and at the same time filter by individual columns as you describe as (2)?  I know it's possible in datatables.net https://datatables.net/examples/api/regex.html when filtering is done locally and not server side, but I can't get it to work with the gem.  When a global search term is present, the column values are ignored.

**Comment by ajahongir** [comment]
sure, take a look for an [example](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to) project I use global seach and per column search.

**Comment by jennifermaas** [comment]
I've definitely been working from your example.  Thanks for that, but I'm still not seeing the global search and column search working together.  Below are the parameters for a column search with no global search term and then a column search where a global search term is present:

1. With columns _title_ and _tempo_ given values but with no search term:
{"draw"=>"21", 
"columns"=>{"0"=>{"data"=>"details_view", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "1"=>{"data"=>"title", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"again", "regex"=>"false"}}, 
	    "2"=>{"data"=>"artist", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "3"=>{"data"=>"year_recorded", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "4"=>{"data"=>"tempo_name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"1", "regex"=>"false"}}}, 
"order"=>{"0"=>{"column"=>"2", "dir"=>"asc"}}, 
"start"=>"0", 
"length"=>"10", 
"search"=>{"value"=>"", "regex"=>"false"}, 
"_"=>"1501264079224"}

**Resulting query:** 
SELECT  `tracks`.* FROM `tracks` WHERE (CAST(`tracks`.`title` AS CHAR) LIKE '%again%' AND `tracks`.`tempo_id` = 1)  ORDER BY tracks.artist ASC LIMIT 10 OFFSET 0

2. With columns _title_ and _tempo_ given values and with search term 'arlo':
  {"draw"=>"23", 
"columns"=>{"0"=>{"data"=>"details_view", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "1"=>{"data"=>"title", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"again", "regex"=>"false"}}, 
	    "2"=>{"data"=>"artist", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "3"=>{"data"=>"year_recorded", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, 
	    "4"=>{"data"=>"tempo_name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"1", "regex"=>"false"}}}, 
"order"=>{"0"=>{"column"=>"2", "dir"=>"asc"}}, 
"start"=>"0", 
"length"=>"10", 
"search"=>{"value"=>"arlo", "regex"=>"false"}, 
"_"=>"1501264079226"}

**Resulting query:**
SELECT  `tracks`.* FROM `tracks` WHERE ((((CAST(`tracks`.`gender` AS CHAR) LIKE '%arlo%' OR CAST(`tracks`.`title` AS CHAR) LIKE '%arlo%') OR CAST(`tracks`.`artist` AS CHAR) LIKE '%arlo%') OR `tracks`.`year_recorded` = 'arlo') OR `tracks`.`tempo_id` = 0)  ORDER BY tracks.artist ASC LIMIT 10 OFFSET 0


Here is my track_datatable.rb:
https://gist.github.com/jennifermaas/6574ba08352b1a95443a47dde7c50ff8 

Do my parameters look correct to you?

I'm using the gem from github:
gem 'ajax-datatables-rails', :git => 'https://github.com/jbox-web/ajax-datatables-rails.git'

**Comment by ajahongir** [comment]
>but I'm still not seeing the global search and column search working together.

these to searching doesnt work together. and global seach is higher priority

**Comment by jennifermaas** [comment]
Okay so before I abandon ship, you are saying there is no way to search on a term and then drill down into those results more specifically?  It has to be one type of search or the other.

**Comment by ajahongir** [comment]
you can see it here https://github.com/jbox-web/ajax-datatables-rails/blob/1d89ba4598bfd16864a8b8b72ac5a055dccb7c0a/lib/ajax-datatables-rails/orm/active_record.rb#L27

**Comment by jennifermaas** [comment]
Oh I see.  Thank you!  I think I know what to do.

**Comment by ajahongir** [comment]
you have to override this method if you want to seach for both ways.

**Comment by diesl** [comment]
> So @ajahongir, is there a way to do a global search like you describe above as (1) and at the same time filter by individual columns as you describe as (2)?

This is exactly what I am looking for, too. 👍 

> > but I'm still not seeing the global search and column search working together.
>
> these to searching doesnt work together. and global seach is higher priority

Are there any plans that you will change this behaviour (or better, make it configurable) so that both global and column search parameters are considered?

Should I open a new request?

**Comment by ajahongir** [comment]
@diesl 

> So @ajahongir, is there a way to do a global search like you describe above as (1) and at the same time filter by individual columns as you describe as (2)?

now its not pissible, But I think you can override this behavior. for more info look at https://github.com/jbox-web/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/orm/active_record.rb#L27

**Comment by ajahongir** [comment]
>Should I open a new request?

I think it will usefull to others too.

**Comment by diesl** [comment]
> > Should I open a new request?
>
> I think it will usefull to others too.

Thanks for your quick response 👍 I am going to make a new request in a minute.
