### ISSUE TITLE
Part 2 The Datatables, how do you add people

### ISSUE THREAD

**Issue by whitecat** [jbox-web/ajax-datatables-rails#213]
How did you add people to the database in end of part 2?
https://github.com/antillas21/ajax-datatables-rails/wiki/Part-2-The-Datatables-with-ajax-functionality

**Comment by matissg** [comment]
You might be asking about this part:
```
private

  def data
    records.map do |record|
      [
        record.name,
        record.phone,
        record.address
      ]
    end
  end

  def get_raw_records
    User.all
  end
```
Basically you need to retrieve raw records which then basically are populated into Datatable.

**Comment by ajahongir** [comment]
hey guys. you have to take a look at [how-to](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to) project to get more details

**Comment by whitecat** [comment]
What I needed to do was do `rails db:migrate`  then do `rails db:seed`. That was the part I was missing.  

I am very new to Rails and I didn't know seed.rb existed. Now I do and step 2 is easy.

**Comment by natebird** [comment]
@whitecat can you close this issue if it is resolved? Thanks.

**Comment by whitecat** [comment]
Closed thank you
