### ISSUE TITLE
the datatable is using bootstrap, how to change the design of the table?

### ISSUE THREAD

**Issue by oscar6654** [jbox-web/ajax-datatables-rails#217]
So im changing everything to materialize. I am using http://materializecss.com/
and it have conflicts with bootstrap so I decided to turn it off. is there a way to fix the design of the datatables? This is what it looks like with bootstrap turned off
<img width="1312" alt="screen shot 2017-05-15 at 4 08 04 am" src="https://cloud.githubusercontent.com/assets/4553726/26048268/6a0d3c38-3924-11e7-9783-01999c01440f.png">

I see this on datatables.net https://datatables.net/examples/styling/material.html
how do i implement that design over?

**Comment by n-rodriguez** [comment]
Hi there! I'm sorry but this has nothing to do with this gem.

But to answer your question, as I see from the doc, you need to add 
`className: 'mdl-data-table__cell--non-numeric'` in your `columnDefs` and include some JS files :
```
//code.jquery.com/jquery-1.12.4.js
https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js
https://cdn.datatables.net/1.10.15/js/dataTables.material.min.js
```
All is in the doc : https://datatables.net/examples/styling/material.html
