### ISSUE TITLE
Confusing documentation: view_columns or sortable_columns??

### ISSUE THREAD

**Issue by nicolasconnault** [jbox-web/ajax-datatables-rails#219]
There seems to be a discrepancy between the documentation in README.md and [other sections of the documentation](https://github.com/jbox-web/ajax-datatables-rails/wiki/Part-2-The-Datatables-with-ajax-functionality), mainly around the code to write in a subclass of AjaxDatatablesRails::Base

In README.md, there is no mention anywhere of sortable_columns or searchable_columns, instead we are told to use view_columns. That's fantastic, I much prefer this design. However it doesn't work (generates a query with "ORDER BY ASC", missing column name even when several of the columns are defined as orderable: true) and conflicts with other sections of the documentation [here on github](https://github.com/jbox-web/ajax-datatables-rails/wiki/Part-2-The-Datatables-with-ajax-functionality), which fail to mention view_columns, instead referring to searchable_columns and sortable_columns.

**Comment by ajahongir** [comment]
well we have magor versions 0.3x and 0.4 and current documentation wrote for 0.3 if you are going to use 0.4 you have to follow this readme:
https://github.com/jbox-web/ajax-datatables-rails and sample project https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to

**Comment by nicolasconnault** [comment]
Thanks I understand now, but it's not clearly explained on the wiki or in the README file, and just cost me a few hours of hair-pulling (and a look at alternative gems) as a result :)
