### ISSUE TITLE
Changelog entry for 0.4.0?

### ISSUE THREAD

**Issue by sman591** [jbox-web/ajax-datatables-rails#221]
Seems like there were some breaking changes introduced in 0.4.0 (despite the [minor version](http://semver.org/) bump) - could a changelog entry be added that describes what exactly changed?

Clearly there were [a lot of changes](https://github.com/jbox-web/ajax-datatables-rails/compare/v0.3.1...v0.4.0), including dropped support for Kaminari and changes to how the datatable classes are structured.

**Comment by n-rodriguez** [comment]
> Seems like there were some breaking changes introduced in 0.4.0 (despite the minor version bump)

This is still a 0.x.x version so APi may still change (http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase). But I agree that the changelog should have been updated.
It's now done.

**Comment by sman591** [comment]
Sweet - thanks for the update! And for the semver clarification.
