### ISSUE TITLE
records in data method doesn't populate (undefined method `[]' for nil:NilClass)

### ISSUE THREAD

**Issue by stuart-bradley** [jbox-web/ajax-datatables-rails#224]
```
jquery-datatables-rails: 3.4.0
ajax-datatables-rails: 0.4.0

```
I'm just trying to implement a server side version of my datatables on an existing project, and I'm running into the following error:

```
NoMethodError (undefined method `[]' for nil:NilClass):
app/datatables/request_datatable.rb:14:in `data
```
Which is coming from `request_datatable.rb`:

```
class RequestDatatable < AjaxDatatablesRails::Base
  def view_columns
    @view_columns ||= {
       id: { source: "Request.id", cond: :eq },
       title: {source: "Request.title", cond: :like}
    }
  end

  def data
    records.map do |record|
      {
        id: record.id,
        title: record.title
      }
    end
  end

  private

  def get_raw_records
    Request.includes(:data_files, :result_files).load
  end
end
```

I know `Request.includes(:data_files, :result_files).load` returns an `ActiveRecord::Relation` so I'm a bit lost as to where I'm going wrong. I've also tried just using `Request.all`, but I'm having the same issue. 

If I modify `data` so that it uses `Request.all` directly, I don't get a rails - but the datatable has no rows.

My controller method:

```
def index
    respond_to do |format|
      format.html {
        @requests = Request.includes(:data_files, :result_files).load
        priority_modal = Request.priority_widget
        active_requests, max_length = Request.active_requests
        render locals: {
            priority_modal: priority_modal,
            active_requests: active_requests,
            max_length: max_length
        }
      }
      format.json { render json: RequestDatatable.new(view_context, { current_user: current_user }) }
    end
  end
```
View:

```
<div class="row">
  <div class="col-md-12">
    <table id="requests-table" data-source="<%= requests_path(format: :json) %>">
      <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>
```
JS:
```
$(document).ready(function() {
    $('#requests-table').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('#requests-table').data('source'),
        "pagingType": "full_numbers"
    });
});
```

Config:

```
AjaxDatatablesRails.configure do |config|
  # available options for db_adapter are: :pg, :mysql, :mysql2, :sqlite, :sqlite3
  config.db_adapter = :mysql2

  # available options for orm are: :active_record, :mongoid
  config.orm = :active_record
end
```

**Comment by stuart-bradley** [comment]
Additionally - I followed the tutorial in the readme ([here](https://github.com/jbox-web/ajax-datatables-rails/wiki/Part-1----The-Installation)) - changing it to reflect v0.4.0 - and I got the exact same error. 

I've created a repository of my tutorial attempt [here](https://github.com/lutrasdebtra/AjaxDatatablesRailsv0.4Tutorial), so you should be able to confirm the error. Hopefully, I didn't copy a user behavior between the projects and it is a real replicable error.

**Comment by jaxn** [comment]
I am upgrading an app from Rails 4.2 to 5.0.3 and am experiencing the same error.

**Comment by jaxn** [comment]
This looks to be related to #220, which reinforces #221.

**Comment by ajahongir** [comment]
well, you have to bind your columns:
```
  $('#users-table').dataTable
    processing: true
    serverSide: true
    ajax: $('#users-table').data('source')
    pagingType: 'full_numbers'
    columns: [
      {data: 'id'}
      {data: 'name'}
      {data: 'phone'}
      {data: 'address'}
    ]
```

**Comment by n-rodriguez** [comment]
Hi there! First I want to apologize for the mess introduced by the v0.4. The change is radical and can be a bit complex to manage (I will update the changelog this week-end and add some warnings). 

But shortly as @ajahongir said you have to bind your columns definitions in JS.

This is a redundant operation which can be solved by a couple of presenter objects like [these ones](https://github.com/n-rodriguez/rails-sbadmin/tree/master/app/presenters) and some [helper methods](https://github.com/n-rodriguez/rails-sbadmin/blob/master/app/helpers/common/data_tables_helper.rb).

In the view [it looks like this](https://github.com/n-rodriguez/rails-sbadmin/blob/master/app/views/admin/users/_datatable.html.haml)

You'll need some JS helpers too : https://github.com/n-rodriguez/rails-sbadmin/blob/master/vendor/assets/javascripts/datatables/factory.js.coffee.

I'd like to implement these features in the next versions of ajax-datatables-rails. What do you think?

**Comment by ajahongir** [comment]
not sure about features. We need to clearify readme

**Comment by ajahongir** [comment]
https://github.com/jbox-web/ajax-datatables-rails#wire-up-the-javascript I think we have to update this part of instrunction

**Comment by n-rodriguez** [comment]
yep ;) do you want to do it?

**Comment by ajahongir** [comment]
well, I can do this job

**Comment by n-rodriguez** [comment]
> well, I can do this job

that's not what I meant. I apologize.

**Comment by stuart-bradley** [comment]
Can confirm that adding the column definitions to `users.js.coffee` worked. My repository of the [tutorial](https://github.com/lutrasdebtra/AjaxDatatablesRailsv0.4Tutorial) is now fully functional, (feel free to use as an example). I'll take a look at @n-rodriguez's suggestions for the helper methods as well.

Thanks!
