### ISSUE TITLE
NameError - uninitialized constant AjaxDatatablesRails::Extensions:

### ISSUE THREAD

**Issue by kelnadim87** [jbox-web/ajax-datatables-rails#225]
Getting this error after upgrading to version 0.4.0

**Comment by antillas21** [comment]
version 0.4.0 removed the need for extensions... just delete the lines that
load any pagination extension and should work.

**Comment by ajahongir** [comment]
follow this [readme](https://github.com/jbox-web/ajax-datatables-rails) and [sample project](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to)

**Comment by kelnadim87** [comment]
Thanks @antillas21 removing the extensions include works.
