### ISSUE TITLE
Modifying <td> classes and styles?

### ISSUE THREAD

**Issue by stuart-bradley** [jbox-web/ajax-datatables-rails#226]
In the documentation, there is an example of how to change the `id` attribute of the `<tr>`:

```
def data
  records.map do |record|
    {
      first_name: record.first_name,
      last_name:  record.last_name,
      bio:        record.bio,
      # 'DT_RowId' => record.id, # This will set the id attribute on the corresponding <tr> in the datatable
    }
  end
end
```
Is it possible to do something similar to the  `class` and `style` attribute of the `<td>`'s related to say `first_name`? Say for example I'd like to colour all the cells in the `first_name`. 

I realize I could use `{data : 'first_name', className : 'some_class'}` in JS, but I'd like to be able to pick the class based on the data of the individual record itself. Is this possible, or should this be done with JS after loading the page?

**Comment by ajahongir** [comment]
https://datatables.net/examples/advanced_init/row_callback.html

**Comment by stuart-bradley** [comment]
Thanks for that, additionally you could use: https://datatables.net/reference/option/columns.createdCell

Which works as like so:
```
$(document).ready(function () {
    $('#requests-table').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('#requests-table').data('source'),
        "pagingType": "full_numbers",
        "columns": [
            {data: 'id'},
            {data: first_name', "createdCell": function (td, cellData, rowData, row, col) {
                if (cellData == "John") {
                    $(td).css('background-color',"#4CAE4C").css('color','white');
                }
            }},
            {data: 'last_name'},
            {data: 'bio'}
        ]
    });
```
});
