### ISSUE TITLE
<td> rendering ignores max height (Aka no vertical scroll)

### ISSUE THREAD

**Issue by stuart-bradley** [jbox-web/ajax-datatables-rails#227]
Before moving to ajax-datatables-rails (aka using jquery-datatables-rails), I was able to allow vertical scrolling in individual `<td>` cells using the following css:

```
td {
  white-space: pre-wrap;
  overflow-y: auto;
  max-height: 300px;
}
```

However, this gem seems to override this behavior somehow. I believe it ignores the `max-height` css, because if I set `overflow-y: scroll;` the scroll bars still appear (just grayed out). 

Is there a way to enable vertical scrolling in the gem?

**Comment by stuart-bradley** [comment]
So the solution to this problem is to create a `scrollable` `div` css class:
```
div.scrollable-div {
  white-space: pre-wrap;
  overflow-y: auto;
  margin: 0;
  padding: 0;
  max-height: 300px;
}
```

And then wrap your `td` content in one of these:

```
  def data
    records.map do |record|
      {
          id: record.id,
          first_name: record.first_name,
          last_name: record.last_name,
          address: record.address,
          bio: scrollable_wrap(record.bio)
      }
    end
  end

  def scrollable_wrap(item)
    result = '<div class="scrollable-div">'
    result += item
    result += '</div>'
    return raw result
  end
```

**Comment by n-rodriguez** [comment]
```ruby
  def scrollable_wrap(item)
    content_tag(:div, item, class: 'scrollable-div')
  end
```
