### ISSUE TITLE
input search value, applied to all columns?

### ISSUE THREAD

**Issue by webrups** [jbox-web/ajax-datatables-rails#231]
I have a table with 12 columns with different kind of input types, number, date, text.

It looks like to handle input values wrong. When I put in some value in the input for column 2, it is applied to all 12 columns. don't know why this is happening?

**Comment by ajahongir** [comment]
It seams you are using global search. what is your request to a server?

**Comment by n-rodriguez** [comment]
Hi there! Any news?
