### ISSUE TITLE
trigger for redraw datatable wrong?

### ISSUE THREAD

**Issue by webrups** [jbox-web/ajax-datatables-rails#232]
It looks wrong to me. since i switched to 0.4 version it triggers the ajax request on every event. instead of just on change it als reacts on evry single key. Not really user friendly and wrong in my eyes.

Can I change this behavior?

**Comment by n-rodriguez** [comment]
> It looks wrong to me. since i switched to 0.4 version it triggers the ajax request on every event. instead of just on change it als reacts on evry single key. Not really user friendly and wrong in my eyes.
> 
> Can I change this behavior?

This is a https://datatables.net/ thing not ajax-datatables-rails.
