### ISSUE TITLE
v0.4.0 fail with default_scope 

### ISSUE THREAD

**Issue by inyerade** [jbox-web/ajax-datatables-rails#233]
I am working with ajax-datatables-rails v0.4.0

And add a default_scope and datatable fail with

     ERROR:  missing FROM-clause entry for table

I think this is similar or the same as #223 , because I fix with the same method.

I know the workaround but I post the issue because I think this may be an important issue. :smile:

**Comment by n-rodriguez** [comment]
https://rails-bestpractices.com/posts/2013/06/15/default_scope-is-evil/
