### ISSUE TITLE
undefined method `and' for nil:NilClass when search string is comma-separated

### ISSUE THREAD

**Issue by kv109** [jbox-web/ajax-datatables-rails#234]
If `searchable_columns` is an empty array and `params[:search][:value]` is a comma-separated string, `ActiveRecord#build_conditions_for_datatable` crashes with 
```
NoMethodError: undefined method `and' for nil:NilClass
Did you mean?  rand
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `each'
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `reduce'
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `build_conditions_for_datatable'
./lib/ajax-datatables-rails/orm/active_record.rb:29:in `build_conditions'
./lib/ajax-datatables-rails/orm/active_record.rb:10:in `filter_records'
./lib/ajax-datatables-rails/base.rb:87:in `retrieve_records'
./lib/ajax-datatables-rails/base.rb:49:in `records'
./spec/support/test_helpers.rb:97:in `data'
```

**Comment by ajahongir** [comment]
@kv109 can you pass your testing params on params[:search][:value]?

**Comment by kv109** [comment]
@ajahongir I'm not sure if I understand the question, but I created [PR](https://github.com/jbox-web/ajax-datatables-rails/pull/235) where you can see [params](https://github.com/jbox-web/ajax-datatables-rails/pull/235/files#diff-6819002a94cd1472c4d7ad26b48ee555R98) which cause crash.

**Comment by ajahongir** [comment]
thank you, I see. It should work.. It seams we have to add some handlers on [SimpleSearch](https://github.com/jbox-web/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/datatable/simple_search.rb#L10) class
