### ISSUE TITLE
Custom view_columns

### ISSUE THREAD

**Issue by pawlarius** [jbox-web/ajax-datatables-rails#237]
Suppose i have a model called Transaction in rails..
 ```
def view_columns
    # Declare strings in this format: ModelName.column_name
    # or in aliased_join_table.column_name format
    @view_columns ||= {
      date: {source: "Transaction.created_at.strftime('%d/%m/%Y %H.%M.%S %p')"}
   }
end
 ```
how can i achieve this kind of modification to datetime?
@ajahongir

**Comment by n-rodriguez** [comment]
```
def view_columns
   # Declare strings in this format: ModelName.column_name
   # or in aliased_join_table.column_name format
   @view_columns ||= {
     date: { source: "Transaction.created_at" }
  }
end
```

```
def data
  records.map do |record|
    {
      date: record.created_at.strftime('%d/%m/%Y %H.%M.%S %p')
    }
  end
end
```

**Comment by pawlarius** [comment]
if i  do that, when searching it wont recognize the new format.. @n-rodriguez

**Comment by ajahongir** [comment]
@Pawlarius Well, I think you have to use `formater` option on `view_columns`
```ruby 
def view_columns
  @view_columns ||= {
    date: { source: "Transaction.created_at", formater: format_date }
   }
end
...
private
def format_date value
  Time.strptime(value, '%d/%m/%Y %H.%M.%S %p').strftime('%d/%m/%Y %H.%M.%S')
end
...
```
updated

**Comment by pawlarius** [comment]
thankyou for your help, i tried that but somehow it return Argument Error.. @ajahongir 
and where can i find more information about this formater feature .. :0
btw im using this gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0'

**Comment by ajahongir** [comment]
@Pawlarius  
>where can i find more information about this formater feature 
>btw im using this gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'v-0-4-0'

you have to use master branch to use formatter feature.

I guess you will solve your issue with this feature.

here is how this calling - https://github.com/jbox-web/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/datatable/column.rb#L102

so in this method you can recieve a searching value, handle and return a new value ready to search

**Comment by pawlarius** [comment]
i follow your example and using master branch, still same issue..with wrong number of arguments.. @ajahongir

**Comment by n-rodriguez** [comment]
Well the formater is attended to be a proc that can take one argument : the search value.

Can you please try with :

```ruby
def view_columns
  @view_columns ||= {
    date: { source: "Transaction.created_at", formater: format_date }
   }
end
...
private
def format_date
  ->(value) { Time.strptime(value, '%d/%m/%Y %H.%M.%S %p').strftime('%d/%m/%Y %H.%M.%S') }
end
...
```

**Comment by pawlarius** [comment]
```ruby
def data
  records.map do |record|  
    { date: record.created_at.strftime('%d/%m/%Y') }
  end
end

def format_date
  ->(value) { Time.strptime(value, '%d/%m/%Y').strftime('%d/%m/%Y') }
end
```

search for "0" return -> ArgumentError (invalid strptime format - `%d/%m/%Y'):
search for "06/07/2017" return nothing

please help @n-rodriguez

**Comment by ajahongir** [comment]
>search for "0" return -> ArgumentError (invalid strptime format - `%d/%m/%Y'):

0 will not be parsed as date

>search for "06/07/2017" return nothing

what is your sql output in this request?

**Comment by pawlarius** [comment]
what i mean is, when i apply formater, that makes me unable to do filter normally that matches text and returns error . While filter with date format will return sql error..
sql when search by date ->

SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
   (6.7ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT `payments`.`id` AS count_column FROM `payments` INNER JOIN `transactions` ON `transactions`.`id` = `payments`.`transaction_id` WHERE (xendit_type = 'VirtualAccount') AND (transactions.user_id= 1) LIMIT 15) subquery_for_count

^ i checked this in mysql and it return error sql syntax..

@ajahongir

**Comment by ajahongir** [comment]
@Pawlarius where is your error log ?

**Comment by ajahongir** [comment]
please give more information: 
- what params coming from client side
- what quest is exuciting on server 
- error logs
- ...
It makes understand your problem..

**Comment by ajahongir** [comment]
xendit_type - from which table you are calling this field?

**Comment by pawlarius** [comment]
ah right, sorry, 
when input filter with '0'
![screen shot 2017-07-09 at 1 28 09 pm](https://user-images.githubusercontent.com/27823957/27991739-98477f6c-64aa-11e7-8245-370431b89ad8.png)
![screen shot 2017-07-09 at 1 28 20 pm](https://user-images.githubusercontent.com/27823957/27991741-9905e3ee-64aa-11e7-8007-89718751bd15.png)


when input filter with '06/07/2017'
![screen shot 2017-07-09 at 1 30 09 pm](https://user-images.githubusercontent.com/27823957/27991751-c77aeb3e-64aa-11e7-8636-828214223725.png)
![screen shot 2017-07-09 at 1 30 18 pm](https://user-images.githubusercontent.com/27823957/27991752-c880c6a2-64aa-11e7-9fad-89e933e34c16.png)

`
def get_raw_records
Payment.includes(:entry).virtual_account.joins(:entry).where("transactions.user_id= #{options[:id]}").limit(15)
end
`
xendit_type is from my table Payments, entry is from Transaction table.. 
@ajahongir

**Comment by ajahongir** [comment]
well, you have 2 problems
1. you are not handling incoming search value. you have to something like this:

```ruby 
def format_date
  ->(value) { Time.strptime(value, '%d/%m/%Y').strftime('%d/%m/%Y') rescue Time.current.strftime('%d/%m/%Y') }
end
```
because when you sending '0' param as searching - you cant parse it to datetime.
I gues you use just input instead of datetime input at client side.

2. next problem is related on wrong passing data to Arel, It seams you are passing string instead of Arel node. are you using custom_column_search method? can you show your datatable?

**Comment by pawlarius** [comment]
actually i already try to handle problem number 1 like this,before you told me, i thought it can handle it automatically so i thought this is not the correct way..

![screen shot 2017-07-09 at 2 05 39 pm](https://user-images.githubusercontent.com/27823957/27991909-c0deb53a-64af-11e7-80d8-8d9ea6ced8ec.png)
![screen shot 2017-07-09 at 2 05 49 pm](https://user-images.githubusercontent.com/27823957/27991910-c13f4792-64af-11e7-97c4-f305018a5cca.png)
@ajahongir 

for def filter_status i just try to check something, 
it is like this
```
def filter_status
    Rails.logger.info("EXAMPLE")
  end
```

**Comment by ajahongir** [comment]
well your problem is with filter_status it should look like `[this](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb#L31)`

**Comment by pawlarius** [comment]
@ajahongir 

i deleted method filter_status, it still doesnt work as it supposed to.. sql return empty set :0

**Comment by ajahongir** [comment]
try this one
def view_columns
  @view_columns ||= {
    date: { source: "Transaction.created_at", formater: format_date, cond: :start_with }

   ....
   }
end

**Comment by pawlarius** [comment]
still return no matching records found @ajahongir 
anyway, while handling invalid format date with rescue, i cant do any filter ,anything i type will only return all the data :0

this is a screenshot with cond start_with
![screen shot 2017-07-09 at 11 55 21 pm](https://user-images.githubusercontent.com/27823957/27995975-2431c922-6502-11e7-9264-77c96af2da63.png)
![screen shot 2017-07-09 at 11 55 27 pm](https://user-images.githubusercontent.com/27823957/27995976-24cb4de0-6502-11e7-8c6d-c9e170b17b78.png)

**Comment by ajahongir** [comment]
def view_columns
@view_columns ||= {
date: { source: "Transaction.created_at", cond: :date_search }

....
}
end
...
private
def date_search
  ->(column) { column.table[column.field].eq(column.search.value.to_date) }
end

**Comment by pawlarius** [comment]
did u mean use cond: :death_search with formater or only cond?
tried both, and got error like this ( input filter '06/07/2017', tried to input filter normally also cause error)
![screen shot 2017-07-10 at 12 14 23 am](https://user-images.githubusercontent.com/27823957/27996111-02d89ec4-6505-11e7-902e-ff1b3c308f92.png)
![screen shot 2017-07-10 at 12 14 29 am](https://user-images.githubusercontent.com/27823957/27996113-049324aa-6505-11e7-9c8f-bb962205788c.png)
@ajahongir

**Comment by ajahongir** [comment]
>did u mean use cond: :death_search with formater or only cond?

only `cond` field

**Comment by pawlarius** [comment]
only cond field return same error like this @ajahongir 
kinda lost now about what is going on :")
![screen shot 2017-07-10 at 12 19 34 am](https://user-images.githubusercontent.com/27823957/27996128-8f93166e-6505-11e7-8624-34954a81362d.png)
![screen shot 2017-07-10 at 12 19 40 am](https://user-images.githubusercontent.com/27823957/27996129-8fffde98-6505-11e7-9618-0f9fd2d6a18d.png)

**Comment by ajahongir** [comment]
you are using datatable.js global search, not per column search, right?
you it not good idea to use this. you always can use per column search as [here](https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to) 

btw, can you check what param as passing as `column` in this proc?
```ruby
def date_search
->(column) {
p column
p column.class
column.table[column.field].eq(column.search.value.to_date)
}
end
```
what type of object column is?

**Comment by pawlarius** [comment]
btw, i tried to remove ':' from cond: :date_search, catch argument error message as invalid date and this is the result..
filter with '0', return column as : <AjaxDatatablesRails::Datatable::Column:0x007ff760995958>
with column class as : AjaxDatatablesRails::Datatable::Column
and sorry,column per search with how did u mean?

input filter with '06' or '06/07' or '06/07/2017' return sql with empty set, when type '06/0' return noMethodError, undefined method 'or' for NilClass
@ajahongir

**Comment by ajahongir** [comment]
> '06/07/2017' return sql with empty set

are you sure that you have any records in db with these conditions?

**Comment by pawlarius** [comment]
fixed it, turn out i need to handle when it is in correct form and return search to normal when it doesnt match my format.

**Comment by taranjeetsingh-evontech** [comment]
Hi @pawlarius Can you please tell me what was the solution that you used at the end.

**Comment by arlharis** [comment]
> fixed it, turn out i need to handle when it is in correct form and return search to normal when it doesnt match my format.

Hi, @pawlarius. Can i know your solution ?
