### ISSUE TITLE
When render form by "AjaxDatatablesRails::Base"

### ISSUE THREAD

**Issue by kntmrkm** [jbox-web/ajax-datatables-rails#24]
Hi.
Thank you for gread gem.

I tried to render form in table record by "render" helper.

Env is...
- rails 4.1.4
- ajax-datatables-rails-0.2.0
- jquery-datatables-rails-2.1.10.0.3

but, form is collapsed. when render by `data` method in `AjaxDatatablesRails::Base`.

like below.

ex.1) normal render by rails.
![___reserven](https://cloud.githubusercontent.com/assets/2703486/3634049/dddf9ce0-0f11-11e4-931a-5c9e7559a276.png)

ex.2) collapsed form that render by `data` method in `AjaxDatatablesRails::Base`.
![___reserven](https://cloud.githubusercontent.com/assets/2703486/3634054/f4fd5fc0-0f11-11e4-9ba5-463e2ad66dc0.png)

code is below.

```
class ReservationDatatable < CommonDatatable
  def_delegator :@view, :render

  # ommit ・・・・

  private

  def data
    records.map do |record|
      [
        render(set_args('reservations/datatables/td_date.html', record, :reservation)),
        render(set_args('reservations/datatables/td_modal_show.html', record, :reservation)),
      ]
    end
  end

  def get_raw_records
    options[:user].account.reservations.
      includes(:user, :customer, [customer: :member_user])
  end

  def set_args(template, record, target)
     { partial: template, locals: { target => record }, formats: :html }
  end
end
```

The 'reservations/datatables/td_modal_show.html' includes modal html.
I want to use modal within datatable's record.

How do I fix my code?

Sorry my English.

**Comment by kntmrkm** [comment]
Sorry guys.

I found couse of problem.

A class of `dataTables_wrapper` is created with `form-inline`.

So, I have removed when datatables is rendered.

```
  drawCallback: function(oSettings) {
      $('.dataTables_wrapper').removeClass("form-inline");
    }
```

but, why set a class of `form-inline`?

**Comment by antillas21** [comment]
@kntmrkm 

Glad you found the cause of your problem.

I wouldn't know what to tell about you the `form-inline` class in the resulting `.dataTables_wrapper` markup as that is provided by the original jQuery.dataTables plugin.

Perhaps, you'd like to contribute your suggestion to the plugin author? :smile:

**Comment by zamananjum0** [comment]
@kntmrkm  Can you please help me on this issue,I want to know how you render modal popup in datatable  and in my case i render modal popup using erb.js and then render partial view, and want to ajax datable's response in modal popup.
