### ISSUE TITLE
Is "orderable?" implemented? 

### ISSUE THREAD

**Issue by aldefouw** [jbox-web/ajax-datatables-rails#245]
Something that is not clear from the documentation is the "orderable" attribute for version 0.4.0.

I added an 'orderable' attribute to my column hash within the @view_columns hash as specified in the README, like so:
  
```
def view_columns
    @view_columns ||= {
        name: { source: "Visit.name", cond: :like, searchable: true, orderable: false }
    }
  end
```

It doesn't appear to have any effect on whether the sorting takes place though.  Ordering by a column IS working regardless of whether I disable it in the DataTables definition.

I did figure out a work-around by disabling it in the JavaScript column definition: 
    
```
columns: [
      { data: "name", orderable: true }
      { data: "study", orderable: false }
      { data: "action", orderable: false }
    ]
```

I'm certainly not an expert on this codebase - so I am probably missing something.

But if the "orderable" attribute has no effect in the Ruby code, then it either needs to be

a) implemented 

or

b) removed from documentation (so as to lessen confusion)

Even so - I'd like to thank all the contributors for their hard work on this gem.  It is great!

**Comment by ajahongir** [comment]
you can turn off orderable on client side https://datatables.net/reference/option/ordering

**Comment by n-rodriguez** [comment]
Hi! Thank for your feedback.You're right, the feature is not implemented. There's some code around that needs to be fixed : https://github.com/jbox-web/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/orm/active_record.rb#L18

**Comment by aldefouw** [comment]
@n-rodriguez  - Thanks so much for the prompt response.  

I really like the flexibility that the newest version offers and look forward to this being fixed at some point.

In the meantime, I'll keep my work-around.

Thanks again for your response!
