### ISSUE TITLE
Using ajax-datatables searchable method with namespaced models (from engine)

### ISSUE THREAD

**Issue by LaurensN** [jbox-web/ajax-datatables-rails#25]
I'm stuck trying to implement ajax datatables that makes use of a model that resides in a Rails Engine (EngineName::ModelName.column_name) .

As far as I can see this leads to compatibility issues in the searchable method.

def search_condition(column, value)
    model, column = column.split('.')
    model = model.singularize.titleize.gsub( / /, '' ).constantize
    model.arel_table[column.to_sym].matches("%#{value}%")
end

Can someone point me in the right direction ?

**Comment by LaurensN** [comment]
I've monkeypatched the method to suit my project, this works fine, I'll update when I find a more graceful solution for a pull request.

**Comment by antillas21** [comment]
@LaurensN ,

Looking forward to a PR from your findings. Let me know if we can help in anything.

**Comment by antillas21** [comment]
Closing this issue, as a [pull request](https://github.com/antillas21/ajax-datatables-rails/pull/26) has been opened to address this scenario.
