### ISSUE TITLE
Documentation: date_range search

### ISSUE THREAD

**Issue by alondahari** [jbox-web/ajax-datatables-rails#250]
Hi,
It would be great if you could add some documentation about how to implement the date_range search option.
Thanks!

**Comment by crstin** [comment]
Seconded, it's not even in `ajax-datatables-rails-v-0-4-0-how-to`. An example would be much appreciated.

**Comment by n-rodriguez** [comment]
Done : https://github.com/jbox-web/ajax-datatables-rails#daterange-search
