### ISSUE TITLE
no implicit conversion from nil to integer when trying to re-order column

### ISSUE THREAD

**Issue by rorykoehler** [jbox-web/ajax-datatables-rails#252]
The datatable loads perfectly however when I try re-order the column I get 

`TypeError Exception: no implicit conversion from nil to integer`

I have traced it to the `fetch_records` method however I'm a little lost as `fetch_records` simply calls `get_raw_records`. Using byebug as the first line of the `data` method in my datatable class if I call `get_raw_records` it works perfectly as expected however if I call `fetch_records` I get the error. Any ideas? 

Overloading the `fetch_records` method in the datatable class as below solves the issue:

```
def fetch_records
    get_raw_records
end
```

**Comment by n-rodriguez** [comment]
Hi there! Do you still have this issue?

**Comment by ajahongir** [comment]
@rorykoehler I gues you are using 0.3.x version. you have to use later version or master branch
