### ISSUE TITLE
Make global search and column search work together

### ISSUE THREAD

**Issue by diesl** [jbox-web/ajax-datatables-rails#258]
As stated [here](https://github.com/jbox-web/ajax-datatables-rails/issues/212#issuecomment-318735866), it is not possible right now to consider both global and column search terms at the same time. When a global search term is present, the column values are ignored.

My request is that both global and column search terms are considered, where the column search terms act as a filter on the result of the global search. This is what I would expect as a user.

The [docs](https://datatables.net/reference/api/column().search()) speak of filtering too:
> Note that this search ability in DataTables is actually technically a filter since it is subtractive.

If you don't want to change behaviour comparing to previous releases, you could make it configurable at least. Thanks!

Edit:
The proposed change would also match the "normal" DataTable behaviour (Non Server-Side Processing mode). I use Datatables in both ways (SSP and non-SSP), and I suspect the different behaviour confuses users.

**Comment by julfla** [comment]
Thank you for highlighting this.

I am using the gem on a project, and was quite confused before seeing this issue.

**Comment by Nittarab** [comment]
This will be really appreciated!

**Comment by julfla** [comment]
Hi @n-rodriguez, how do you feel about this?

A project of mines requires this feature and I have some time to try address this.

Do you think that we should open some configuration for this?

If not, it seems that only lib/ajax-datatables-rails/orm/active_record.rb would be impacted.

**Comment by diesl** [comment]
> Hi @n-rodriguez, how do you feel about this?
A project of mines requires this feature and I have some time to try address this.
Do you think that we should open some configuration for this?

@n-rodriguez What do you think? I would like to see this implemented too, of course 😉

**Comment by diesl** [comment]
Hello @n-rodriguez,
do you have any plans to implement this? I think it is a core feature to support global search and column search simultaneously and it would help me a lot if I could make use of this feature. Right now I hacked it using the params object, but I would like to have a clean solution of course.

It appears to me that others also would like to have this implemented, regarding the reactions on my initial post.

I took a look at the code today but and tried to find a solution, but it seems to me that a solution is not as trivial as changing some lines of code.

**Comment by pekoiq** [comment]
@diesl, 
I guess this is still unresolved.  I know this is in an older thread, but I'm wondering if you could share how you hacked the ability to support global search and column search simultaneously using the params object.

**Comment by diesl** [comment]
> I guess this is still unresolved.

Unfortunately you are right. Not sure why @n-rodriguez did not answer to my previous comments. 😢 It is the issue with most +1, so I think other users would like to have this resolved too.

> I'm wondering if you could share how you hacked the ability to support global search and column search simultaneously using the params object.

It is quite a while ago when I looked at the code the last time, and also it changed a bit in the meantime.

But basically I concat some specific column search value to the global search string using a separator. Server side, I split them again and then pass the column search value with the `options` object. The `options` object can be used in `get_raw_records`. 

Ugly, but works 😐
