### ISSUE TITLE
links to edit

### ISSUE THREAD

**Issue by rsantelices** [jbox-web/ajax-datatables-rails#263]
Hey guys im having a hard time getting the link_to to work properly, this is the code:

```
 def_delegator :@view, :link_to

def data
  records.map do |record|
    {
      id: link_to(record.id, edit_resource_path(record)),
      email:  record.email
    }
  end
end
```

However they do not render fine

**Comment by ajahongir** [comment]
https://github.com/jbox-web/ajax-datatables-rails/blob/master/README.md#using-view-helpers

**Comment by ryleto** [comment]
try adding the resource path attribute to the delegator line:

`def_delegator :@view, :link_to, :edit_resource_path`
