### ISSUE TITLE
Support for upper case column names?

### ISSUE THREAD

**Issue by gs2589** [jbox-web/ajax-datatables-rails#267]
I seem to be having an issue with upper case column names

Here is my view method.

```
def view_columns
    # Declare strings in this format: ModelName.column_name
    # or in aliased_join_table.column_name format
    
     @view_columns ||= {
      show_name: {source: 'Product.custom_name', cond: :like, searchable: :true, orderable: :true},
      product_code: {source: 'Product."NDC"', cond: :like, searchable: :true, orderable: :true}
   }
end

```

This works for sorting, but when I try to search, I get an error:

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column products."NDC" does not exist
LINE 1: ...ts"."custom_name" AS VARCHAR) ILIKE '%a%' OR CAST("products"...
                                                             ^
HINT:  Perhaps you meant to reference the column "products.NDC".

If I remove the double quotes from the method, I get an error on table initialization :
 ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column products.ndc does not exist

**Comment by n-rodriguez** [comment]
The convention of Rails is to use downcased column names. I've made some searches and some hacks exist to work around this case, but it's hacks.
