### ISSUE TITLE
Is orthogonal data supported with this gem?

### ISSUE THREAD

**Issue by gs2589** [jbox-web/ajax-datatables-rails#269]
In my data table I have the following column definition:

```
columns:[
       {data: "supplier",
             render: function(data, type, row){
              return data ? data.name : null
             }
]
```

In my SearchResultDatatable#data method I have

```
def data
    records.map do |record|
      {
        supplier: {name: record.supplier.try(:name)},
        
      }
end

```
This is not working - I get the  datatables.net/tn/4 error because 

` {name: record.supplier.try(:name)} `

gets serialized as a string not an object- so data.name returns undefined.

Any thoughts on how to fix this?

**Comment by n-rodriguez** [comment]
Add this in your JS:

```
data = JSON.parse(data);
```

**Comment by gs2589** [comment]
Thanks n-rodriguez.
I tried your suggestion, but got this error:

> Uncaught SyntaxError: Unexpected token # in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at eval (eval at format (purchases:12), <anonymous>:1:6)
>     at format (purchases:265)
>     at HTMLTableCellElement.<anonymous> (purchases:355)
>     at HTMLTableSectionElement.dispatch (jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1:5227)
>     at HTMLTableSectionElement.elemData.handle (jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1:4879)


It looks like the issue arises because of the #sanitize method 

```
def sanitize(data)
      data.map do |record|
        if record.is_a?(Array)
          record.map { |td| ERB::Util.html_escape(td) }
        else
          record.update(record){ |_, v| ERB::Util.html_escape(v) }
        end
      end
    end

```

Is there a way to go around this?
Is it a bad idea to bypass this method?
Is there a way to get standard serialization into json?

**Comment by gs2589** [comment]
Ok, Im making some progress:

Here is some **new** code:

```
def data
    records.map do |record|
      {id: record.id,
       scan_timestamp: raw({data:record.effective_date.in_time_zone('Eastern Time (US & Canada)').strftime("%I:%M%p %Z %d-%b-%y"), display:"hello"}.to_json)
end
```

then in js, I can do 
data = JSON.parse(row.scan_timestamp)
and that converts it into an object. Im wondering if there is a way to format the data in Datatable#data to ensure that the js datatables automatically turns orthogonal data into nested objects?

Thanks!

**Comment by MrMoins** [comment]
I'm also trying to use orthogonal data but can't figure how to do with this gem.

**Comment by MrMoins** [comment]
I'm trying to modify sanitize method like this, it return a json object correctly formatted but now I've some issue on JS side.

```ruby
def sanitize(data)
  data.map do |record|
    if record.is_a?(Hash)
      record
    elsif record.is_a?(Array)
      record.map { |td| ERB::Util.html_escape(td) }
    else
      record.update(record){ |_, v| ERB::Util.html_escape(v) }
    end
  end
end
```

**Comment by gs2589** [comment]
@n-rodriguez  Any thoughts on this? 
I'd love to figure out a 'standard' way to do this with this gem and add it to the readme.  Orthogonal data is pretty core to datatables, so I think many users would benefit.  I'd be happy to write up the guide for the readme, at this moment, I've not been able to get this to work.

**Comment by n-rodriguez** [comment]
Hi! It could be supported. Nowadays the data is assumed to be html content so it's html escaped to avoid XSS attacks. What you want is json all the way so :

Override the `sanitize` method in your datatable :

```ruby

  def data
    records.map do |record|
      {
        id:    record.id,
        title: { title: record.title }
      }
    end
  end

  private

    def sanitize(data)
      data.map do |record|
        if record.is_a?(Array)
          record.map { |td| ERB::Util.html_escape(td) }
        elsif record.is_a?(Hash)
          if options[:json_content]
            record
          else
            record.update(record) { |_, v| ERB::Util.html_escape(v) }
          end
        end
      end
    end
```
and in the controller :

```ruby
  def index
    respond_to do |format|
      format.html
      format.json { render json: PostDatatable.new(params, json_content: true) }
    end
  end
```

And in Coffee/JS :

```coffee
$ ->
  $('#posts-datatable').dataTable
    processing: true
    serverSide: true
    ajax: $('#posts-datatable').data('source')
    pagingType: 'full_numbers'
    columns: [
      { data: 'id' }
      {
        data: 'title',
        render: (data, type, row)->
          console.log(data)
          if data?
            data.title
          else
            ''
      }
    ]
```

**Comment by n-rodriguez** [comment]
BTW I would use https://github.com/jbox-web/ajax-datatables-rails#using-view-decorators to avoid this kind of lengty methods :

```ruby
# before
def data
  records.map do |record|
    {
      id: record.id,
      scan_timestamp: raw({ data: record.effective_date.in_time_zone('Eastern Time (US & Canada)').strftime("%I:%M%p %Z %d-%b-%y"), display:"hello" }.to_json
    }
  end
end

# after
def data
  records.map do |record|
    {
      id: record.id,
      scan_timestamp: { data: record.decorate.effective_date, display: 'hello' }
    }
  end
end
```

**Comment by n-rodriguez** [comment]
Added in the README : https://github.com/jbox-web/ajax-datatables-rails#tutorial

**Comment by calaway** [comment]
I'm trying to specify a `data-sort` (or `data-order`) tag on a column and can't quite get it working from these instructions. Can you help me see what I've done wrong?

```ruby
  def data
    records.map do |record|
      {
        id: record.id,
        build_number: { display: record.build_number, sort_by: record.build_number.to_i },
      }
    end
  end
```

```javascript
$(document).ready(function(){
  $('#builds-datatable').DataTable({
    // ...
    columns: [
      { data: "id"},
      { data: "build_number",
        render: {
          _: 'display',
          sort: 'sort_by',
       }
      }
    ]
  });
});
```

`display` is showing correctly, but I can't get it to add the `data-sort` attribute. I know both `display` and `sort_by` are coming through to the client side correctly, since I can access both of them.

I have added `json_content: true` to the controller and copied the `sanitize` method into the datatable class.

Any help you can offer is greatly appreciated. Thank you for creating and maintaining such a useful gem!

**Comment by srodney86** [comment]
> I'm trying to specify a `data-sort` (or `data-order`) tag on a column and can't quite get it working from these instructions. Can you help me see what I've done wrong?
> 
> ```ruby
>   def data
>     records.map do |record|
>       {
>         id: record.id,
>         build_number: { display: record.build_number, sort_by: record.build_number.to_i },
>       }
>     end
>   end
> ```
> 
> ```js
> $(document).ready(function(){
>   $('#builds-datatable').DataTable({
>     // ...
>     columns: [
>       { data: "id"},
>       { data: "build_number",
>         render: {
>           _: 'display',
>           sort: 'sort_by',
>        }
>       }
>     ]
>   });
> });
> ```
> 
> `display` is showing correctly, but I can't get it to add the `data-sort` attribute. I know both `display` and `sort_by` are coming through to the client side correctly, since I can access both of them.
> 
> I have added `json_content: true` to the controller and copied the `sanitize` method into the datatable class.
> 
> Any help you can offer is greatly appreciated. Thank you for creating and maintaining such a useful gem!

Did you ever manage to solve this?
I'm having the same problem with it working on the display side but the sort attribute is not applying.
