### ISSUE TITLE
searchable_columns and PostgreSQL

### ISSUE THREAD

**Issue by asmaloney** [jbox-web/ajax-datatables-rails#27]
If you use a non-string type in the searchable_columns list and are using PostgreSQL, it will fail with an error:

`PG::UndefinedFunction: ERROR:  operator does not exist: integer ~~* integer`

The SQL becomes something like this:

``` sql
SELECT COUNT(*) FROM "foo"  WHERE ((((("foo"."id" ILIKE 0 OR "foo"."date" ILIKE '%%')...
```

I think it's because this function in base.rb is playing with **_arel_table**_:

``` ruby

    def search_condition(column, value)
      model, column = column.split('.')
      model = model.singularize.titleize.gsub( / /, '' ).constantize
      model.arel_table[column.to_sym].matches("%#{value}%")
    end
```

Possible solution is to check the searchable_columns type (somehow) and only use LIKE/ILIKE on strings.

**Comment by antillas21** [comment]
@asmaloney mmmh... yeah, if one of the searchable columns is not string or text-based , it breaks. So, yeah, either that (use LIKE/ILIKE on string-based only) or a type cast... will need to check this issue.

Thanks for reporting. :smile:

**Comment by antillas21** [comment]
@asmaloney We have pushed a new commit that will help you solve this issue. Please see the updated [CHANGELOG](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md#yet-unreleased)

This functionality is present in the `master` branch of the repo and is currently un-released. If you'd like to use this in your project, please add this to your Gemfile:

``` ruby
gem "ajax-datatables-rails", git: "git@github.com:antillas21/ajax-datatables-rails.git", branch: "master"
```
