### ISSUE TITLE
Trying to simply include one model association.

### ISSUE THREAD

**Issue by altjx** [jbox-web/ajax-datatables-rails#273]
In the example on the github page, there is an extremely complicated and nested model scenario. However, I'm simply trying to include one associated model, but can't figure out how to simplify the scenario provided in the example.

For example, the example in the guide shows:

```
def get_raw_records
   Event.includes(
    { course: :coursetype },
    { allocations: {
        teacher: [:contact, { competencies: :competency_type }]
      }
    }
    ).references(:course).distinct
end
```

In my case, I just want to do one simple include, but not sure how. So here's my code:

```
class PageDatatable < AjaxDatatablesRails::Base

  # Allow the use of helpers in JSON response.
  def_delegators :@view, :link_to, :page_path

  def view_columns
    # Declare strings in this format: ModelName.column_name
    # or in aliased_join_table.column_name format
    @view_columns ||= {
      # id: { source: "User.id", cond: :eq},
      # name: { source: "User.name"}

      position: { source: "Page.position"},
      book_name: { source: "Page.book.book_name"},
    }
  end

  end

  def data
    records.map do |record|
      {
        # example:
        # id: record.id,
        # name: record.name
        position: record.position,
        book_name: link_to("#{record.book.book_name}", page_path(record), remote: true),
      }
    end
  end

  private

  def get_raw_records
    # insert query here
    Page.includes(:book)
  end
end
```

Again, I know the way I have `.includes(:book)` is currently incorrect, but I can't figure out how to make it work based on the example provided in the guide.

Any help would be greatly appreciated. This is one of the last pieces of the puzzle of my app before everything's functioning properly again.

**Comment by matissg** [comment]
If Page `has_many :books`, I believe it should be `Page.includes(:books)`, no?
I think you can just take a look on some examples from [Rails docs here](http://guides.rubyonrails.org/active_record_querying.html).

**Comment by altjx** [comment]
So page belongs to book. I tried just that though, but still got the error. This works generally in anywhere else in rails, but I guess with the ajax-datatables-rails gem it works a little differently?

Sent from my iPhone

On Jan 17, 2018, at 11:54 PM, matissg <notifications@github.com> wrote:

If Page has_many :books, I believe it should be Page.includes(:books), no?
I think you can just take a look on some examples from Rails docs here.

**Comment by ajahongir** [comment]
>Page.includes(:book)

what if you use `Page.joins(:book)`?

**Comment by matissg** [comment]
I think error could be in this part:
```
      position: { source: "Page.position"},
      book_name: { source: "Page.book.book_name"},
```
You have to define like: `book_name: { source: "Book.name"},`
If your association is set correctly, it should work.

**Comment by altjx** [comment]
I ended up using `.joins(:book)` and changed my @view_columns to Book.name and that did the trick. Thank you very much for your help!!! THanks a lot guys!
