### ISSUE TITLE
Styling body cells

### ISSUE THREAD

**Issue by CrAsH1101** [jbox-web/ajax-datatables-rails#274]
How to add style to table's <td>?
I want 3 column to be aligned right (but not the header).
I want 4 column to have some additional data attributes.
How can I achieve this?

Thanx,
Igor

**Comment by matissg** [comment]
I think it's basically about [DataTables styling](https://datatables.net/examples/styling/) - HTML, CSS.

**Comment by n-rodriguez** [comment]
I close this issue since it doesn't concern this gem.
