### ISSUE TITLE
rails datatable column filtering

### ISSUE THREAD

**Issue by gaiapuffo** [jbox-web/ajax-datatables-rails#276]
Hi, I have a rails 3.22 application with ruby 2.2 and gem 'ajax-datatables-rails', "0.3.1".
Ok, with global filtering I don't have any problem, but single column filtering don't work.
The problem I think is that the guide says

```
def data
  records.map do |record|
    [
     "#{image_tag(link_picture, class:'img-circle', style:'max-width:50px')}",
      record.first_name,
      record.last_name,
      record.bio
    ]
  end
end
```
In the first position I have a image.
The guide says that you have to use the same sequence of column declarations as in sortable_columns.
In my 

 @searchable_columns ||= {first_name,last_name}
 
So the problem is the image! But is not beautiful to have first_name,last_name and after image...so what can I do that use this order?

**Comment by ajahongir** [comment]
you have to use master branch or latest version to use filtering. and lookout sample project - https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to
