### ISSUE TITLE
has_scope gem support

### ISSUE THREAD

**Issue by emilenriquez** [jbox-web/ajax-datatables-rails#280]
https://github.com/plataformatec/has_scope 

this gem simplifies the need to create long hard coded queries that makes the function bloated.
is there any chance we can use this to query the data?

**Comment by n-rodriguez** [comment]
```ruby
format.json { render json: InvoiceDatatable.new(view_context, { current_org: current_organization }) }
```

```ruby
class Foo < AjaxDatatablesRails::Base
  include HasScope

  has_scope :featured, :type => :boolean
  has_scope :by_degree
  has_scope :by_period, :using => [:started_at, :ended_at], :type => :hash

  def get_raw_records
    apply_scopes(current_organization.invoices).all
  end

  private

  def current_organization
    options[:current_org]
  end
end
```

Don't use `:only` or `:except` options or it will crash with `Unknow method :action_name`

**Comment by emilenriquez** [comment]
what I did was I passed in the query to the the a datatable

```
format.json { render json: InvoiceDatatable.new(view_context, {current_org: current_organization, query: apply_scopes(current_organization.invoices.order(created_at: :desc)).all}) }
```

and in the datatable file 

```

  def get_raw_records    
    options[:query]
  end
```

**Comment by n-rodriguez** [comment]
It sounds like an anti pattern. Does the solution I propose work? (I didn't try it, just read the code of has_scope)

**Comment by emilenriquez** [comment]
ohh I see. will try your code above

I'm guessing it will loop through the columns and wouldn't be able to read the params defined in the has_scope?

**Comment by emilenriquez** [comment]
```
NoMethodError in InvoicesController#index

undefined method `to_unsafe_h' for nil:NilClass
Extracted source (around line #74):
```

**Comment by n-rodriguez** [comment]
I've updated the example above

**Comment by emilenriquez** [comment]
this worked like a charm! 

and neat code!!

**Comment by emilenriquez** [comment]
sorry, sorting worked.

but the custom filtering failed.

**Comment by n-rodriguez** [comment]
Ok. I will take a look when I can.

**Comment by emilenriquez** [comment]
thanks @n-rodriguez

**Comment by n-rodriguez** [comment]
@emilenriquez does it work?

**Comment by emilenriquez** [comment]
it did work @n-rodriguez thanks!

**Comment by cesar82** [comment]
Hi @emilenriquez, I would like to use has_scope with ajax call, so I don't need to reload my page, do you have any idea how can do it?

For example, I would add a checkbox for show/hide inactive users (it is a boolean in the table), if user check or uncheck the checkbox I would like to trigger the call and refresh my table and also when a user clicks in sort arrows in a specific column this value for inactive users can be included in the ajax call.


Thanks for any help here.

**Comment by cesar82** [comment]
@emilenriquez it looks it should be a good option for including my custom params into the ajax call, but i do not find how to trigger the datatable ajax call when the user clicks the show the inactive users

https://datatables.net/examples/server_side/custom_vars.html

**Comment by andreibondarev** [comment]
@cesar82 Have you been able to figure out how to refresh your DataTable without a page reload?

**Comment by cesar82** [comment]
@andreibondarev yes!

This method DataTable().ajax.reload() reloads the table and take the user to page 1, if you want to keep the current page use this way DataTable().ajax.reload(null, false)

Thanks
