### ISSUE TITLE
New method additional_data is not adding the extra data to the JSON

### ISSUE THREAD

**Issue by gersonazgo** [jbox-web/ajax-datatables-rails#286]
```
ruby 2.5.0
rails 5.2.0
ajax-datatables-rails 0.4.0
```

The deprecated method `additional_datas` works just fine.
The new method `additional_data` is **not adding the extra data to the JSON**.

Maybe it has something to do with this implementation.

https://github.com/jbox-web/ajax-datatables-rails/blob/0c0d4f2e7f75bf783ead25b8e1c9342174915b0a/lib/ajax-datatables-rails/base.rb#L72-L89

**Comment by n-rodriguez** [comment]
additional_data is only available on the master branch
