### ISSUE TITLE
TypeError: ajax is null

### ISSUE THREAD

**Issue by samuel-christian** [jbox-web/ajax-datatables-rails#287]
Hi, I've stumbled across this error message in console for a while. Also, this error breaks all the jquery plugin I use and I cannot seem to find the solution even in datatables forum.

I've followed the tutorial in README like this:

```
$("#pt-table").dataTable({
    "bPaginate": false,
    "bFilter": false,
    "bInfo": false,
    "ordering": false,
    "processing": true,
    "serverSide": true,
    "ajax": $(this).data("source"),
    "columns": [
      {"data": "account_code"},
      {"data": "identifier"},
      {"data": "name"},
      {"data": "department"},
      {"data": "order_id"},
      {"data": "cv_number"},
      {"data": "validity_period"},
      {"data": "paid_amount"},
      {"data": "other_information"},
      {"data": "posting_date"},
      {"data": "invoice_number"}
    ],
    "createdRow": function( row, data, dataIndex ) {
      $(row).addClass("space");
    }
  })
});
```

The data is loaded completely fine but there's error in the console message (this breaks all other jquery functionalities I use):
`TypeError: ajax is null` and it refers to datatable js to this line:
`ajax.data = ajaxData;`

Anyone have any insight?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by zarix** [comment]
my solution is to dissolve the part
```
"ajax": $(this).data("source") 
```
in 
```
"ajax": {
  "url": "/controller/action.json"
}
```

**Comment by n-rodriguez** [comment]
weird... anyway, it works :) (the [Datatables doc](https://datatables.net/reference/option/ajax))

**Comment by dcmorse** [comment]
I merged zarix' insight and their code together and got:
```
"ajax": {url: $(this).data("source")}
```
Works for me.
