### ISSUE TITLE
How to handle empty raw records?

### ISSUE THREAD

**Issue by hopewise** [jbox-web/ajax-datatables-rails#292]
if `get_raw_records` returns zero results, I will get this error:

```
ActiveRecord::StatementInvalid in ExperimentsController#my_students_experiments

PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: SELECT COUNT(*) FROM () AS foo
                              ^
: SELECT COUNT(*) FROM () AS foo
    <div class="source hidden" id="frame-source-0">
      <div class="info">
        Extracted source (around line <strong>#592</strong>):
      </div>
      <div class="data">
        <table cellpadding="0" cellspacing="0" class="lines">
          <tr>
            <td>
              <pre class="line_numbers">
```

So, how to handle the case when there is empty or zero count at the table?
here is my [StudentCircuitDatatable](https://gist.github.com/hopewise/2df786f11ea041120a00dbcee01808ab)

**Comment by n-rodriguez** [comment]
Hi! This should not happen : https://github.com/jbox-web/ajax-datatables-rails#c-get-raw-records.
I don't know what `Experiment.none` returns but it might be the culprit.

**Comment by n-rodriguez** [comment]
> So, how to handle the case when there is empty or zero count at the table?

This is actually handled provided you return a chainable `ActiveRecord::Relation` object.

**Comment by hopewise** [comment]
`Experiment.none` return a relation with empty result. So, what shall I return in case I don't want to show any record?
