### ISSUE TITLE
Rails 5.2.0  - undefined method params for ActionController::Parameters

### ISSUE THREAD

**Issue by nicwillemse** [jbox-web/ajax-datatables-rails#297]
There seems to be a compatibility problem with rails 5.2.0, it appears to be trying to call the `params ` method on the params object.

`NoMethodError (undefined method 'params' for #<ActionController::Parameters:0x00007feccc8fcb70>)`

The Code : 
```ruby
def index
    respond_to do |format|
      format.html
      format.json { render json: StepDefinitionDatatable.new(params) }
    end
end
```

**Comment by nicwillemse** [comment]
was fixed with

`format.json { render json: StepDefinitionDatatable.new(view_context) }`

**Comment by slead** [comment]
@nicwillemse using Rails 5.2.0 I'm also seeing the same error as in your original post. Can you please clarify the fix of using `view_context`?

When I try this, I get a different error message:

> undefined method `to_unsafe_h' for nil:NilClass

thanks

**Comment by nicwillemse** [comment]
@slead can you share the code please, might be easier to help that way.

based on the error, I would guess that you are handing in a null object.

**Comment by somazx** [comment]
I'm seeing the same issue. For starters the documentation all shows passing in params, which results in the error:
> NoMethodError (undefined method 'params' for #ActionController::Parameters: ... >)

If I pass in the view_context then I get the
> undefined method `to_unsafe_h' for nil:NilClass

In module `Datatable#get_param` when I inspect `options`, it isn't a hash, it is the actual params object:
> <ActionController::Parameters {"controller"=>"se_client/forms/site_inspections", "action"=>"index", "format"=>"json"} permitted: false>

I thought *maybe* line 76 should be something like:
`options.to_unsafe_h.with_indifferent_access[param]`

instead of

`options[param].to_unsafe_h.with_indifferent_access`

Here is the tail end of the stack trace:
```
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/datatable/datatable.rb:76:in `get_param'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/datatable/datatable.rb:45:in `columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/datatable/datatable.rb:51:in `column_by'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:54:in `block in connected_columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:53:in `map'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:53:in `connected_columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:61:in `searchable_columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:67:in `search_columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/orm/active_record.rb:52:in `build_conditions_for_selected_columns'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/orm/active_record.rb:36:in `build_conditions'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/orm/active_record.rb:12:in `filter_records'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:113:in `records_filtered_count'
ajax-datatables-rails (0.4.3) lib/ajax-datatables-rails/base.rb:41:in `as_json'
```

**Comment by somazx** [comment]
To be clear, at this point the params are empty; as this is on initial load. Therefore options[param] (param value at this point is `columns`) does return nil.

> <ActionController::Parameters {"controller"=>"se_client/datatable", "action"=>"index", "format"=>"json"} permitted: false>

**Comment by slead** [comment]
@nicwillemse I'm following the 'quick start in 5 steps' section from https://github.com/jbox-web/ajax-datatables-rails, using a simple model which works normally outside of ajax-datatables-rails, but fails once I add in the line `format.json { render json: UserDatatable.new(params) }` to the controller's index

**Comment by somazx** [comment]
Problem solved for me.

In my case I was just trying to test the endpoint using get request in browser without any params.
ajax-datatables-rails expects and requires the full set of datatable parameters to be passed in.

**Comment by n-rodriguez** [comment]
Hi everybody! I'm sorry by the online documentation is for the master branch and not the v0.4.x.
If you're using the v0.4.x use `Datatable.new(view_context)` in your controllers.
If you want to use the master branch use `Datatable.new(params)`.

**Comment by n-rodriguez** [comment]
There's a discussion about the subject : https://github.com/jbox-web/ajax-datatables-rails/issues/288

**Comment by bhushangahire** [comment]
How do I pass params with view_context then?

**Comment by n-rodriguez** [comment]
@bhushangahire 

> How do I pass params with view_context then?

> If you're using the v0.4.x use Datatable.new(view_context) in your controllers.
> If you want to use the master branch use Datatable.new(params).

**Comment by n-rodriguez** [comment]
In short : 

If you're using the **v0.4.x** of this gem use `Datatable.new(view_context)` in your controllers. See the [v0.4.x documentation](https://github.com/jbox-web/ajax-datatables-rails/tree/v0.4.x).

If you're using the **v1.x** of this gem (or the master branch) use `Datatable.new(params)` in your controllers, as in the [documentation](https://github.com/jbox-web/ajax-datatables-rails#4-setup-the-controller-action).

**Comment by Xavoski** [comment]
i am using gems ajax-datatables-rails 1.0.0 with rails 5.2.0.

My controller is:
<pre>
 def index
 respond_to do |format|
  format.html
  format.json { render json: CityDatatable.new(params)} 
 end
end
</pre>

If i call <code>cities_path</code> it returns the html page but not load the list, because it was not a json call. If in menu i call <code>cities_path(formet: :json)</code>, the system returns error <code>undefined method 'to_unsafe_h' for nil:NilClass</code> because <code>params</code> is still null at this point.
If i go to <code>cities_path</code> and press F5, my datatable is loaded corectly.
