### ISSUE TITLE
Search using HAVING instead of WHERE

### ISSUE THREAD

**Issue by creativetags** [jbox-web/ajax-datatables-rails#298]
How can I override the default search to use mySQL HAVING instead of WHERE so that I can search on aggregates. I need this because I have some encrypted columns and I need to perform decryption first before searching.

There is some discussion in #29 but it seems the code has changed since then (search_condition is no more).

**Comment by creativetags** [comment]
Just to say I've worked around this by forking the code with this change: https://github.com/jbox-web/ajax-datatables-rails/compare/v0.4.x...creativetags:v0.4.x

**Comment by n-rodriguez** [comment]
great :) Note that if you're using v1.0.0 forking is not mandatory anymore ;)
You can now override this method (`filter_records`) directly in your datatable class.
