### ISSUE TITLE
Complex condition

### ISSUE THREAD

**Issue by ohaddahan** [jbox-web/ajax-datatables-rails#302]
Is it possible to filter by a calculation?
Let's say the filter input is `min: 10`, I want to calculate `(column.a * factor - column.b) > 10` ?
I looked into `cond:` example but it fails :(

**Comment by n-rodriguez** [comment]
>  Let's say the filter input is `min: 10`, I want to calculate `(column.a * factor - column.b) > 10` ?

Use a lambda like in https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb#L34
