### ISSUE TITLE
Pass a form params to the datatable

### ISSUE THREAD

**Issue by p1-alexandrevaney** [jbox-web/ajax-datatables-rails#304]
Hi, i'm trying to use this gem to display data and i want to add additional filters using a form under the table

The form is in the same view : `<%= form_tag(datatable_vulns_path, method: :get) do %>`

and i plan to use scopes to alter raw_records with the params of the form like this : 

```ruby
#vuln_datatable.rb

def get_raw_records
    @vulns = Vuln.all
    if(params[:app].present?)
       @vulns = @vulns.app(params[:app].join(', '))
    end
  return @vulns
end
```

except i don't know how to give the params hash from to form to the vuln_datatable.rb

Do you have an idea on how to do it please ?

Thank you very much

**Comment by Nittarab** [comment]
If you are using v1.0
`VulnDatatable.new(params, app: params[:app])` 
for the older version:
`VulnDatatable.new(view_context,, app: params[:app]`

and in the vuln_datatable.rb
```
#vuln_datatable.rb

def get_raw_records
    @vulns = Vuln.all
    if(options[:app].present?)
       @vulns = @vulns.app(options[:app].join(', '))
    end
  return @vulns
end
```

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails#pass-options-to-the-datatable-class
