### ISSUE TITLE
Rudimentary support for Microsoft SQL Server

### ISSUE THREAD

**Issue by ArkieCoder** [jbox-web/ajax-datatables-rails#306]
This patch works for me to provide rudimentary support for the `sqlserver` adapter for RoR.  

I originally thought this was an issue with the `activerecord-sqlserver-adapter` gem, but it turns out it was `ajax-datatables-rails` all along.  

Here's a link to the issue I created over there: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/658

<pre>
diff -uNr ajax-datatables-rails-1.0.0-orig/lib/ajax-datatables-rails/datatable/column.rb ajax-datatables-rails-1.0.0/lib/ajax-datatables-rails/datatable/column.rb
--- ajax-datatables-rails-1.0.0-orig/lib/ajax-datatables-rails/datatable/column.rb      2018-09-25 19:31:14.336965748 +0000
+++ ajax-datatables-rails-1.0.0/lib/ajax-datatables-rails/datatable/column.rb   2018-09-25 19:32:44.445947455 +0000
@@ -8,6 +8,7 @@
       TYPE_CAST_MYSQL   = 'CHAR'
       TYPE_CAST_SQLITE  = 'TEXT'
       TYPE_CAST_ORACLE  = 'VARCHAR2(4000)'
+      TYPE_CAST_SQLSERVER  = 'VARCHAR(4000)'

       DB_ADAPTER_TYPE_CAST = {
         mysql:          TYPE_CAST_MYSQL,
@@ -15,7 +16,8 @@
         sqlite:         TYPE_CAST_SQLITE,
         sqlite3:        TYPE_CAST_SQLITE,
         oracle:         TYPE_CAST_ORACLE,
-        oracleenhanced: TYPE_CAST_ORACLE
+        oracleenhanced: TYPE_CAST_ORACLE,
+        sqlserver:      TYPE_CAST_SQLSERVER
       }.freeze

       attr_reader :datatable, :index, :options
</pre>

The `VARCHAR(4000)` might be a bit overkill, but it gets the job done right now.  Thanks for the great gem, you've made my life much easier.

**Comment by n-rodriguez** [comment]
@ArkieCoder : pushed on master branch https://github.com/jbox-web/ajax-datatables-rails/commits/master

Put this in your Gemfile to use it : 

```ruby
gem 'ajax-datatables-rails', git: 'https://github.com/jbox-web/ajax-datatables-rails.git'
```
