### ISSUE TITLE
Field should be a string and eq should be cond

### ISSUE THREAD

**Issue by ohaddahan** [jbox-web/ajax-datatables-rails#311]
https://github.com/jbox-web/ajax-datatables-rails/blob/722b55c18106ee16d88be568da9bb3db871bf254/lib/ajax-datatables-rails/datatable/column/search.rb#L90
```

  def raw_search(cond)
             if custom_field?
            ::Arel::Nodes::SqlLiteral.new(field).eq(formatted_value)
          else
            table[field].send(cond, formatted_value)
          end
        end
```

```::Arel::Nodes::SqlLiteral.new(field).eq(formatted_value)``` fails with:
> TypeError: no implicit conversion of Symbol into String

Also it should be:
``` ::Arel::Nodes::SqlLiteral.new(field.to_s).send(cond, formatted_value)```

Hard coding to ```eq``` isn't only wrong since the condition isn't always ```eq``` but it also causes bugs when you supply a ```Range``` input for a ```in``` condition.

**Comment by n-rodriguez** [comment]
@ajahongir how does `custom_field?` work? it was added here https://github.com/jbox-web/ajax-datatables-rails/commit/8cb169c2aae1dc987462cc0a73c76c87617c0d83 but with no tests.

I'm adding specs on this use case but I'm wondering how it works actually since I don't use it.

**Comment by n-rodriguez** [comment]
Actually this was a mistake. It's now covered by https://github.com/jbox-web/ajax-datatables-rails/commit/b79f3bfc78142516583616e66a37004c7d98fdd4
