### ISSUE TITLE
Support Scroller extension

### ISSUE THREAD

**Issue by Nittarab** [jbox-web/ajax-datatables-rails#312]
What do you think about the scroller extension?

https://datatables.net/extensions/scroller/

Could be easily to implement the pagination?

**Comment by n-rodriguez** [comment]
> Could be easily to implement the pagination?

I give it a try and I think this case is already handled : https://github.com/jbox-web/ajax-datatables-rails/pull/264.
Except a little JS bug when you scroll with the mouse wheel, it seems to work :)

**Comment by Nittarab** [comment]
@n-rodriguez i'll try as soon as possible, in the meantime i'll close the issue. Thank you!
