### ISSUE TITLE
Render partial do block in Datatables

### ISSUE THREAD

**Issue by abelavila140** [jbox-web/ajax-datatables-rails#320]
Im trying to `render` a partial with a `do` block:

```
def data
    records.map do |record|
      {
        subcategory: record.name,
        category: record.name,
        link: actions_dropdown(record)
      }
    end
end

private
  def actions_dropdown(record)
    render_to_string(partial: 'actions_button', formats: [:html]) do
      = link_to('Edit', edit_category_path(record), class: 'dropdown-item')
    end
  end
```
Is this possible?

**Comment by abelavila140** [comment]
Any ideas?

**Comment by aantillon** [comment]
I don;t think so, but you can try and report why it doesn't... think a `DataTables` class delegates to `view`, but not sure really if `render` is an available method in the view, that would be in the controller, wouldn't it?

**Comment by abelavila140** [comment]
@aantillon you can use `render_to_string` using the controller, but I wanted to be able to use a block with it.

**Comment by n-rodriguez** [comment]
you can inject the controller in the datatable an call render when you need it :

```ruby
UserDatatable.new(params, controller: self)

# The datatable class
class MyDatatable < AjaxDatatablesRails::ActiveRecord
  def controller
    @controller ||= options[:controller]
  end

  def actions_dropdown(record)
    controller.render(partial: 'actions_button') do
      link_to('Edit', edit_category_path(record), class: 'dropdown-item')
    end
  end
end
```
but this is very ugly.

**Comment by abelavila140** [comment]
@n-rodriguez So im getting a double render error when trying to do this.

**Comment by n-rodriguez** [comment]
> @n-rodriguez So im getting a double render error when trying to do this.

oh... of course...

**Comment by n-rodriguez** [comment]
did you try this? https://blog.bigbinary.com/2016/01/08/rendering-views-outside-of-controllers-in-rails-5.html

**Comment by abelavila140** [comment]
That really didnt fix the problem with the double rendering. But if I use `@controller.render_to_string`, I do not get any errors. However, none of the links in my do-block get set.

**Comment by abelavila140** [comment]
@n-rodriguez

**Comment by Okomikeruko** [comment]
I stumbled upon this issue when looking for a solution to something similar. So if anyone else stumbles into here looking for a solution to the problem I had, here's what I did. 

The problem I was having with this issue was:

    ActionView::MissingTemplate (Missing partial admin/customers/_controls with {:locale=>[:en], :formats[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :haml]}. Searched in:
     * "/home/ubuntu/environment/project_folder/app/views"
     * "/home/ubuntu/.rvm/gems/ruby-2.6.2/gems/simple_calendar-2.3.0/app/views"
     * "/home/ubuntu/.rvm/gems/ruby-2.6.2/gems/devise-4.6.2/app/views"

So I ended up doing the following with my CustomerController.rb:

    class CustomerController < ApplicationController
      def index 
        respond_to do |format|
          format.html
          format.json { render json: CustomerDatatable.new(params, controller: self) }
        end 
      end 
    end 

And in my CustomerDatatable.rb:

    class CustomerDatatable < AjaxDatatablesRails::ActiveRecord 
      def view_columns
        @view_columns ||= {
          :last_name => { source: "Customer.last_name" },
          :first_name => { source: "Customer.first_name" },
          :email => { source: "Customer.email" },
          :controls => { source: "", orderable: false }
        }
      end
    
      def data
        records.map do |record|
          {
            :last_name => record.last_name,
            :first_name => record.first_name,
            :email => record.email,
            :controls => render_controls(record),
            :DT_RowId => record.id 
          }
        end
      end
    
      def get_raw_records
        Customer.all
      end
    
      def controller
        @controller ||= options[:controller]
      end
    
      def render_controls(record)
        controller.render_to_string(
          partial: "admin/customers/controls",
          formats: "html",
          locals: { :customer => record }
         )
      end
    end

It was the `formats: "html",` that fixed my issue.

**Comment by n-rodriguez** [comment]
For this kind of issue Draper is IMHO a better solution.
See https://github.com/jbox-web/ajax-datatables-rails#using-view-decorators (the `dt_actions` method)
