### ISSUE TITLE
sanitizing data causes "undefined method `strip' for #<Array..."

### ISSUE THREAD

**Issue by epipheus** [jbox-web/ajax-datatables-rails#325]
I'm getting an error in the browser when ajax-datatables-rails calls `sanitize(data)` [here](https://github.com/jbox-web/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L36)

When I track it down it doesn't like [this line in Nokogiri ](https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/html/document_fragment.rb#L35)(parent of Loofah)

```ruby
          # This is a horrible hack, but I don't care
          if tags.strip =~ /^<body/i
            path = "/html/body"
          else
            path = "/html/body/node()"
          end
```

**Comment by n-rodriguez** [comment]
Closing the issue since you found the bug ;) thank you :+1:
