### ISSUE TITLE
Alternate API

### ISSUE THREAD

**Issue by mrinterweb** [jbox-web/ajax-datatables-rails#335]
I was migrating about 20 datatables to the latest API, and the new API required significant refactoring of the existing datatables. I had a little extra time so I wanted to see how it would be to write an alternate API that was had less duplication. I consider this to be shorthand for ajax-datatables-rails. I extracted the API into a gem https://github.com/Shipstr/ajax-datatables-rails-alt-api.

If there are ideas in my alternate API gem that you'd like to bring over to `ajax-datatables-rails`, I'd be into helping with that and I'll create some PRs.

**Comment by reginato** [comment]
hi @mrinterweb  im looking for the same feature, did it work for you, i need some help?

**Comment by mrinterweb** [comment]
@reginato the gem I wrote that extends ajax-datatables-rails worked for me, but it is something I no longer maintain.
