### ISSUE TITLE
Sorting association columns

### ISSUE THREAD

**Issue by codex0098** [jbox-web/ajax-datatables-rails#34]
I'm getting sql syntax error because it is trying to map with the datatable dsl model when i try to sort on one of model associations.
Was wondering what needs to be changed in sortable_columns method

Any help appreciated

thnx

**Comment by codex0098** [comment]
Override sorted_columns private method and  built model query with includes and joins in get_raw_records method

**Comment by antillas21** [comment]
Most of the time, you don't need to override methods. For example, suppose you have the following `sortable_columns` implementation:

``` ruby
def sortable_column
  @sortable_columns ||= [
    'clients.name', 'clients.email', 'orders.order_number',
    'orders.created_at', 'orders.amount'
  ]
end
```

from a query that retrieves orders and clients data, you would need to implement a query like this in `get_raw_records`

``` ruby
def get_raw_records
  Order.joins(:client)
  # depending on model relationships, this sometimes works best:
 # Order.includes(:client)
end
```

**Comment by codex0098** [comment]
+1 @antillas21 .. Thanks, it worked. I did the same
