### ISSUE TITLE
json callback not made upon first load

### ISSUE THREAD

**Issue by amanbop** [jbox-web/ajax-datatables-rails#35]
If I click on url generated by link_to "Clients", clients_path, I only see the empty table rendered in index. If I click reload on browser address bar then everything works. Here is my code

clients_controller.rb

```
class ClientsController < ApplicationController
  def index
    # populate the @clients variable with clients the user can access, sort them, and paginate
    # set breadcrumb
    add_breadcrumb "Clients", clients_path
    respond_to do |format|
      format.html
      format.json { render json: ClientDatatable.new(view_context) }
    end
  end
```

view index.html.erb in clients

```
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table id="clients", class="table", data-source="<%= clients_path(format: :json) %>" >
    <thead>
        <tr>
            <th>Name</th>
            <th>Matter</th>
            <th>Custodians</th>
            <th>Collections</th>
            <th>Items</th>      
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<%= link_to t('.new', :default => t("helpers.links.new")),new_client_path,:class => 'btn btn-primary' %>
<%= link_to 'Clients', clients_path %>

```

clients.js.coffee

```
jQuery ->
  $('#clients').dataTable
    paginationType: "full_numbers"
    processing: true
    serverSide: true
    ajax: $('#clients').data('source')

```

json callback i.e. data-source="<%= clients_path(format: :json) %>" does not work if I click on url formed by <%= link_to 'Clients', clients_path %>. Call to controller is made but index.html.erb is rendered but without any data. But if I put my cursor in the adderss bar and press enter or hit reload on the address bar of browser the page is rendered with the data.

I am using bootstrap for datatable layout.

**Comment by antillas21** [comment]
Questions:
- What does the `add_breadcrumb "Clients", clients_path` call in the controller index action do?
- Why would you put a link to the same page you are already rendering in the page you are seeing?

Also, and most important (perhaps)
- Do you have `turbolinks` enabled in your app?

**Comment by amanbop** [comment]
@antillas21 
add_breadcrumb just adds a bread crumb link to the view
link was there as I was testing some stuff
yes I had turbolinks enabled and that was causing the issue. Disabling it fixed it. So +1 for you :-)

How can this be used with trubolinks though?

**Comment by antillas21** [comment]
@amanbop Hey, nice to know `turbolinks` was the reason behind this misbehavior... and disabling it makes the problem go away.

I would not know how to solve this while having `turbolink` enabled, as I myself **always** recommend to turn it off :wink: LOL.

I think the issue here is that in your JS code, you are relying and triggering datatables after `document.ready` ... and `turbolinks` changes this cycle and recommends calling events on `document.load`.

Again, this is just guess and you would need to check both `turbolinks` and `jQuery.dataTables` documentation. Good luck on your findings.
