### ISSUE TITLE
How to define a default sort column?

### ISSUE THREAD

**Issue by NSNJRGL** [jbox-web/ajax-datatables-rails#359]
Thank you for great gem. How do I define default order column and order type? Please let me know.
Thanks 😊

**Comment by cubytz** [comment]
@NSNJRGL Did you find the answer to your question?

**Comment by NSNJRGL** [comment]
I don't remember, But I figured it out. I'll share it when I found my solution hhe ;) @cubytz

**Comment by ashwini-seshadri** [comment]
https://datatables.net/examples/basic_init/table_sorting.html
