### ISSUE TITLE
documentation around options

### ISSUE THREAD

**Issue by hoguej** [jbox-web/ajax-datatables-rails#36]
The Options examples is confusing. I think this is how it works... not even sure, but looks like it from the code. This seems like a better-ish example.

``` ruby


class UnrespondedMessagesController < ApplicationController
  def index
    datatable = UnrespondedMessagesDatatable.new(view_context,
      { :foo => { :bar => Baz.new }, :from => 1.month.ago }
    )
    repsond_to do |format|
      format.json { render json: datatable }
    end
  end
end

class UnrespondedMessagesDatatable < AjaxDatatablesRails::Base
  # customized methods here
  def get_raw_records
    UnrespondedMessages.where(created_at: self.options[:foo][:from]..DateTime.now)
  end
end
```

**Comment by antillas21** [comment]
Hi @hoguej ,

Yes, your example better describes the intention. Though inside the datatable class, you wouldn't need to call self, as you are instantiating the class and in the `AjaxDatatablesRails::Base` class we have defined `attr_reader :options`. You can [take a look at this here](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L6-L12).

If you would like to contribute your example to the README file, it is most welcome :smile:

**Comment by antillas21** [comment]
@hoguej 

I have updated the `README` with an example similar to what you wrote. You ca take a look here: https://github.com/antillas21/ajax-datatables-rails#options

Thanks for bringing this into our attention :smile:
