### ISSUE TITLE
Postgresql and mysql in one rails app

### ISSUE THREAD

**Issue by keesvandenbos** [jbox-web/ajax-datatables-rails#364]
Hi,

Is it possible to support both pg and mysql in one rails app? I need to use both databases and setting db_adapter only lets me initialize only one of the two?

Many thanks in advance for any help.

**Comment by n-rodriguez** [comment]
> Is it possible to support both pg and mysql in one rails app? I need to use both databases and setting db_adapter only lets me initialize only one of the two?

I don't think it's possible right now...

**Comment by n-rodriguez** [comment]
> Is it possible to support both pg and mysql in one rails app? I need to use both databases and setting db_adapter only lets me initialize only one of the two?

You can now set the `db_adapter` setting on the datatable class.

See: https://github.com/jbox-web/ajax-datatables-rails#change-the-db-adapter-for-a-datatable-class

Note: this is on `master` branch and ready to be released soon.
