### ISSUE TITLE
 Search does not work on a column for model relations

### ISSUE THREAD

**Issue by zpaulovics** [jbox-web/ajax-datatables-rails#37]
Hi Antillas21,

I have already spent two days with this issue, but could not find a working solution. My be a did something wrong. My datatables related details are:
### javascript

```
$.extend( $.fn.dataTable.defaults, {
  dom: "<'row'<'col-sm-4'l<'pull-right'i>><'col-sm-8'<'pull-left'f><'pull-right'pT>>r>t<'row'<'col-sm-3'i><'col-sm-9'p>>",
  displayLength: 25
  processing: true
  columnDefs: [
    { "orderable": false, "targets": -1 }
  ]
} )

$ ->
  $('#event_table').dataTable
    order: [[ 3, "asc" ]]
    serverSide: true
    ajax: $('#event_table').data('source')
```
### Code from event_datatable.rb

```
  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= [
        'coursetypes.natural_id',
        'courses.name',
        'events.title',
        'events.event_start',
        'events.event_end',
        'contacts.last_name',
        'competency_types.name',
        'events.status'
    ]
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns ||= [
       # 'course.name',
        'events.title',
        'events.event_start',
        'events.event_end',
        'events.status'
    ]
  end

  def get_raw_records
    Event.includes([{course: :coursetype}, {allocations: {teacher: [:contact, {competencies: :competency_type}]}} ]).distinct
  end
```
### Results

The sort works fine even if I select a column from an associated table like the course. The select query is generated from the ActiveRecord::Relation object returned from my get_raw_records. Here is the related SQLs from the log:

```
   (0.8ms)  SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events`
   (1.0ms)  SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events`  WHERE ((((`events`.`title` LIKE '%%' OR `events`.`event_start` LIKE '%%') OR `events`.`event_end` LIKE '%%') OR `events`.`status` LIKE '%%'))
  SQL (19.9ms)  SELECT  DISTINCT `events`.`id` FROM `events` LEFT OUTER JOIN `courses` ON `courses`.`id` = `events`.`course_id` LEFT OUTER JOIN `coursetypes` ON `coursetypes`.`id` = `courses`.`coursetype_id` LEFT OUTER JOIN `allocations` ON `allocations`.`event_id` = `events`.`id` LEFT OUTER JOIN `teachers` ON `teachers`.`id` = `allocations`.`teacher_id` LEFT OUTER JOIN `contacts` ON `contacts`.`id` = `teachers`.`contact_id` LEFT OUTER JOIN `competencies` ON `competencies`.`teacher_id` = `teachers`.`id` LEFT OUTER JOIN `competency_types` ON `competency_types`.`id` = `competencies`.`competency_type_id` WHERE ((((`events`.`title` LIKE '%%' OR `events`.`event_start` LIKE '%%') OR `events`.`event_end` LIKE '%%') OR `events`.`status` LIKE '%%'))  ORDER BY courses.name ASC LIMIT 100 OFFSET 0
```

The search also works fine if search on a column of the Event model, but when I uncomment the search column definition for 'course.name' to make search, I got the following error message

```
   (0.7ms)  SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events`
   (0.4ms)  SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events`  WHERE (((((`courses`.`name` LIKE '%%' OR `events`.`title` LIKE '%%') OR `events`.`event_start` LIKE '%%') OR `events`.`event_end` LIKE '%%') OR `events`.`status` LIKE '%%'))

Mysql2::Error: Unknown column 'courses.name' in 'where clause': SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events`  WHERE (((((`courses`.`name` LIKE '%%' OR `events`.`title` LIKE '%%') OR `events`.`event_start` LIKE '%%') OR `events`.`event_end` LIKE '%%') OR `events`.`status` LIKE '%%'))
Completed 500 Internal Server Error in 26ms
```

When it retrieves the filtered set of records by the query declared in the get_raw_records method, with :recordsFiltered => filter_records(get_raw_records).count(:all) it seems the created SQL select is only for the events table, ignoring the ActiveRecord::Relation object returned from get_raw_records.

**Comment by antillas21** [comment]
Hi @zpaulovics ,

Could you try the following, please:
- The column reference for course name does not follow `ActiveRecord` conventions, think it should be `courses.name`, remember, table names are plural :)
- Now, I'm almost sure the easiest way to have search working on a related table, is to use a `joins` clause, instead of an `includes`. Though some times, using an `.includes(:related_table).references(:related_model)` works better in terms of query efficiency.

Hope this helps.

**Comment by zpaulovics** [comment]
Hi Antonio,

Thank you for your quick answer. It helped to solve my problem. 
1. To change the table name plural, did not solved the problem. It was a misspelling, I always using plural names for tables so the correct string is ‘courses.name’, but it dose not have any relation to the issue.
2. I used include to have LEFT OUTER JOIN, because I also want to include in the list those events that does not have teacher allocated. But your comment on this showed me the solution, and I could understand the real reason of the issue. 

When I used include in my query I assumed that the include forces the eager loading, which you need when want to apply the search criteria on any columns of an associated table. But include only forces the eager loading if you have a where condition in the ActiveRecord::Relation object. In the query for :recordsFiltered => filter_records(get_raw_records).count(:all) no where clause appended if you leave empty the search field of the table. In this case include will generate 2 SQL queries (one for the Event model, and then another for the associated tables). The :recordsFiltered => filter_records(get_raw_records).count(:all) will use only the first one to return from the ActiveRecord::Relation object in get_raw_records. That is why I got the error message.

### Solution one

You should append .references(:related_model) for any associated table, as you suggested. That forces the eager loading of all the associated models by one SQL query, and the search condition for any column works fine. So the working query is:

```
Event.includes([{course: :coursetype}, {allocations: {teacher: [:contact, {competencies: :competency_type}]}} ]).references(:course).distinct
```

The generated SQL is:

```
SELECT DISTINCT COUNT(DISTINCT `events`.`id`) FROM `events` LEFT OUTER JOIN `courses` ON `courses`.`id` = `events`.`course_id` LEFT OUTER JOIN `coursetypes` ON `coursetypes`.`id` = `courses`.`coursetype_id` LEFT OUTER JOIN `allocations` ON `allocations`.`event_id` = `events`.`id` LEFT OUTER JOIN `teachers` ON `teachers`.`id` = `allocations`.`teacher_id` LEFT OUTER JOIN `contacts` ON `contacts`.`id` = `teachers`.`contact_id` LEFT OUTER JOIN `competencies` ON `competencies`.`teacher_id` = `teachers`.`id` LEFT OUTER JOIN `competency_types` ON `competency_types`.`id` = `competencies`.`competency_type_id`
```

### Solution two

You should replace the includes method by the eager_load method. This makes exactly the same result as the solution one. The query is:

```
Event.eager_load([{course: :coursetype}, {allocations: {teacher: [:contact, {competencies: :competency_type}]}} ]).distinct
```

Hope this description will help any folks who may face with the same problem.

But I think there is a bug in the code of base.rb, namely in simple_search method the “params[:search].present? && params[:search][:value].present?” condition should have been used, otherwise you generate empty queries for all searchable columns even if the search field value is empty.

Thank you for your help!

**Comment by antillas21** [comment]
@zpaulovics Glad to know my comment helped you pinpoint a solution.

Would you be interested in contributing your finding into the README or the wiki? I am getting a lot of questions regarding similar issues when building queries inside the datatable class.

**Comment by zpaulovics** [comment]
Yes, of course, I will prepare a pull request.

**Comment by antillas21** [comment]
Awesome! :thumbsup: I am really grateful.

**Comment by antillas21** [comment]
@zpaulovics I have credited your contribution to this gem. You can take a look at the [CHANGELOG](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md#yet-unreleased) and see your name listed.

Thanks again for contributing.

**Comment by zpaulovics** [comment]
Fine, tanks.
