### ISSUE TITLE
NoMethodError: undefined method `or' for nil:NilClass

### ISSUE THREAD

**Issue by cmchetanm** [jbox-web/ajax-datatables-rails#372]
https://github.com/jbox-web/ajax-datatables-rails/blob/a1879513f15934781eed14bde28db3d931e985a2/lib/ajax-datatables-rails/orm/active_record.rb#L46

**Comment by cmchetanm** [comment]
it should be `end.compact.reduce(:or)`

**Comment by n-rodriguez** [comment]
Hi! Do you have a test case?

**Comment by cmchetanm** [comment]
Hi @n-rodriguez , will submit the test case.

**Comment by n-rodriguez** [comment]
> Hi @n-rodriguez , will submit the test case.

thanks!

**Comment by n-rodriguez** [comment]
Hi there! Any news?
