### ISSUE TITLE
Can we use ajax datatable gem and normal JavaScript together in ruby on rails

### ISSUE THREAD

**Issue by Neha-chhajed** [jbox-web/ajax-datatables-rails#387]
Hello,

I am using language ruby on rails in that we use ajax datatable gem and javascript

but my javascript code is not working?

So can we use both together?

**Comment by n-rodriguez** [comment]
Yes, see: https://github.com/jbox-web/ajax-datatables-rails#5-wire-up-the-javascript

**Comment by Neha-chhajed** [comment]
okay.
But I cant use this method column( ).search() because of that gem.

So how we can use this method ?
