### ISSUE TITLE
Sorting encrypted data

### ISSUE THREAD

**Issue by PHRAIN22** [jbox-web/ajax-datatables-rails#393]
I am using the gem Lockbox to encrypt my data. 

It displaying the data works fine. 

Sorting the data seems to be an issue since it sorts with the encrypted hash value instead of the decrypted one. 

Sorting with "ServerSide": false make it possible to sort my columns correctly but it only shows 10 results.
With ServerSide enabled, it retrieves all the data + results but the sorting won't work as expected.

Any ideas what the issue could be?

**Comment by n-rodriguez** [comment]
> Any ideas what the issue could be?

you simply cannot sort encrypted columns in server side mode because data are.. encrypted :)

it works if you set `ServerSide: false` because in this mode sort is done in the browser but you're not using this gem any more :)
