### ISSUE TITLE
Possibility to change operator from AND to OR 

### ISSUE THREAD

**Issue by mrudult** [jbox-web/ajax-datatables-rails#403]
I have got a table where the filters need be joined by `OR` instead of `AND`

Is there a way we can change [this](https://github.com/jbox-web/ajax-datatables-rails/blob/448a754ef98afe5185b00ada052f92b64779d3e0/lib/ajax-datatables-rails/orm/active_record.rb#L51) to accept `:or`?

**Comment by n-rodriguez** [comment]
> Is there a way we can change [this](https://github.com/jbox-web/ajax-datatables-rails/blob/448a754ef98afe5185b00ada052f92b64779d3e0/lib/ajax-datatables-rails/orm/active_record.rb#L51) to accept `:or`?

Yes, just override the existing method : 

 ```ruby
class MyDatatable < AjaxDatatablesRails::ActiveRecord
  def build_conditions_for_selected_columns
    search_columns.map(&:search_query).compact.reduce(:or)
  end
end
```

**Comment by mrudult** [comment]
@n-rodriguez Thanks. It worked.
