### ISSUE TITLE
Ruby 2.7 Deprecated

### ISSUE THREAD

**Issue by jonmchan** [jbox-web/ajax-datatables-rails#425]
Ruby 2.7 is deprecated, failing to even have support in the latest bundler versions. Removing ruby 2.7 from the CI test matrix should be considered since it is failing:

```
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```

**Comment by n-rodriguez** [comment]
We will drop Ruby 2.7 support *after* `ajax-datatables-rails` 1.5.0 release. Thank you!
