### ISSUE TITLE
SQL syntax error because typecast to VARCHAR

### ISSUE THREAD

**Issue by saiqulhaq** [jbox-web/ajax-datatables-rails#43]
hello..
i'm using mysql database and rails version 4.1.6
so i would report that i got error like this

`Mysql2::Error - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR) LIKE '%a%')' at line 1:
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in`block in execute'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
  activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in`execute'
  activerecord (4.1.6) lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
  activerecord (4.1.6) lib/active_record/connection_adapters/mysql2_adapter.rb:232:in`exec_query'
  activerecord (4.1.6) lib/active_record/connection_adapters/mysql2_adapter.rb:240:in `select'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:24:in`select_all'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in`cache_sql'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.1.6) lib/active_record/relation/calculations.rb:265:in`execute_simple_calculation'
  activerecord (4.1.6) lib/active_record/relation/calculations.rb:227:in `perform_calculation'
  activerecord (4.1.6) lib/active_record/relation/calculations.rb:119:in`calculate'
  activerecord (4.1.6) lib/active_record/relation/calculations.rb:34:in `count'
   () home/fu/.rvm/gems/ruby-2.1.1/bundler/gems/ajax-datatables-rails-b8c50d7e2bdc/lib/ajax-datatables-rails/base.rb:40:in`as_json'
  activesupport (4.1.6) lib/active_support/json/encoding.rb:34:in `encode'
  activesupport (4.1.6) lib/active_support/json/encoding.rb:21:in`encode'
  activesupport (4.1.6) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'

and then after some minutes reading your commit history, i found this https://github.com/antillas21/ajax-datatables-rails/commit/2b1715598ab52e4d61189ecac227d3cfe66034ee commit that break sql syntax 

then i change  `[model.arel_table[column.to_sym].as('VARCHAR')])` to  `[model.arel_table[column.to_sym].as('CHAR')])` like previous commit to get it works

i dont know this affected to postgresql db
`

**Comment by antillas21** [comment]
Hi @saiqulhaq ,

Yes, you are right... this is the reason we haven't released a new stable version yet.

That particular commit is based on postgre, where `VARCHAR` is the right answer, as we need to perform searches on non-string based fields converted to strings... if I use `CHAR`, it works on MySQL, but on Postgre it performs a search limited to the first character in the resulting converted string, which is no good.

We need to find the time to provide a `one-size-fits-all` implementation there. If you'd like to contribute a solution, the invitation is open :)

Have a great day.

**Comment by saiqulhaq** [comment]
ok, i just create pull request for this issue https://github.com/antillas21/ajax-datatables-rails/pull/44

**Comment by antillas21** [comment]
Thanks @saiqulhaq ,

I am sorry for the delay in getting back to you, I've been extremely busy at work recently. I will review your PR this weekend and let you know my comments.

I truly appreciate your contribution. Have a great weekend.

**Comment by hasanloo** [comment]
@antillas21 
Would you please merge this PR, because it is essential feature of this great gem.

**Comment by antillas21** [comment]
@hasanloo, @saiqulhaq I am sorry for the delay in merging this PR, I first set to understand what exactly is the change, so I could test and add an entry in the README, but got carried away by day-to-day work.

I will test and merge this ASAP, once I get back to my workstation.

**Comment by antillas21** [comment]
@hasanloo and @saiqulhaq I have completed the merge and released a new version of the gem.

Please refer to these links to find out about the changes:
- [CHANGELOG - ver. 0.2.1](https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md#021)
- [README - Searching on non text-based columns](https://github.com/antillas21/ajax-datatables-rails#searching-on-non-text-based-columns)

@saiqulhaq once again, thanks for contributing :smile:

**Comment by hasanloo** [comment]
@antillas21 and @saiqulhaq  
Thanks!

**Comment by jeet-codecimal** [comment]
I have resolved the issue by adding config initializer as shown below

```
# initializer file
AjaxDatatablesRails.configure do |config|
  # available options for db_adapter are: :pg, :mysql2, :sqlite3
  config.db_adapter = :mysql2
end
```

Thanks to [Antonio Antillon](https://github.com/antillas21) for [detailed answer with parameters](https://github.com/jbox-web/ajax-datatables-rails/issues/70#issuecomment-67876088) as well.
