### ISSUE TITLE
undefined method `count' for nil:NilClass

### ISSUE THREAD

**Issue by rameshkumarxyz** [jbox-web/ajax-datatables-rails#45]
Hi Guys i am getting this error i dont know why , any help will be great.

My controller code

```
def index
     respond_to do |format|
      format.html
      format.json { render json: ServiceTypeDatatable.new(view_context) } 
    end
  end
```

i am getting error here on this line

```
      format.json { render json: ServiceTypeDatatable.new(view_context) } 
```

<h1> Here are my js and view codes</h1>

My js code

```
$('#service-type-table').dataTable
      processing: true
      serverSide: true
      ajax: $('#service-type-table').data('source')
      pagingType: 'full_numbers'
```

My view code

```
<table id="service-type-table", data-source="<%= admin_service_types_path(format: :json) %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Weightage</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
```

ServiceTypeDatatable.rb file code

```
class ServiceTypeDatatable < AjaxDatatablesRails::Base
 include AjaxDatatablesRails::Extensions::Kaminari

  def sortable_columns
       @sortable_columns ||= ['service_types.name','service_types.active','service_types.weightage']
  end

  def searchable_columns
      @sortable_columns ||= ['service_types.name','service_types.active','service_types.weightage']
  end

  private

  def data
    records.map do |record|
      [
        record.name,
        record.active,
        record.weightage
      ]
    end
  end

  def get_raw_records
    # insert query here
  end


end

```

**Comment by antillas21** [comment]
@trkrameshkumar I see that you have an empty `get_raw_records` method... this is the main point of entry to make it all work.

You need to write in this method, the db query needed to retrieve the records you're interested in presenting in a `jquery.dataTable` instance.

Taking a look at the code you have, a very simple (starter) query if you need all `ServiceType` records from your db is to have:

``` ruby
def get_raw_records
  ServiceType.all
end
```

You can learn more about the purpose of this method reading the documentation here: https://github.com/antillas21/ajax-datatables-rails#get-raw-records

**Comment by rameshtyaga** [comment]
@antillas21 you saved my day , Thank you very much for your valuable information, this works for me , i hope we can improve the documentation for ajax-datatables-rails gem , so that others also clearly know how to setup the project on theire environment, in this weekend , i will give a pull request with improved , documentation of ajax-datatables-rails,

Thank you.

**Comment by antillas21** [comment]
Thank @trkrameshkumar, if you have tips on making documentation clearer, please contribute... though, don't take me wrong, but I think it's pretty clear why the method is there when you use the generator, it also has a comment clearly saying: `this is where your query goes` and we mention that fact and method in the documentation as well.

Call it tunnel vision, I have no idea off the top my head to make documentation clearer... will wait for your doc contribution to get a new angle.

**Comment by rameshtyaga** [comment]
Thanks for your quick reply @antillas21 , our existing documentation is perfect , what i was try to say is to give complete tutorial kind of thing to setup the gem on their existing project. and i gm going to do that .

Thank you.

**Comment by antillas21** [comment]
A tutorial would be cool :smile:

Maybe we can add thay to the wiki section (currently not available).

Thanks for your upcoming contribution. Looking forward to what you come up with.

**Comment by rameshtyaga** [comment]
Sure @antillas21 .

**Comment by rameshtyaga** [comment]
@antillas21 as i said, i just completed two part tutorial series for ajax-datatables-rails gem , please visit the wiki to see the tutorials.
