### ISSUE TITLE
Automatic addition of row ID attributes?

### ISSUE THREAD

**Issue by inyerade** [jbox-web/ajax-datatables-rails#47]
Have this the functionality of automatic addition of row ID attributes? With DT_RowId parameter based on http://www.datatables.net/examples/server_side/ids.html

**Comment by antillas21** [comment]
@inyerade if you take a look here: https://github.com/antillas21/ajax-datatables-rails#map-data

It's up to you to define how to return the `data` portion of the resulting JSON structure. We typically recommend returning a 2D array in this key, but you could return anything that `jquery.dataTables` supports. Just remember to adjust your javascript code that consumes the resulting JSON structure if you do so.

**Comment by inyerade** [comment]
I'm new in rails and ruby, how can I get the data vector like [0:'text asd' , 1:'more text' 2:'database text' , DT_RowId:'1']

I try:

```
 def data
    records.map do |record|
      [
        0 : record.id,
        1 : record.name,
        2 : record.last_name
      ]
    end
  end
```

and

```
def data
    records.map do |record|
      [
        0 => record.id,
        1 => record.name,
        2 => record.last_name
      ]
    end
  end
```

but I get errors.

**Comment by antillas21** [comment]
@inyerade you would need to define that data returns an array of hashes, in order to do so:

``` ruby
def data
  records.map do |record|
    {
      DT_RowId: record.id,
      first_name: record.name,
      last_name: record.last_name
    }
  end
end
```

or, taking your example of integer based keys:

``` ruby
def data
  records.map do |record|
    {
      "0": record.id,
      "1": record.name,
      "2": record.last_name
    }
  end
end
```

notice the change from `[]` to `{}` on each `record` iteration.

**Comment by inyerade** [comment]
thx for the tips but the correct and the only one that works was

```
def data
    records.map do |record|
    {
        "0" => record.name,
        "1" => record.short_name,
        "DT_RowId" => record.id,
    }
   end
end
```

**Comment by mariiillo** [comment]
I created a [pull request](https://github.com/antillas21/ajax-datatables-rails/pull/91) related to this issue.

**Comment by antillas21** [comment]
:+1: @emeve89
