### ISSUE TITLE
How do I apply a style to the generated columns?

### ISSUE THREAD

**Issue by cmcguff** [jbox-web/ajax-datatables-rails#49]
If the relevant columns are created by the map, how do I style them individually, i.e. I have some numerics I want right-aligned etc.

**Comment by antillas21** [comment]
Hi @cmcguff ,

Here's something I do whenever I need to style or need markup in columns. Suppose we have an `InvoicesDatatable` and are using FontAwesome icons, and we need to show the "edit" icon next to the "Edit" link and the "remove" icon next to the "Delete" link:

``` ruby
class InvoicesDatatable < AjaxDatatablesRails::Base
  # other methods here
  def_delegators :@view, :link_to, :h, :invoice_path, :edit_invoice_path

  def data
    records.map do |record|
      [
        record.invoice_number
        record.customer,
        record.total,
        link_to("<i class='fa fa-edit'></i> Edit", edit_invoice_path(record)),
        link_to("<i class='fa fa-remove'></i> Delete",
          invoice_path(record), method: :delete,
          data: { confirm: 'Are you sure you want to delete this record?' })
      ]
    end
  end
end
```

You could enter html markup to wrap the data inside for a column, so you can define CSS styles later on, take the total column from the example above.
I can define a delegator to `number_to_currency` and do the following:

``` ruby
class InvoicesDatatable < AjaxDatatablesRails::Base
  # other methods here
  def_delegators :@view, :link_to, :h, :invoice_path, :edit_invoice_path,
    :number_to_currency

  def data
    records.map do |record|
      [
        record.invoice_number
        record.customer,
        as_currency(record.total),
        # other attributes here
      ]
    end
  end

  def as_currency(value)
    "<span class='currency'>#{number_to_currency(value)}</span>"
  end
end
```

Then in a corresponding stylesheet in my project

``` css
.currency {
  text-align: right;
}
```

I could even delegate to `content_tag` and clean the custom `as_currency` method:

``` ruby
class InvoicesDatatable < AjaxDatatablesRails::Base
  # other methods here
  def_delegators :@view, :link_to, :h, :invoice_path, :edit_invoice_path,
    :number_to_currency, :content_tag

  def data
    records.map do |record|
      [
        record.invoice_number
        record.customer,
        as_currency(record.total),
        # other attributes here
      ]
    end
  end

  def as_currency(value)
    content_tag :span, number_to_currency(value), class: 'currency'
  end
end
```

Hope these examples help you define what you need for your use case.

**Comment by cmcguff** [comment]
Yes, that's perfect! Thanks for taking the time to explain in detail.

**Comment by cmcguff** [comment]
Extending this further how would I render a partial?, for example I have a table column with a set of button I'm having trouble figuring out how to call this from the datatable.

```
      <div class="text-right" style="white-space:nowrap;">
        <%= render :partial => "table_actions", :locals => { :r => record } %>
      </div>
```

**Comment by antillas21** [comment]
Well... I'm not sure you can call `render` from a datatable object (even if you add a delegator to the view), given that the datatable class is not a view related class. But you can try though, by adding a delegator to the datatable class like this:

``` ruby
def_delegator :@view, :render
```

**Comment by cmcguff** [comment]
Yeah, that was my first approach, I have ended up just rebuilding the content of the partial in the datatable class - I can live with it and it's working perfectly.

**Comment by paul-ot** [comment]
@cmcguff, in order to render a partial inside a DataTable column, you could add the controller to the DataTable class initializer
```ruby
def initialize(view, controller, options = {})
    @view = view
    @controller = controller
    @options = options
  end
```
And delegate the `render_to_string` method to `@controller`.
```ruby
delegate :render_to_string, to: :@controller
```

After that, in your individual DataTable class `ProductDatatable` on my case, you could do the following
```ruby
  def data
    products.map do |product|
      [].tap do |column|
        column << product.sku
        column << product.name
        column << as_currency(product.price_unit)
        column << as_currency(product.price_pack)
        column << product.pack_units
        column << render_to_string(partial: 'products/list_actions', locals: {market: @options[:market], product: product}, formats: [:html])
      end
    end
  end
```
See the implementation of it, in the last `column << ...` line.

The call from the controller must be:
```ruby
def index
    respond_to do |format|
      format.html
      format.json { render json: ProductDatatable.new(view_context, self, {market: @market}) }
    end
  end
```

I hope it helps.
