### ISSUE TITLE
Can we include code climate GPA score badge on this repo

### ISSUE THREAD

**Issue by rameshkumarxyz** [jbox-web/ajax-datatables-rails#50]
If we include code climate GPA score badge on this repo, that will help us to keep track of the quality of the code.

@antillas21 tell me what do you think.

**Comment by rameshtyaga** [comment]
@antillas21 tell me what do you think.

**Comment by antillas21** [comment]
Done... you can see the new `README` file: https://github.com/antillas21/ajax-datatables-rails#ajax-datatables-rails and find the code climate badge.

**Comment by ricardodovalle** [comment]
Code Climate:  4.0 :clap: :tada::tada::tada:
Congratulations @antillas21

**Comment by antillas21** [comment]
:smile: muito obrigado

**Comment by rameshtyaga** [comment]
@antillas21 Congratlations for getting 4.0 on code climate GPA. We will look forward to improve the code to 10.0, chears.

**Comment by antillas21** [comment]
Thanks @trkrameshkumar ... though from this document: http://docs.codeclimate.com/article/150-glossary-gpa, I think 4.0 is the highest?

**Comment by rameshtyaga** [comment]
ohh.. @antillas21,  sorry my mistake.
