### ISSUE TITLE
Travis build failed.

### ISSUE THREAD

**Issue by rameshkumarxyz** [jbox-web/ajax-datatables-rails#51]
I am seeing travis build status as `failed` on our repo on the read me file.

**Comment by antillas21** [comment]
Hi @trkrameshkumar ,

Yes... the build failure comes from the fact that I haven't had a chance to rework some specs, and thus, such specs are failing due to new dependencies that are not loaded in the test suite.

**Comment by rameshtyaga** [comment]
Ok @antillas21 , now i am on the process of writing test cases for `jquery-datatables-rails` gem,it may take 3 to 4 days, soon after i complete this , we can rework on the specs.

**Comment by antillas21** [comment]
:smile: great!
