### ISSUE TITLE
add callbacks

### ISSUE THREAD

**Issue by saiqulhaq** [jbox-web/ajax-datatables-rails#58]
i think we should add callback like before_initialize or something

**Comment by antillas21** [comment]
Can you elaborate on this? for example, what would be (real-world if possible) benefits of having callbacks.

**Comment by saiqulhaq** [comment]
i have an app that using same column on searchable and sortable
to implement DRY, i override `#initialize` method for assign my instance variable class

``` ruby
def initialize view, options = {}
  super
  @columns = [...]
end

def searchable_columns
  @columns
end

def sortable_columns
  @columns
end
```

but, if we have callback, we must not override the initiliaze method

``` ruby
after_initialize do
  @columns = [...]
end

def searchable_columns
  @columns
end

def sortable_columns
  @columns
end
```

**Comment by antillas21** [comment]
Would it be easier if you define a custom method and reuse it on both method? something like this may work, I think:

``` ruby
def columns
  @columns ||= [... all_columns ...]
end

def searchable_columns
  columns
end

def sortable_columns
  columns
end
```

this way, you wouldn't need to override the `initialize` method... just a thought out of the top of my head.

**Comment by saiqulhaq** [comment]
omg, why i'm not thinking about it LOL
i had to learn ruby anymore
