### ISSUE TITLE
URL to search

### ISSUE THREAD

**Issue by chabgood** [jbox-web/ajax-datatables-rails#59]
Is there a way to generate a url to search by keyword?  <%= link_to 'search', url_path(:term => 'moo')
We have an email that would have a term the user could click on and go to the page with the search performed.

**Comment by antillas21** [comment]
Can you provide more info about this?

If you follow the `README` in the section about view helpers, you'll see a starter example to implement this.

Though, I'm not sure about what is specifically the functionality you are referring to.

**Comment by chabgood** [comment]
I url link in an email generated by rails, to send a search term to the controller.

**Comment by antillas21** [comment]
@chabgood this is regular rails, I fail to see how it relates to this gem, but what you are asking for is:

Suppose the search route is something like `email_search_path` that maps to the `/search?term=` path inside the app domain and your app is deployed at: `http://example.com`. To access it from the outside:

``` ruby
<%= link_to 'Search', email_search_url(term: 'foo') %>
```

Notice how you replace `_path` with `_url` to generate a complete URL to expose the route from the outside world.

This will generate this URL in your mail body: `http://example.com/search?term=foo` as opposed to just `/search?term=foo` by using `email_search_path(term: 'foo')`.

**Important:** make sure you have defined this:

``` ruby
config.action_mailer.default_url_options = { host: 'http://example.com' }
```

In all the environment files inside `config/environments/` (specially `production.rb`) that handle email delivery.

**Comment by chabgood** [comment]
Sorry I meant url,  The url generated is this but does not search:

http://localhost:3000/syteline_orders/manage_buyers?term=57

On Thu, Dec 4, 2014 at 3:54 PM, Antonio Antillon notifications@github.com
wrote:

> @chabgood https://github.com/chabgood this is regular rails, I fail to
> see how it relates to this gem, but what you are asking for is:
> 
> Suppose the search route is something like email_search_path that maps to
> the /search?term= path inside the app domain and your app is deployed at:
> http://example.com. To access it from the outside:
> 
> <%= link_to 'Search', email_search_url(term: 'foo') %>
> 
> Notice how you replace _path with _url to generate a complete URL to
> expose the route from the outside world.
> 
> This will generate this URL in your mail body:
> http://example.com/search?term=foo as opposed to just /search?term=foo by
> using email_search_path(term: 'foo').
> 
> _Important:_ make sure you have defined this:
> 
> config.action_mailer.default_url_options = { host: 'http://example.com' }
> 
> In all the environment files inside config/environments/ (specially
> production.rb) that handle email delivery.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65710622
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
What is the code in the controller and action mapped to that URL?

**Comment by chabgood** [comment]
def manage
    respond_to do |format|
     format.html # index.html.erb
     format.json { render json: SytelineDatatable.new(view_context) }
    end
  end

On Thu, Dec 4, 2014 at 7:40 PM, Antonio Antillon notifications@github.com
wrote:

> What is the code in the controller and action mapped to that URL?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65735341
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
And how are you managing that `:term` param inside the `SytelineDatatable` class?

**Comment by chabgood** [comment]
I am not, how do you do that?  I did not see anything in the docs about
that unless I missed something.

On Thursday, December 4, 2014, Antonio Antillon notifications@github.com
wrote:

> And how are you managing that :term param inside the SytelineDatatable
> class?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65735991
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Perhaps I may need to edit the docs to be more explicit about this, but the idea is that you can pass in an `options` hash. Documentation is here: https://github.com/antillas21/ajax-datatables-rails#options

So, for example, you could do the following:

``` ruby
# in your controller code, you are receiving a term in the params[:term] key
# so you can pass it to the datatable inside an options hash at the end
def manage
  respond_to do |format|
    format.html
    format.json { render json: SytelineDatatable.new(view_params, { term: params[:term] }) }
  end
end

# then just use the options hash inside your datatable class
class SytelineDatatable < AjaxDatatablesRails::Base
  # other methods here
  # ...

  def get_raw_records
    Model.where(term: options[:term])  
  end
end
```

Or even... as `params` are delegated to the view when instantiating a datatable class, perhaps they could be accessed directly like this:

``` ruby
# datatable class
class SytelineDatatable < AjaxDatatablesRails::Base
  # other methods here
  # ...

  def get_raw_records
    Model.where(term: params[:term])  
  end
end
```

**Comment by chabgood** [comment]
Oh ok I will try that shortly.  Thanks.  It is a very cool gem!!

On Thursday, December 4, 2014, Antonio Antillon notifications@github.com
wrote:

> Perhaps I may need to edit the docs to be more explicit about this, but
> the idea is that you can pass in an options hash. Documentation is here:
> https://github.com/antillas21/ajax-datatables-rails#options
> 
> So, for example, you could do the following:
> 
> # in your controller code, you are receiving a term in the params[:term] key# so you can pass it to the datatable inside an options hash at the enddef manage
> 
>   respond_to do |format|
>     format.html
>     format.json { render json: SytelineDatatable.new(view_params, { term: params[:term] }) }
>   endend
> 
> # then just use the options hash inside your datatable classclass SytelineDatatable < AjaxDatatablesRails::Base
> 
>   # other methods here
>   # ...
> 
>   def get_raw_records
>     Model.where(term: options[:term])
>   endend
> 
> Or even... as params are delegated to the view when instantiating a
> datatable class, perhaps they could be accessed directly like this:
> 
> # datatable classclass SytelineDatatable < AjaxDatatablesRails::Base
> 
>   # other methods here
>   # ...
> 
>   def get_raw_records
>     Model.where(term: params[:term])
>   endend
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65739157
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
:smile: Thanks! Glad to be of any help.

**Comment by chabgood** [comment]
hmm , issue:

<%= link_to 'here', manage_buyers_syteline_orders_url(:format => :json,
:po_num => @order.po_id) %>

def manage_buyers
    respond_to do |format|
     format.html
     format.json { render json: SytelineBuyersDatatable.new(view_context, {
:po_num => params[:po_num] }) }
    end
  end

def get_raw_records
    return current_user.syteline_orders.where(:po_id => options[:po_num])
if options[:po_num].present?
    current_user.syteline_orders.scoped
  end

A NoMethodError occurred in syteline_orders#manage_buyers:

  undefined method `[]' for nil:NilClass
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:101:in`block in aggregate_query'

---

## Backtrace:

  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:101:in `block in aggregate_query'
  ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in`each'
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:100:in `each_with_index'
  ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in`each'
  ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in `map'
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:100:in`aggregate_query'
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:84:in `composite_search'
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:72:in`filter_records'
  ajax-datatables-rails (0.2.0)
lib/ajax-datatables-rails/base.rb:40:in `as_json'
  activesupport (3.2.19) lib/active_support/json/encoding.rb:47:in
`block in encode'
  activesupport (3.2.19) lib/active_support/json/encoding.rb:77:in
`check_for_circular_references'
  activesupport (3.2.19) lib/active_support/json/encoding.rb:46:in`encode'
  activesupport (3.2.19) lib/active_support/json/encoding.rb:31:in `encode'
  activesupport (3.2.19)
lib/active_support/core_ext/object/to_json.rb:16:in`to_json'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:93:in
`block in <module:Renderers>'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:35:in
`block in _handle_render_options'
  /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in
`block in each'
  /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in
`each_key'
  /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in `each'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:32:in
`_handle_render_options'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:28:in
`render_to_body'
  actionpack (3.2.19)
lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:88:in `render'
  actionpac

On Thu, Dec 4, 2014 at 8:35 PM, Antonio Antillon notifications@github.com
wrote:

> [image: :smile:] Thanks! Glad to be of any help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65739420
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Rule of thumb is to pass any dependencies to the datatable class... You
require access to the current_user, so you should pass it in the options
hash as well ;)

**Comment by chabgood** [comment]
current_user was working fine.  The search table was working fine before
the addition.

On Thu, Dec 4, 2014 at 9:39 PM, Antonio Antillon notifications@github.com
wrote:

> Rule of thumb is to pass any dependencies to the datatable class... You
> require access to the current_user, so you should pass it in the options
> hash as well ;)
> On Dec 4, 2014 7:27 PM, "Chris Habgood" notifications@github.com wrote:
> 
> > hmm , issue:
> > 
> > <%= link_to 'here', manage_buyers_syteline_orders_url(:format => :json,
> > :po_num => @order.po_id) %>
> > 
> > def manage_buyers
> > respond_to do |format|
> > format.html
> > format.json { render json: SytelineBuyersDatatable.new(view_context, {
> > :po_num => params[:po_num] }) }
> > end
> > end
> > 
> > def get_raw_records
> > return current_user.syteline_orders.where(:po_id => options[:po_num])
> > if options[:po_num].present?
> > current_user.syteline_orders.scoped
> > end
> > 
> > A NoMethodError occurred in syteline_orders#manage_buyers:
> > 
> > undefined method `[]' for nil:NilClass
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:101:in`block in aggregate_query'
> > 
> > ---
> > 
> > ## Backtrace:
> > 
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:101:in `block in aggregate_query'
> > ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in
> > `each'
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:100:in `each_with_index'
> > ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in
> > `each'
> > ajax-datatables-rails (0.2.0) lib/ajax-datatables-rails/base.rb:100:in
> > `map'
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:100:in`aggregate_query'
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:84:in `composite_search'
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:72:in`filter_records'
> > ajax-datatables-rails (0.2.0)
> > lib/ajax-datatables-rails/base.rb:40:in `as_json'
> > activesupport (3.2.19) lib/active_support/json/encoding.rb:47:in
> > `block in encode'
> > activesupport (3.2.19) lib/active_support/json/encoding.rb:77:in
> > `check_for_circular_references'
> > activesupport (3.2.19) lib/active_support/json/encoding.rb:46:in
> > `encode'
> > activesupport (3.2.19) lib/active_support/json/encoding.rb:31:in
> > `encode'
> > activesupport (3.2.19)
> > lib/active_support/core_ext/object/to_json.rb:16:in`to_json'
> > actionpack (3.2.19) lib/action_controller/metal/renderers.rb:93:in
> > `block in <module:Renderers>'
> > actionpack (3.2.19) lib/action_controller/metal/renderers.rb:35:in
> > `block in _handle_render_options'
> > /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in
> > `block in each'
> > /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in
> > `each_key'
> > /home/chabgood/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/set.rb:222:in
> > `each'
> > actionpack (3.2.19) lib/action_controller/metal/renderers.rb:32:in
> > `_handle_render_options'
> > actionpack (3.2.19) lib/action_controller/metal/renderers.rb:28:in
> > `render_to_body'
> > actionpack (3.2.19)
> > lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
> > actionpack (3.2.19) lib/abstract_controller/rendering.rb:88:in `render'
> > actionpac
> > 
> > On Thu, Dec 4, 2014 at 8:35 PM, Antonio Antillon <
> > notifications@github.com>
> > 
> > wrote:
> > 
> > > [image: :smile:] Thanks! Glad to be of any help.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65739420>
> > 
> > > .
> > 
> > ## 
> > 
> > _"In matters of style, swim with the current; in matters of principle,
> > stand like a rock." Thomas Jefferson_
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65742826>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65743547
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Ok, so you have this in your `get_raw_records` method

``` ruby
def get_raw_records
  return current_user.syteline_orders.where(:po_id => options[:po_num])
  if options[:po_num].present?
    current_user.syteline_orders.scoped
  end
end
```

What I see there is you first get the `current_user.syteline_orders` that meet the `po_id: options[:po_num]` criteria, but there may be none... and then you return right after getting them.

As you are using `return` in the first line, the `if` block underneath _never_ gets evaluated. 

Aside from that, the error is raised in the `aggregate_query` method, and that method relies on having the `searchable_columns` method declared... did you add columns to the array in that method?

**Comment by chabgood** [comment]
No columns were added, I think you rearranged my method:

def get_raw_records
    return current_user.syteline_orders.where(:po_id => options[:po_num])
if options[:po_num].present?

```
current_user.syteline_orders.scoped
```

  end

On Thu, Dec 4, 2014 at 10:20 PM, Antonio Antillon notifications@github.com
wrote:

> Ok, so you have this in your get_raw_records method
> 
> def get_raw_records
>   return current_user.syteline_orders.where(:po_id => options[:po_num])
>   if options[:po_num].present?
>     current_user.syteline_orders.scoped
>   endend
> 
> What I see there is you first get the current_user.syteline_orders that
> meet the po_id: options[:po_num] criteria, but there may be none... and
> then you return right after getting them.
> 
> As you are using return in the first line, the if block underneath _never_
> gets evaluated.
> 
> Aside from that, the error is raised in the aggregate_query method, and
> that method relies on having the searchable_columns method declared...
> did you add columns to the array in that method?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65745810
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Ohhh sorry... thought you were missing an `end` there... OK, so I get it:

``` ruby
def get_raw_records
  return current_user.syteline_orders.where(:po_id => options[:po_num]) if options[:po_num].present?

  current_user.syteline_orders.scoped
end
```

OK, so you scope to `syteline_orders` that meet the criteria if `:po_num` is passed... and all `syteline_orders` if not.

Now, you say no columns were added... is that right? So you have this in the `searchable_columns` method?

``` ruby
def searchable_columns
  # list columns inside the Array in string dot notation.
  # Example: 'users.email'
  @searchable_columns ||= []
end
```

If so, then please add the columns you may want to expose to perform searches through the datatables plugin search field.

**Comment by chabgood** [comment]
Yes the columns are there, the table search works normally, it is when I go
to the url:

http://localhost:3000/syteline_orders/manage_buyers.json?po_num=57  it does
that.

On Thu, Dec 4, 2014 at 10:42 PM, Antonio Antillon notifications@github.com
wrote:

> Ohhh sorry... thought you were missing an end there... OK, so I get it:
> 
> def get_raw_records
>   return current_user.syteline_orders.where(:po_id => options[:po_num]) if options[:po_num].present?
> 
>   current_user.syteline_orders.scopedend
> 
> OK, so you scope to syteline_orders that meet the criteria if :po_num is
> passed... and all syteline_orders if not.
> 
> Now, you say no columns were added... is that right? So you have this in
> the searchable_columns method?
> 
> def searchable_columns
>   # list columns inside the Array in string dot notation.
>   # Example: 'users.email'
>   @searchable_columns ||= []end
> 
> If so, then please add the columns you may want to expose to perform
> searches through the datatables plugin search field.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65746943
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by chabgood** [comment]
Oh does it have something to with the view_context and a url and not a view?

On Thu, Dec 4, 2014 at 10:51 PM, Chris Habgood chabgood@gmail.com wrote:

> Yes the columns are there, the table search works normally, it is when I
> go to the url:
> 
> http://localhost:3000/syteline_orders/manage_buyers.json?po_num=57  it
> does that.
> 
> On Thu, Dec 4, 2014 at 10:42 PM, Antonio Antillon <
> notifications@github.com> wrote:
> 
> > Ohhh sorry... thought you were missing an end there... OK, so I get it:
> > 
> > def get_raw_records
> >   return current_user.syteline_orders.where(:po_id => options[:po_num]) if options[:po_num].present?
> > 
> >   current_user.syteline_orders.scopedend
> > 
> > OK, so you scope to syteline_orders that meet the criteria if :po_num is
> > passed... and all syteline_orders if not.
> > 
> > Now, you say no columns were added... is that right? So you have this in
> > the searchable_columns method?
> > 
> > def searchable_columns
> >   # list columns inside the Array in string dot notation.
> >   # Example: 'users.email'
> >   @searchable_columns ||= []end
> > 
> > If so, then please add the columns you may want to expose to perform
> > searches through the datatables plugin search field.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65746943
> > .
> 
> ## 
> 
> _"In matters of style, swim with the current; in matters of principle,
> stand like a rock."  Thomas Jefferson_

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Oooohhh, ooh I think I finally understood what the issue is, LOL, sorry for all the confusion.

Ok, first things first:
- In your email you **should not** link to a json view, you should link to the html version, so you should make the link like this: 

``` ruby
<%= link_to 'here', manage_buyers_syteline_orders_url(:po_num => @order.po_id) %>
```

Notice the removal of the `:format => :json` param. This will look to this controller and action in their html format (which calls the json version to display data, and this _is the way it is supposed to work_).
- Second, in order to access (for debugging purposes) the json view of the route, please use this gem's `version-0-3-0` branch in your `Gemfile`. You can do so, by adding the gem like this in your Gemfile:

``` ruby
gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'version-0-3-0'
```

**Comment by chabgood** [comment]
I took out the json but it is not looking at the po_num param being sent.
The log even shows it not searching for 57.

http://localhost:3000/syteline_orders/manage_buyers?po_num=57

 SELECT `syteline_orders`.\* FROM `syteline_orders` WHERE
`syteline_orders`.`user_id` = 16 AND
((((((((((`syteline_orders`.`poitem_rowpointer` LIKE '%%' OR
`*syteline_orders`.`po_id`
LIKE 0)\* OR `syteline_orders`.`vendor_name` LIKE '%%') OR
`syteline_orders`.`item_name` LIKE '%%') OR
`syteline_orders`.`item_description` LIKE '%%') OR
`syteline_orders`.`buyer` LIKE '%%') OR `syteline_orders`.`unit_mat_cost`
LIKE 0.0) OR `syteline_orders`.`vendor_item_name` LIKE '%%') OR
`syteline_orders`.`due_date` LIKE '%%') OR `syteline_orders`.`status` LIKE
'%%')) ORDER BY syteline_orders.item_name DESC LIMIT 10 OFFSET 0

On Thu, Dec 4, 2014 at 11:01 PM, Antonio Antillon notifications@github.com
wrote:

> Oooohhh, ooh I think I finally understood what the issue is, LOL, sorry
> for all the confusion.
> 
> Ok, first things first:
> - In your email you _should not_ link to a json view, you should link
>   to the html version, so you should make the link like this:
> 
> <%= link_to 'here', manage_buyers_syteline_orders_url(:po_num => @order.po_id) %>
> 
> Notice the removal of the :format => :json param. This will look to this
> controller and action in their html format (which calls the json version to
> display data, and this _is the way it is supposed to work_).
> - Second, in order to access (for debugging purposes) the json view of
>   the route, please use this gem's version-0-3-0 branch in your Gemfile.
>   You can do so, by adding the gem like this in your Gemfile:
> 
> gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'version-0-3-0'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65747865
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
Mmmh... this is very weird.. I have been able to reproduce this bug in a test app.

And what it is even weirder is that I have a production app working properly (when passing an options hash).

Will definitively investigate this. I am suspicious that maybe the addition of `ActiveSupport::Configurable` may be causing this, as the production app was using a version prior to the addition of this module.

Thanks for reporting.

**Comment by antillas21** [comment]
@chabgood I think I have identified where the issue is... it's not in the gem, but rather in the params passed to the controller route, when requesting JSON data.

Here's an example adapted to your case.

You have the following link in an email:

``` ruby
<%= link_to 'here', manage_buyers_syteline_orders_url(:po_num => @order.po_id) %>
```

In that view, you have a datatable from a `<table>` tag whose `data-source` attribute may be pointing at:

``` erb
<table data-source="<%= manage_buyers_syteline_orders_path(format: :json) %>">
...
</table>
```

And the reason why it's not recognizing the `:po_num` param in the datatable.. is because it may be missing from the `data-source` attribute in the html view. So you need to pass this param in your html as well.

``` erb
<table data-source="<%= manage_buyers_syteline_orders_path(po_num: params[:po_num], format: :json) %>">
...
</table>
```

**Comment by chabgood** [comment]
Great minds think alike, I was thinking of doing a similar thing. I was
busy with other tasks today.  THANKS!!

On Fri, Dec 5, 2014 at 5:44 PM, Antonio Antillon notifications@github.com
wrote:

> @chabgood https://github.com/chabgood I think I have identified where
> the issue is... it's not in the gem, but rather in the params passed to the
> controller route, when requesting JSON data.
> 
> Here's an example adapted to your case.
> 
> You have the following link in an email:
> 
> <%= link_to 'here', manage_buyers_syteline_orders_url(:po_num => @order.po_id) %>
> 
> In that view, you have a datatable from a <table> tag whose data-source
> attribute may be pointing at:
> 
> <table data-source="<%= manage_buyers_syteline_orders_path(format: :json) %>">
> ...
> </table>
> 
> And the reason why it's not recognizing the :po_num param in the
> datatable.. is because it may be missing from the data-source attribute
> in the html view. So you need to pass this param in your html as well.
> 
> <table data-source="<%= manage_buyers_syteline_orders_path(po_num: params[:po_num], format: :json) %>">
> ...
> </table>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65872592
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_
