### ISSUE TITLE
No records being returned although there are record on db tables.

### ISSUE THREAD

**Issue by codemilan** [jbox-web/ajax-datatables-rails#61]
I have set up ajax-datatables-rails (0.2.1), jquery-datatables-rails (3.1.1) properly in rails 4.1.4 as per mention in github pages, but I'm not getting any records returned  what is the reason ?

**Comment by antillas21** [comment]
@coderawal can you share a gist of your defined class to help you debug?

**Comment by codemilan** [comment]
sorry antillas21, the problem was with def_delegator  definition syntax, i solved it.

**Comment by antillas21** [comment]
No problemo. If you need any help, please don't hesitate to ask.
