### ISSUE TITLE
undefined method `each_value' for nil:NilClass rails 4

### ISSUE THREAD

**Issue by codemilan** [jbox-web/ajax-datatables-rails#62]
jquery-datatables-rails (3.1.1)
ajax-datatables-rails (0.2.1)
rails (4.1.4)

ajax-datatables-rails (0.2.1) lib/ajax-datatables-rails/base.rb line 65

```
  def sort_records(records)
     sort_by = []
      params[:order].each_value do |item|
        sort_by << "#{sort_column(item)} #{sort_direction(item)}"
  end
```

and screenshot for uploaded_songs.js.coffee file:
![screenshot from 2014-12-09 18 02 05](https://cloud.githubusercontent.com/assets/7425858/5357260/88d475cc-7fcd-11e4-832c-f508ac1a0e2a.png)

and screenshot for uploaded_songs_controller.rb (index action) file:
![screenshot from 2014-12-09 18 04 19](https://cloud.githubusercontent.com/assets/7425858/5357286/ddb1b62c-7fcd-11e4-8405-09b697905c01.png)

and screenshot for uploaded_songs_datatables.rb file:
![screenshot from 2014-12-09 18 00 28](https://cloud.githubusercontent.com/assets/7425858/5357237/54b7ddce-7fcd-11e4-8f2c-41fc236b923b.png)

**Comment by antillas21** [comment]
Have you uncommented any of the pagination modules listed at the top of the template file for your datatable class?

**Comment by codemilan** [comment]
yah, I have uncommented Kaminari as a pagination module.
Also, I have a 'link_to'  tag in a template file, pointing to index action in uploaded_songs_controller as-
uploaded_songs_path(format: :json), clicking on this link too gives this error, I think I'm lacking some concept on using this gem or is this the issue with gem itself.

**Comment by antillas21** [comment]
@coderawal ooh I see... yeah I think where the error comes from...

Please update your `Gemfile` to this:

``` ruby
gem 'ajax-datatables-rails', github: 'antillas21/ajax-datatables-rails', branch: 'master'
```

We have recently [merged a contribution](https://github.com/antillas21/ajax-datatables-rails/commit/79ed2ebac4af990c85750cbebecbfaf1aeca4a38) that checks to see if there are any pagination and sorting params being passed in the URL, and is yet unreleased.

**Do this only if** you want to access the json view of the data sent back to the datatables jquery plugin from the datatable class. **The plugin and gem work just fine without doing this**, as the jquery plugin always sends the required params to the datatable class as params through the URL.

**Comment by antillas21** [comment]
Don't forget to do a 

``` shell
$ bundle update ajax-datatables-rails
```

if you modify your Gemfile.

**Comment by codemilan** [comment]
Thanks antillas21, now it's working perfectly.

**Comment by codemilan** [comment]
again in trouble antillas21, every thing is fine but sorting, searching and perpage record not working, datatable UI is flickering, the code is same as above screenshots it was working before with kaminari uncommented, but now it's not, I updated my gem as you mentioned in above comment and the rsponse are in json format. It's even not working with_paginate gem
