### ISSUE TITLE
How to add custom  filters to data table?

### ISSUE THREAD

**Issue by phlegx** [jbox-web/ajax-datatables-rails#63]
Hi @antillas21!

Any idea how to add custom filters to the table? 
Congratulations for the nice plugin! :smile: 

Thx

**Comment by antillas21** [comment]
Could you please provide an example of what a custom filter is?

Datatables (the jquery plugin) supports adding multiple filters when searching, based on the columns of the table.

Though, if you would like to pre-filter records based on arbitrary filters (not present in the table columns), you can build a set of form controls (outside the table markup) and pass those arguments as options to the datatable class as described in the corresponding `Options` section in the `README`.

**Comment by antillas21** [comment]
Please provide an example of what is you need, in order to help you come up with a solution to your scenario :smile:

**Comment by phlegx** [comment]
Found all on Datatables documentation... Yupppiiii :sob: Thx
