### ISSUE TITLE
Convert from GET to POST

### ISSUE THREAD

**Issue by mcarlotta** [jbox-web/ajax-datatables-rails#66]
Is it possible to convert the default GET to POST? I have a lot of columns and when I pass a certain threshold of filterable columns I run into URITooLong Error.

I messed with this on your legacy version and was able to implement it. But for the newer version, it is unable to find raw records {ie: Products.all }

Error:  

 ActionController::ParameterMissing (param not found: product):
  app/controllers/products_controller.rb:79:in `product_params'
  app/controllers/products_controller.rb:35:in`create'

def index
    respond_to do |format|
      format.html
      format.json { render json: ProductDatatable.new(view_context) }
    end
  end

**Comment by antillas21** [comment]
You can check the jQuery.dataTables plugin documentation here for this feature: http://datatables.net/examples/server_side/post.html

And I believe you will need to modify the route in you application to accept a `POST` request like in your `routes.rb` file:

``` ruby
post 'route_name', to: 'controller#action'
```
