### ISSUE TITLE
undefined method `configure' for AjaxDatatablesRails:Module

### ISSUE THREAD

**Issue by chabgood** [jbox-web/ajax-datatables-rails#67]
in the initializer dir I have this:

AjaxDatatablesRails.configure do |config|
  # available options for db_adapter are: :pg, :mysql2, :sqlite3
  config.db_adapter = :mysql2
end

I get the error when starting rails:

config/initializers/ajax_datatables_rails.rb:1:in `<top (required)>': undefined method`configure' for AjaxDatatablesRails:Module (NoMethodError)

**Comment by antillas21** [comment]
@chabgood what version of the gem do you have? This feature is available on version 0.2.1 as commented here: https://github.com/antillas21/ajax-datatables-rails/blob/master/CHANGELOG.md#021

Any version below 0.2.1 will error out on this.

**Comment by chabgood** [comment]
Ok, I updated the gem to 0.2.1, I am still having an issue, I will close this and open up the real issue.  I thought this would fix it.

**Comment by ahmedecademy** [comment]
@antillas21 sorry I know it's way to old post but I am getting this error.
* ajax-datatables-rails (1.2.0)

 here are logs:
 DEBUG [f73c0771] 	rake aborted!
 DEBUG [f73c0771] 	NoMethodError: undefined method `configure' for AjaxDatatablesRails:Module
 DEBUG [f73c0771] 	/home/live/eCademyDemo/releases/20210106092837/config/initializers/ajax_datatables_rails.rb:3:in `<main>'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/engine.rb:662:in `load_config_initializer'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `each'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/home/live/eCademyDemo/releases/20210106092837/config/environment.rb:5:in `<main>'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/bin/ruby_executable_hooks:24:in `eval'
/home/live/.rvm/gems/ruby-2.6.0@ecademy/bin/ruby_executabl
 DEBUG [f73c0771] 	e_hooks:24:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)

**Comment by ahmedecademy** [comment]
Issue resolved following mentioned changes in link below:
https://github.com/jbox-web/ajax-datatables-rails/blob/master/doc/migrate.md#to-migrate-from-v10x-to-v130

Didn't try it earlier as version in use was 1.2.0, so it was confusing a bit.
