### ISSUE TITLE
Any callbacks available after reloading?

### ISSUE THREAD

**Issue by cmcguff** [jbox-web/ajax-datatables-rails#68]
I have some elements in the datatable that are not refreshing as I expect, specifically bootstrap tooltips and jquery time_ago are not being updated. I suspect I need to reapply the relevant initialization code but not sure where I can hook this in.

Here's the relevant code as an example:

```
def as_comment(value)
  unless value.nil?
    "<span class='glyphicon glyphicon-comment has-tip' data-toggle='tooltip' title='#{value}'></span>"
  end
end

def as_time_ago(value)
  "#{time_ago(value, 'Unchanged')}"
end
```

**Comment by antillas21** [comment]
@cmcguff have you added `time_ago` as a delegator to the `view`? Not (really) sure about it, but I think that's all you may need in that particular case.

Also, as of right now, `ajax-datatables-rails` does not support callbacks... a request was made some weeks ago, but was (at the time) dismissed by the very own person requesting it (https://github.com/antillas21/ajax-datatables-rails/issues/58).

I still find it hard to make a case to add callbacks... until we hit the

> it will really be helpful if ...

moment

**Comment by cmcguff** [comment]
well... it will be really helpful if I could re-apply javascript display helpers after rendering of the datatable :)

for the above examples, I can get the display working manually if I add the following buttons to the form and click them after the display has loaded:

```
<button onclick="$('.timeago').timeago();">time ago</button>
<button onclick="$('.has-tip').tooltip();">tooltips</button>
```

What would be awesome is if there is some way to have this code run automatically after/during rendering.

**Comment by antillas21** [comment]
@cmcguff mmh, don't know... reading your code, perhaps this behavior belongs to the jQuery plugin callback cycle, please take a look here: http://datatables.net/reference/option/#Callbacks

**Comment by cmcguff** [comment]
@antillas21 I think you're right, after a bit of messing around with the ajax callback I settled on the standard drawCallback, works correctly:

```
...
"drawCallback": function(settings) {
    resetDisplay();
},
...

function resetDisplay(){
  $('.timeago').timeago();
  $('.has-tip').tooltip();
}
```

**Comment by abrambailey** [comment]
I went to the issues for this project and typed in 'javascript' and came to this thread... Ironically, I was trying to generate tooltips in the datatable too. Perfect solution. Thanks!
