### ISSUE TITLE
Using options hash to pass in params

### ISSUE THREAD

**Issue by cmcguff** [jbox-web/ajax-datatables-rails#69]
I have updated my controller method to pass in some options from params[] like this

```
@scope = params[:scope] ||= 'all'
if current_user.admin? 
  @type = params[:type] ||= 'New'
else  
  @type = params[:type] ||= 'current'
  @scope = 'me'
end  
respond_to do |format|
  format.html
  format.json { render json: LeaveRequestDatatable.new(view_context, { scope: @scope, type: @type }) }
end
```

When the form changes, I can see the type/scope updating as expected on the form, but I always get the defaults passed through to datatable. Changing the type/scope is through buttons on the screen, changes the url like this ?scope=me&type=Approved

If I hardcode it works exactly as expected, seems that the JSON call is not able to read the params?

**Comment by antillas21** [comment]
@cmcguff please refer to this issue: https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65872592

It presents a similar scenario than what you are building, and the proper answer on how to achieve it is right there :smile:

**Comment by cmcguff** [comment]
Perfect, works exactly as I expect now. Thanks.
