### ISSUE TITLE
MySQL ORM not searching text or varchar columns

### ISSUE THREAD

**Issue by chabgood** [jbox-web/ajax-datatables-rails#70]
Hi Antonio, I included the ORM file for mysql, restarted the server.  It appears that columns that are not text or varchar are not being searched:

AjaxDatatablesRails.configure do |config|
  config.db_adapter = :mysql2
end

"wilcox" is the search term

SELECT `syteline_orders`.\* FROM `syteline_orders` WHERE `syteline_orders`.`user_id` = 16 AND ((((((((((((CAST(`syteline_orders`.`po_line` AS CHAR) LIKE 0 OR CAST(`syteline_orders`.`qty_ordered` AS CHAR) LIKE 0) OR CAST(`syteline_orders`.`qty_received` AS CHAR) LIKE 0) OR CAST(`syteline_orders`.`u_m` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`po_id` AS CHAR) LIKE 0) OR CAST(`syteline_orders`.`vendor_name` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`item_name` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`item_description` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`buyer` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`unit_mat_cost` AS CHAR) LIKE 0.0) OR CAST(`syteline_orders`.`due_date` AS CHAR) LIKE '%wilcox%') OR CAST(`syteline_orders`.`status` AS CHAR) LIKE '%wilcox%')) ORDER BY syteline_orders.qty_ordered ASC LIMIT 100 OFFSET 0

**Comment by saiqulhaq** [comment]
did you use the master branch for ajax-datatables-rails gem source?

**Comment by chabgood** [comment]
Yes I am on 0.2.1.

On Mon, Dec 22, 2014 at 1:39 AM, M. Saiqul Haq notifications@github.com
wrote:

> did you use the master branch for ajax-datatables-rails gem source?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/70#issuecomment-67818260
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
@chabgood looking at the log you pasted in your original comment, there is the search being performed on several columns... This is a wild guess but I think all fields prefixed with `qty` are numeric instead of text? And also `due_date` is not text, but of type datettime?

I can see at the end of the log snippet that the grm ois casting all those fields to `CHAR` and perform a search there.

**Comment by chabgood** [comment]
Those columns with qty and po_id are all int fields.

On Mon, Dec 22, 2014 at 10:11 AM, Antonio Antillon <notifications@github.com

> wrote:
> 
> @chabgood https://github.com/chabgood looking at the log you pasted in
> your original comment, there is the search being performed on several
> columns... This is a wild guess but I think all fields prefixed with qty
> are numeric instead of text? And also due_date is not text, but of type
> datettime?
> 
> I can see at the end of the log snippet that the grm ois casting all those
> fields to CHAR and perform a search there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antillas21/ajax-datatables-rails/issues/70#issuecomment-67869755
> .

## 

_"In matters of style, swim with the current; in matters of principle,
stand like a rock."  Thomas Jefferson_

**Comment by antillas21** [comment]
@chabgood I setup a small example with integer, text and date based columns and MySQL as database engine, to see if I could reproduce your issue, and this is what I get when I enter `ff` into the search box:

``` ruby
# params in the log
Parameters: {"draw"=>"4", "columns"=>{"0"=>{"data"=>"0", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"1", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"2", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"3", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"ff", "regex"=>"false"}, "_"=>"1419274720206"}
```

``` sql
(0.3ms)  SELECT COUNT(*) FROM `orders`
(0.4ms)  SELECT COUNT(*) FROM `orders`  WHERE ((((CAST(`orders`.`id` AS CHAR) LIKE '%ff%' OR CAST(`orders`.`po_number` AS CHAR) LIKE '%ff%') OR CAST(`orders`.`order_number` AS CHAR) LIKE '%ff%') OR CAST(`orders`.`created_at` AS CHAR) LIKE '%ff%'))
  Order Load (0.5ms)  SELECT  `orders`.* FROM `orders`  WHERE ((((CAST(`orders`.`id` AS CHAR) LIKE '%ff%' OR CAST(`orders`.`po_number` AS CHAR) LIKE '%ff%') OR CAST(`orders`.`order_number` AS CHAR) LIKE '%ff%') OR CAST(`orders`.`created_at` AS CHAR) LIKE '%ff%'))  ORDER BY orders.id ASC LIMIT 10 OFFSET 0
Completed 200 OK in 6ms (Views: 4.0ms | ActiveRecord: 1.1ms)
```

This is my setup:

``` ruby
# datatable class
class OrdersDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::SimplePaginator

  def sortable_columns
    @sortable_columns ||= ['orders.id', 'orders.po_number', 'orders.order_number', 'orders.created_at']
  end

  def searchable_columns
    @searchable_columnes ||= ['orders.id', 'orders.po_number', 'orders.order_number', 'orders.created_at']
  end

  private

  def data
    records.map do |record|
      [
        record.id,
        record.po_number,
        record.order_number,
        record.created_at.strftime('%Y-%m-%d')
      ]
    end
  end

  def get_raw_records
    Order.all
    # insert query here
  end
end

# orders_controller
class OrdersController < ApplicationController
 def index
    # @clients = Client.all
    respond_to do |format|
      format.html
      format.json { render json: OrdersDatatable.new(view_context) }
    end
  end
end

# initializer file
AjaxDatatablesRails.configure do |config|
  # available options for db_adapter are: :pg, :mysql2, :sqlite3
  config.db_adapter = :mysql2
end

# schema file
ActiveRecord::Schema.define(version: 20141222184204) do

  create_table "orders", force: true do |t|
    t.integer  "client_id"
    t.string   "order_number"
    t.string   "data"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "po_number"
  end

end
```

``` html
<h1>Listing clients</h1>

<table id="orders-table" data-source="<%= orders_path(format: :json) %>">
  <thead>
    <tr>
      <th>ID</th>
      <th>PO Number</th>
      <th>Order Number</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<br>
```

**Comment by antillas21** [comment]
As you can see... everything is working as expected :smile:

**Comment by chabgood** [comment]
Do you have any idea why it would not be working or how to troubleshot this?

**Comment by chabgood** [comment]
Would there be an issue with a float column?

**Comment by antillas21** [comment]
I thought that it may... but I updated my previos example to add a `float` column to the `orders` table, and this is what I get:

``` ruby
# passing 426 as search value
Parameters: {"draw"=>"9", "columns"=>{"0"=>{"data"=>"0", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"1", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"2", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"3", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"4", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"4", "dir"=>"desc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"426", "regex"=>"false"}, "_"=>"1419292600575"}
```

``` sql
(0.3ms)  SELECT COUNT(*) FROM `orders`
(0.5ms)  SELECT COUNT(*) FROM `orders`  WHERE (((((CAST(`orders`.`id` AS CHAR) LIKE '%426%' OR CAST(`orders`.`po_number` AS CHAR) LIKE '%426%') OR CAST(`orders`.`order_number` AS CHAR) LIKE '%426%') OR CAST(`orders`.`created_at` AS CHAR) LIKE '%426%') OR CAST(`orders`.`total` AS CHAR) LIKE '%426%'))
  Order Load (0.5ms)  SELECT  `orders`.* FROM `orders`  WHERE (((((CAST(`orders`.`id` AS CHAR) LIKE '%426%' OR CAST(`orders`.`po_number` AS CHAR) LIKE '%426%') OR CAST(`orders`.`order_number` AS CHAR) LIKE '%426%') OR CAST(`orders`.`created_at` AS CHAR) LIKE '%426%') OR CAST(`orders`.`total` AS CHAR) LIKE '%426%'))  ORDER BY orders.total DESC LIMIT 10 OFFSET 0
Completed 200 OK in 8ms (Views: 4.3ms | ActiveRecord: 1.3ms)
```

This is the updated code

``` ruby
# schema file
ActiveRecord::Schema.define(version: 20141222235148) do
  create_table "orders", force: true do |t|
    t.integer  "client_id"
    t.string   "order_number"
    t.string   "data"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "po_number"
    t.float    "total",        limit: 24
  end
end

# datatable file
class OrdersDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::SimplePaginator

  def_delegator :@view, :number_to_currency

  def sortable_columns
    @sortable_columns ||= ['orders.id', 'orders.po_number', 'orders.order_number', 'orders.created_at', 'orders.total']
  end

  def searchable_columns
    @searchable_columns ||= ['orders.id', 'orders.po_number', 'orders.order_number', 'orders.created_at', 'orders.total']
  end

  private

  def data
    records.map do |record|
      [
        record.id,
        record.po_number,
        record.order_number,
        record.created_at.strftime('%Y-%m-%d'),
        number_to_currency(record.total.to_f)
      ]
    end
  end

  def get_raw_records
    Order.all
  end
end

```
