### ISSUE TITLE
A way to render the table inside a view after page load?

### ISSUE THREAD

**Issue by chabgood** [jbox-web/ajax-datatables-rails#71]
I am using tabs on rails.  So it goes to a view with tabs, I want to be able to render the table inside a tab on loadup.  I call the dashboard controller method and that renders the view with the tabs.  Is there a way to render the table after the page loads inside the first tab?

**Comment by antillas21** [comment]
@chabgood I don't know how this question relates to this gem... think your question fits better in the documentation of the CSS framework you are using, like [Bootstrap](http://getbootstrap.com/javascript/#tabs) or [Foundation](http://foundation.zurb.com/docs/components/tabs.html).

**Comment by chabgood** [comment]
The way to get the table to generate is call the html method. but how do I do that when the page is already rendered with the tabs?

**Comment by antillas21** [comment]
Perhaps this http://datatables.net/examples/ajax/defer_render.html fits what you need?

The point I want to get across is... if the issue at hand does not directly involve this gem's implementation of a (Ruby) datatable class to fetch, filter, sort and paginate database records through params received via the jQuery dataTables plugin, then your best bet is to check the plugin's documentation at: http://datatables.net/reference/index

**Comment by chabgood** [comment]
Ok, sorry about that.

**Comment by antillas21** [comment]
@chabgood nothing to apologize for... just wanted to note, that there may be better suited places where your questions can be addressed and answered.
