### ISSUE TITLE
undefined method `order' for #<Array:0x007fa3ca408510>

### ISSUE THREAD

**Issue by sman591** [jbox-web/ajax-datatables-rails#73]
I followed the guide at https://github.com/antillas21/ajax-datatables-rails/wiki/Part-2-The-Datatables-with-ajax-functionality, but am running into an error when DataTables queries the server. 

I'm using Rails 3 and SQLite3, maybe this is related? http://stackoverflow.com/questions/13145611/rails-ruby-nomethoderror-undefined-method-order-for-array0x718c278

> undefined method `order' for #Array:0x007fa3cf826160

Bottom of my app/datatables/questionnaire_datatable.rb:

``` ruby
def data
  records.map do |record|
    [
      record.first_name,
      record.last_name
    ]
  end
end

def get_raw_records
  Questionnaire.all
end
```

**Comment by antillas21** [comment]
@sman591 It is related yes, given that `ActiveRecord` previous to Rails 4 returns an `Array` when you call `Model.all` and if you take a look here: https://github.com/antillas21/ajax-datatables-rails#get-raw-records and notice the **IMPORTANT** section, you need to return an `ActiveRecord::Relation` object as a result of the `get_raw_records` method.

So, for Rails 3 you can do the following:

``` ruby
def get_raw_records
  Questionnaire.unscoped
end
```

and this will return what the gem expects (an `ActiveRecord::Relation` object) to be able to chain `order, limit, etc`

**Comment by sman591** [comment]
@antillas21 Aha, that solved it, thank you! Would it be good to have a note about that in the important section?

**Comment by antillas21** [comment]
@sman591 I don't know how to write such a note... would you happen to have an idea about this?

Truth be told, I suffer from developer short sight when it comes to documenting... :smile:

**Comment by sman591** [comment]
@antillas21 Maybe if there were two lines in the code block, with comments next to them for which Rails version they correspond to? Such as:

``` ruby
def get_raw_records
  User.all # Rails 4
  User.unscoped # Rails 3
end
```
