### ISSUE TITLE
Typecasting / Searching Non-Text (sort of) Columns

### ISSUE THREAD

**Issue by msimkins** [jbox-web/ajax-datatables-rails#75]
I use the active record extension to save IP Objects as text strings, however they are encoded, so are not available to search (for example an IP Address of 10.1.1.10 is held in the database as 4^0a01010a

The ActiveRecord process serializes them to or from the database, however, I cannot search for 10.1.1  as the representation is 0a0101 (in that case). This creates an IP Object, which has the to_s to turn it back to a string for display purposes

Is it possible to either use any ActiveRecord serializer functionailty, or  specify the CAST or retrieval method for the field rather than going 'direct' to the database

**Comment by antillas21** [comment]
@msimkins you can override the following methods inside your datatable class to achieve the desired functionality:
- `search_condition` method (defined here: https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L116-L123), you can take a look at how the final search condition is built at the `new_search_condition` method if you're using the latest version (0.3.0) or `deprecated_search_condition` if you're using any other version. Actually, I just noticed I forgot to refactor this, :facepalm:
- the `search_condition` method, (by means of passing the bill to any of the other two methods listed above) uses the `typecast` method (defined here: https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L148-L154), so you have two points where you can introduce your changes.

If you go a full `ActiveRecord` way, perhaps you can lean on `Arel` (as we currently do), just making a prevision for an edge case.

Looking forward to how you address this, and if you'd be interested in contributing back your solution :smile:
