### ISSUE TITLE
Pass URI params into ADR

### ISSUE THREAD

**Issue by Ganasist** [jbox-web/ajax-datatables-rails#76]
I must be doing something fundamentally wrong, but is there a way to pass in URI params from the controller to the Datatables class? Right now everything with ADR is working great, but I cannot pass in a Search query to the class. I've tried using the options hash, but no luck:

```
def index
  respond_to do |format|
    format.html
    format.json { render json: JobDatatable.new(view_context, { test: params[:search] }) }
  end
end
```

In the corresponding Datatables class, trying to access options[:test] either produces nothing or gives me back a huge JSON response that came from the server. If I modify it to this:

```
def index
  @temp = params[:search]
  respond_to do |format|
    format.html
    format.json { render json: JobDatatable.new(view_context, { test: @temp }) }
  end
end
```

It still does not get picked up in the Datatables class. I am basically trying to access something like /users?type=admin and get that into the get_raw_records method for scoped queries.

**Comment by antillas21** [comment]
@Ganasist please refer to this comment, as this exactly describes your case, I think: https://github.com/antillas21/ajax-datatables-rails/issues/59#issuecomment-65872592

If after following the steps described there, you're still experiencing problems, please don't hesitate to ping me here or at my email addres (displayed on my github profile)

**Comment by Ganasist** [comment]
Yes after a bit of tweaking this is the solution… introduce the URI search params into the table’s data-source attribute. In the get_raw_records method I then introduced a conditional query:

def get_raw_records
    unless params[:scoped].blank?
      @jobs = Job.all.relevant_categories(params[:scoped]).includes(:uploads)
    else
      @jobs = Job.all.includes(:uploads)
    end
end

Thank God for your help here! Now I just want to create a dropdown to hit the URI and introduce new scopes for new category searches. It probably won’t work via ajax with my skill level, but still I am very happy about this. Spent 6 hours on it yesterday.

I _definitely_ think you could include a brief section on the Github page for this because I’m sure I’m not the only one who wants to use URI params in datatables searches. Thanks for your help let me know if you have any questions!

John

**Comment by antillas21** [comment]
@Ganasist, would you like to contribute this to the README? I'm always open to suggestions on how to improve documentation... if you can come up with an easy way to explain this, I will merge in a PR that helps other people to understand easily.

What do you say?

**Comment by Ganasist** [comment]
Yes sounds good because I think it would definitely help. I have no time this weekend but next week I should be able to.

Since I’ve never done something like this… should I just send you the text via email and you translate to markup or should I do something formally on GitHub?

**Comment by antillas21** [comment]
The best way to do this is to fork the project (instructions here:https://help.github.com/articles/fork-a-repo/), open a branch for this, make changes to the README file, and open a pull request against this repo (instructions here:https://help.github.com/articles/using-pull-requests/) 

Looking forward to your pull request to improving documentation :)

**Comment by Ganasist** [comment]
Perfect thanks for the instructions. I will do this asap. Hope the instructions are clear. Edit whatever you like. I assume markdown for this

**Comment by antillas21** [comment]
That's right.. The README file uses markdown. You can use the Atom editor to have a split window with markdown on one side and a preview to the other side if that helps you.

**Comment by Ganasist** [comment]
Great. I use Atom so I will try it out.
