### ISSUE TITLE
cannot set @sortable_columns as empty array

### ISSUE THREAD

**Issue by listx** [jbox-web/ajax-datatables-rails#78]
Even if I do

```
...
      columns: [
        {sortable: false, searchable: false}
        {sortable: false, searchable: false}
        {sortable: false, searchable: false}
...
```

in the JS (coffeescript) file, I still get an error and the datatable is empty. It's strange because I get this message:

```
/home/l/webdev/ltbweb/vendor/bundle/gems/ajax-datatables-rails-0.3.0/lib/ajax-datatables-rails/base.rb:169:in `sort_column': [DEPRECATED] Using table_name.column_name notation is deprecated. Please refer to: https://github.com/antillas21/ajax-datatables-rails#searchable-and-sortable-columns-syntax
```

...even though `@sortable_columns` is empty.

The larger context I'm working from is this: I have a `PartnershipSchedule` model, which belongs to a `Partnership`, which in turn could have either a `School` or `Organization`. It's like this:

```
class Partnership < ActiveRecord::Base
  belongs_to :organization # Organization.name is a field
  belongs_to :school # School.name is a field
  has_many :partnership_schedules
```

I need to list all `PartnershipSchedules` in a table, and each row will have a `name`, which is drawn from either the `organization` or `school`, but not both.

Going back to the original problem, I want to first test just listing all the `PartnershipSchedule` items, by their org/school name. This `name` method belongs in `Partnership` and invokes _either_ the `Organization` or the `School` model. Because of my limited SQL skills, I do not want to bother trying to allow this 'name' part to be sortable (is this even possible?). I just want to list all the `PartnershipSchedule` items. So, I need to _disable_ any sorting or searching for now. However, if I leave `@sortable_columns` blank, I get an error. Hence my predicament.

Sorry to write so much in the first post.

**Comment by antillas21** [comment]
@listx A quick, off-the-top of my head workaround for this scenario (making a note here, to add support for scenarios like this) is to override the `sort_records(records)` private method. Just do the following:

``` ruby
class YourDatatable < AjaxDatatablesRails::Base
  # other methods here

  def sort_records(records)
    records
  end
end
```

**Comment by listx** [comment]
Yup, this is a simple but effective workaround. Closing.

**Comment by codemilan** [comment]
after adding this method now the columns defined in sortable_columns methods non of them are being sorted out. query result now is only LIMIT 10 OFFSET 0 no orderby, whats the reason.
Also how can we check that the query in get_raw_records methods has records greater than 0 in our view.

**Comment by nextpulse** [comment]
I am seeing this issue with the latest code. 
The recommended fix removes the sorting feature as noted by @codemilan - so not very useful.

Any updates?

BTW: I am using the updated syntax [Model.col]

**Comment by nextpulse** [comment]
To help others:

Seems issue is fixed with on the branch 'filtering-improvements' 

gem 'ajax-datatables-rails', github: 'ajahongir/ajax-datatables-rails', branch: 'filtering-improvements'
