### ISSUE TITLE
Mysql syntax Error getting while I didn't give sortable_columns and searchable_columns values

### ISSUE THREAD

**Issue by ArunSakthivel** [jbox-web/ajax-datatables-rails#80]
Hi
 If I didn't set the attributes for sortable_columns and searchable_columns. I'm getting below error:

`< Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC LIMIT 10 OFFSET 0' at line 1: SELECT`users`.* FROM`users`ORDER BY  ASC LIMIT 10 OFFSET 0 >`

While I'm searching in the Mysql doc the correct syntax is:
`<SELECT`users`.* FROM`users`ORDER BY  name ASC LIMIT 10 OFFSET 0>`

So, I'm thinking that the column name is missing while generating the SQL query.
My suggestion is, Throw error message from the gem instead of SQL syntax error

**Comment by antillas21** [comment]
Hi @ArunSakthivel ,

This was recently brought to our attention here: https://github.com/antillas21/ajax-datatables-rails/issues/78 ... a quick solution is: https://github.com/antillas21/ajax-datatables-rails/issues/78#issuecomment-72596235

Rest assured, will work on adding support for empty `sortable_columns` arrays soon.

**Comment by antillas21** [comment]
Closing after 4+ months without response.
