### ISSUE TITLE
Inserting span class inside of datatable

### ISSUE THREAD

**Issue by reyntjensw** [jbox-web/ajax-datatables-rails#89]
Hi

I'd like to add some links inside my datatable, but they are using span classes:

```
    link_to("<span class='glyphicon glyphicon-eye-open'></span>", company),
    link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_company_path(company)
    link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, company, method: :delete, data: { confirm: 'Are you sure?' }
```

What is the best way of implementing them?

**Comment by antillas21** [comment]
@reyntjensw please refer to this closed issue that addresses your same scenario.

**Comment by antillas21** [comment]
LOL.. just forgot to include the link: https://github.com/antillas21/ajax-datatables-rails/issues/49

**Comment by reyntjensw** [comment]
Hi Antillas

It worked, thanks!
