### ISSUE TITLE
Undefined method 'params'

### ISSUE THREAD

**Issue by dyohi** [jbox-web/ajax-datatables-rails#9]
I am receiving the following error:

NoMethodError (undefined method `params' for nil:NilClass):

Not sure where params is being called as it is not in the generated UsersDatatable.rb file.

Any help would be appreciated.

David

**Comment by JoelQ** [comment]
Hi David,

I apologize for taking so long to respond, I've been out of town for the past few days.

`params` is used by class `AjaxDatatablesRails` [(source)](https://github.com/JoelQ/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails.rb)  which your class `UsersDatatable` inherits from. I'm not sure why it is not defined in your case. Are you passing in the view context when instantiating `UsersDatatable` in your controller?

**Comment by jpmermoz** [comment]
Hi! Same problem is happening to me.. 

This is my controller:

  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductsDatatable.new(view_context) }
    end
  end

And the ProductsDatatable:

class ProductsDatatable < AjaxDatatablesRails

  def initialize(view)
    @model_name = Product
    @columns = [products.code, products.category_id, products.purchase_price, products.stock, products.box_number, products.expiration_at, products.user_id]
    @searchable_columns = [products.code, products.category_id, products.purchase_price, products.stock, products.box_number, products.expiration_at, products.user_id]
    super(view)
  end

private

```
def data
  products.map do |product|
    [
      product.code,
      product.category.name,
      product.purchase_price,
      product.stock,
      product.box_number,
      product.expiration_at,
      product.user.username
    ]
  end
end

def products
  @products ||= fetch_records
end

def get_raw_records
  Product.all
end

def get_raw_record_count
  search_records(get_raw_records).count
end

# ==== Insert 'presenter'-like methods below if necessary
```

end

Any help would be appreciated, thanks!

Jp

**Comment by seventhsense** [comment]
I got the same error.

```
  User Load (0.2ms)  SELECT "users".* FROM "users"
  CACHE (0.0ms)  SELECT "users".* FROM "users"
Completed 500 Internal Server Error in 3ms

NoMethodError (undefined method `params' for nil:NilClass):
  app/datatables/users_datatable.rb:23:in `users'
  app/datatables/users_datatable.rb:5:in `initialize'
  app/controllers/users_controller.rb:9:in `new'
  app/controllers/users_controller.rb:9:in `block (2 levels) in index'
  app/controllers/users_controller.rb:7:in `index'
```

and following is 23th line of my users_datatable.rb 

```
 23       @users ||= fetch_records
```

so the error may occurs in fetch_records method, i think

any idea?

and full trace

```
/home/seventh/ajax-datatables-rails/lib/ajax-datatables-rails.rb:16:in `method_missing'
/home/seventh/ajax-datatables-rails/lib/ajax-datatables-rails.rb:65:in `page'
/home/seventh/ajax-datatables-rails/lib/ajax-datatables-rails.rb:47:in `paginate_records'
/home/seventh/ajax-datatables-rails/lib/ajax-datatables-rails.rb:43:in `fetch_records'
app/datatables/users_datatable.rb:23:in `users'
```

**Comment by JoelQ** [comment]
Hmmmm... I will need to dig around and do some testing to try to figure out what is going on. I will let you know when I find something

**Comment by Tuckie** [comment]
Any updates on this?  I'm seeing the same issue.

**Comment by jpmermoz** [comment]
I ended up using will_filter gem, I forked it and add it some cool features, including i18n.
Here is the link: https://github.com/codingways/will_filter

**Comment by Tuckie** [comment]
I was able to get this working by switching from:

``` ruby
  @columns = [users.f_name, users.l_name, users.bio]
  @searchable_columns = [users.f_name, users.l_name]
```

to

``` ruby
  @columns = ["users.f_name", "users.l_name", "users.bio"]
  @searchable_columns = ["users.f_name", "users.l_name"]
```
