### ISSUE TITLE
Any way to pass parameter to datatable?

### ISSUE THREAD

**Issue by inyerade** [jbox-web/ajax-datatables-rails#93]
in the function `get_raw_record` I want to do a query acording to the user session.

I'm using Devise and in the where clause I want to add `user_id: current_user.id`

I put the line `puts current_user` in my datatable file into get_raw_record function and get `undefined local variable or method`current_user'`

I think that pass an argument in the call of datatable element in the controller can be a possible solution.

**Comment by antillas21** [comment]
Hi @inyerade 

This is what you need to do in order to pass in an options hash to the datatable class:

In your view, your table code should look like this:

``` erb
<table data-source="<%= my_resource_index_path(current_user: current_user, format: :json) %>">
...
</table>
```

after this, you can access the `current_user` object in your datatable class as `options[:current_user]`, example:

``` ruby
class MyDatatable < AjaxDatatablesRails::Base
  # other methods here
  def get_raw_records
    MyResource.where(user_id: options[:current_user].id)
  end
end
```

**Comment by antillas21** [comment]
Ohh... also don't forget to update the controller code as well ;)

**Comment by inyerade** [comment]
@antillas21  what change do I have to make to the controller?

**Comment by inyerade** [comment]
Thx @antillas21  I solve my last question. And the full answer is
In the controller I write:

```
...
def datatable
    respond_to do |format|
        format.html
        format.json { render json: MyDatatable.new(view_context , {current_user: current_user}) }
    end
end
...
```

And in the datatable element:

```
class MyDatatable < AjaxDatatablesRails::Base
    ...
    def get_raw_records
        MyResource.where(user_id: options[:current_user].id)
    end
end
```

but I do not understand why I have to pass  the `current_user` variable in the view.

```
<table data-source="<%= my_resource_index_path(current_user: current_user, format: :json) %>">
...
</table>
```

For me work well without current_user declaration in the view table call (data-source attribute). Like this:

```
<table data-source="<%= my_resource_index_path(format: :json) %>">
...
</table>
```

**Comment by pawlarius** [comment]
is it possible to do the reverse?
pass parameters from datatables.rb form to controller?
somehow all parameters become nil..

**Comment by inyerade** [comment]
Why you want to do this @Pawlarius ?

**Comment by ajahongir** [comment]
in controller
options = {}
UserDatatable.new(.., options)
p options[:data_from_datatable]

in datatable
options[:data_from_datatable] = true

**Comment by mdnnawaz** [comment]
I tried the above steps but i get NoMethodError - undefined method `to_unsafe_h' for nil:NilClass error

**Comment by inyerade** [comment]
@mdnnawaz maybe you need to see this https://github.com/jbox-web/ajax-datatables-rails/issues/246

**Comment by Angelo-Igitego** [comment]
I had to tweak the code to be able to pass parameters to DataTable. 

Background: I wanted to retrieve comments created in a given period of time. Rails version: 5.2, Ruby version: 2.6.3.

**In the view**: 
```
 <table id="comments-datatable" data-source="<%= comments_path(from: Date.today, to: Date.today, format: :json) %>"> 
```

**Controller code**: 
```
respond_to do |format|
    format.html
    format.json { render json: CommentDatatable.new(params, view_context: view_context, user: current_user, from: params[:from], to: params[:to]) }
end
```
**`comment_datatable.rb`**:
```
 def get_raw_records
    from ||= Date.parse(options[:from]).beginning_of_day
    to   ||= Date.parse(options[:to]).end_of_day
    Comment.where(created_at: from..to).order(created_at: :desc)
  end
```
