### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by antillas21** [jbox-web/ajax-datatables-rails#98]
Recently discovered this blog post: http://www.nikolatodorovic.com/nikolas-blog/rails-4-datatables-110-ajax and the lack of support for Oracle was brought to our attention.

I have contacted the author of the blog post (Nikola Todorovic) and is willing to help us adding support for Oracle :smile: 

So far, @mebezac has done some preliminary research and these are his findings:
- looks like Arel doesn't support the `matches` functionality for Oracle you use to build the search conditions. (https://github.com/rails/arel/blob/d69146d3db96116ef241e3c8b0eb122104bb780b/lib/arel/visitors/oracle.rb).
- There's actually a few issues with arel, but I'm not certain how open they are to pull requests. I noticed when working on Regexp, that they only support PostgreSQL, when it would be easy to add support for other databases.
- Also, in his custom ProductsDatatable, his calling `LOWER` in his query. There's an old ticket https://arel.lighthouseapp.com/projects/36051/tickets/3-case-sensitive-like-vs-case-insensitive-like-match-predicate about case-sensitive searching vs case-insensitive searching that we need to be aware of when working with different databases.
- Also, he's using a scope on his model to have is own custom search method

``` ruby
scope :filter_product_name, -> (product_name) {where("lower(PRODUCTS.NAME) like :search", search: "%#{product_name.downcase}%")}
```
- He says _"I am not sure if you can customized your searches and sorts in this way using gem I mentioned in the beginning."_ But his search method isn't really different than what your search would be doing, and if he wants it sorted, he could do that in `get_raw_records`

**Comment by mebezac** [comment]
If/When testing with Rails >= 4.2 make sure we use the 4.2 branch of oracle-enhanced https://github.com/rsim/oracle-enhanced/tree/rails42

**Comment by n-rodriguez** [comment]
Oracle is now part of the test suite. I close this issue.
